### ISSUE TITLE
Consolidate price list styles

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1012]
Currently we're displaying overall price list data (the full spreadsheet data plus the contract/vendor information) a few different ways. The fields are sometimes in different orders, the erroneous data sometimes swaps places with the good data, the status is noted in different places, etc.

On the CO's data upload step 4 page:
![screencapture-0-0-0-0-8000-data-capture-step-4-1478296678853](https://cloud.githubusercontent.com/assets/509309/20023728/978e280c-a2a7-11e6-97de-6f465c304d1c.png)

On the CO's "view my submitted price lists" pages (`/data_capture/price-lists/<somekey>`):
![screencapture-0-0-0-0-8000-data-capture-price-lists-2-1478294422270](https://cloud.githubusercontent.com/assets/509309/20022940/8874ea0e-a2a2-11e6-93bb-a11be24c516d.png)

On the site admin's "change this price list"/new price list page (`/admin/data_capture/newpricelist/<somekey>`):
![screencapture-0-0-0-0-8000-admin-data_capture-newpricelist-2-1478295832658](https://cloud.githubusercontent.com/assets/509309/20023452/a5edb978-a2a5-11e6-8051-096c18e9109d.png)

On the site admin's approved price list page (same as above but not editable):
![screencapture-0-0-0-0-8000-admin-data_capture-approvedpricelist-2-1478296327357 1](https://cloud.githubusercontent.com/assets/509309/20023680/576c433a-a2a7-11e6-98d7-f7ef75b9f634.png)

**Comment by hbillings** [comment]
Some thoughts here: https://github.com/18F/calc/issues/981#issuecomment-260070171

**Comment by hbillings** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement price list details style changes](https://trello.com/c/QWtdHarC/235-implement-price-list-details-style-changes)

**Comment by hbillings** [comment]
Potentially helpful for modifying the admin price lists: https://medium.com/django-musings/customizing-the-django-admin-site-b82c7d325510

**Comment by hbillings** [comment]
@ericronne, I think you and I should pair on this at some point.

**Comment by ericronne** [comment]
Home page is the priority, natch, but time permitting, i'd love to dive into the admin section (and try [inline price-list editing](https://github.com/18F/calc/issues/1120), too!)

**Comment by tbaxter-18f** [comment]
If you are diving into the admin, I'd love to help if I can. I like twisting new functionality of the django admin, and think it's often under-leveraged.
