### ISSUE TITLE
Style vendor and contract details better

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1013]
I threw the vendor details together super quick and they kinda suck. The font sizes are different than elsewhere on the site, the boldness of the info/labels is reversed from the rest of the site, and in general they just look...wireframey.
![screencapture-0-0-0-0-8000-data-capture-step-4-1478296678853](https://cloud.githubusercontent.com/assets/509309/20024035/60268de4-a2a9-11e6-878c-22bb02dd57b5.png)

**Comment by jseppi** [comment]
Good to close since the card based design has been implemented, @hbillings?
