### ISSUE TITLE
Left-align all table headers

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1014]
Some table headers are right-aligned, probably because they're picking up styles from number cells.
![screencapture-0-0-0-0-8000-data-capture-step-4-1478296678853](https://cloud.githubusercontent.com/assets/509309/20024078/ba376f4c-a2a9-11e6-8fe2-1e7f9aab1a43.png)

**Comment by jseppi** [comment]
Yeah, the `<th>` elements with columns of numbers also have the `.number` class applied to them.
