### ISSUE TITLE
Data table on site admin submitted price lists is odd

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1016]
I don't even, Django.
<img width="1027" alt="screen shot 2016-11-04 at 5 09 07 pm" src="https://cloud.githubusercontent.com/assets/509309/20025156/75dce798-a2b1-11e6-84eb-cdf016e78860.png">

**Comment by jseppi** [comment]
wat 
<img width="391" alt="screen shot 2016-11-14 at 10 45 48 am" src="https://cloud.githubusercontent.com/assets/697848/20273598/87d4ccc4-aa57-11e6-93ae-1cb181b498c2.png">

**Comment by hbillings** [comment]
@jseppi That's GH's terribly unintuitive way of showing deleted labels. (I removed the `frontend` tag in favor of language & skill specific tags.) It freaked me the hell out.

**Comment by jseppi** [comment]
Sure it is, haunted-@hbillings

**Comment by hbillings** [comment]
With the latest table styles, this is no longer an issue.
