### ISSUE TITLE
Approved price list view shouldn't be titled "Change approved price list"

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1018]
Since you can't change the price list on `/admin/data_capture/approvedpricelist/<key>`, the headline should just say "Viewing" or something.
<img width="453" alt="screen shot 2016-11-07 at 5 32 23 pm" src="https://cloud.githubusercontent.com/assets/509309/20082125/262b16ae-a511-11e6-9c42-69f2b51ec46b.png">

**Comment by jseppi** [comment]
I can't figure out how to change this heading. Looks like there might not be a way to do it other than a template override? @toolness: do you know how this could be done?

**Comment by hbillings** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement price list details style changes](https://trello.com/c/QWtdHarC/235-implement-price-list-details-style-changes)

**Comment by hbillings** [comment]
So it looks like somehow Django generates this as the `title`. This in `hourglass/admin/base.html` is what generates the "Change X list" title: 
`{% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}`

I haven't had a chance to chase down where this has to be overridden, but I suspect that it's some sort of built-in admin function that needs to be overridden. :-(
