### ISSUE TITLE
How do we identify a specific price list?

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1019]
There's no canonical way to refer to a discrete price list + its vendor/contract details. This is creating issues with the UX, because we identify them in multiple ways on different pages.

## Current variations
1. Sometimes, we play up the vendor, but vendors can and do have multiple price lists:
<img width="701" alt="screen shot 2016-11-07 at 5 40 26 pm" src="https://cloud.githubusercontent.com/assets/509309/20082230/b72f0386-a511-11e6-8933-22c1558d9f93.png">

2. Sometimes we use both the vendor name and contract number, with the date of the last relevant action:
<img width="426" alt="screen shot 2016-11-07 at 5 46 39 pm" src="https://cloud.githubusercontent.com/assets/509309/20082313/2b5283aa-a512-11e6-8a38-cecc33053fde.png">

and
<img width="959" alt="screen shot 2016-11-07 at 5 50 29 pm" src="https://cloud.githubusercontent.com/assets/509309/20082381/b5bc09a8-a512-11e6-822b-18e42374a269.png">

3. This is lengthy, though, and often results in repeated information:
<img width="966" alt="screen shot 2016-11-07 at 5 45 38 pm" src="https://cloud.githubusercontent.com/assets/509309/20082299/17663710-a512-11e6-8b5e-f6aab93051a3.png">

4. On some pages, we don't even try to summarize what you're looking at:
<img width="427" alt="screen shot 2016-11-07 at 5 40 58 pm" src="https://cloud.githubusercontent.com/assets/509309/20082222/ad333d84-a511-11e6-9ee5-a3462163c401.png">

and
<img width="453" alt="screen shot 2016-11-07 at 5 32 23 pm" src="https://cloud.githubusercontent.com/assets/509309/20082241/cb8981a8-a511-11e6-99f8-c8c08af2d426.png">

## Solutions
If we're going to refer to a price list, we should have a standard way of doing it. Some of these work great as a list view (#2 of above), but not well for a phrase-based structure like "Enter details for..." 

One way to fix this would be simply to go with #4 everywhere there's a phrase and #2 everywhere there's a list. This makes it harder to use verbs in headlines, though, which I like as a matter of clarity and directness. ("What am I going to do on this page? Oh, I'm going to _enter details for that price list_.") 

I suppose we could just say "Enter vendor and contract details" and "View price list details." But I feel like somewhere on the page there should be a unique identifier that reminds the user -- who sees thousands of these -- *which* price list he's viewing at any given time.

I just don't know if that sort of identifier even exists. 😭

**Comment by jseppi** [comment]
We're essentially using the contract number as the unique identifier (though there could be revisions, in which case the date is important, but that wouldn't come up in all views).

I personally prefer the contract number to be presented at the forefront. However, I'm not a real user of the system and I would not be surprised to hear facts or opinions for why the contract number might not be the best leading text to display everywhere.

**Comment by toolness** [comment]
I'm not sure if we're already doing this, but from an architectural standpoint, it might be useful to just define this as the `__str__()` for the `SubmittedPriceList` model, and use e.g. `Enter details for {{ pricelist }}` in our templates.  That way we can set it to the contract number for now, but if that turns out to be ambiguous for some reason, we can easily just change the `__str__()` method without having  to change all our templates.

**Comment by hbillings** [comment]
The more I think about it, the more I'm leaning toward abstracting the titles (option 4).

The thing that feels weird about using the contract number by itself (from a language perspective) is that we're primarily asking for details about the vendor, and the details about the contract are in relationship to the vendor (like, the start date is the start date of the vendor's work on the contract). So if you title Step 2 "Enter details for GS-123-4567" and the first question is, "Is this a small business?" there's a little bit of cognitive dissonance there. 

These kinds of problems go away if that page is just "Enter vendor & contract details." Which is more cardboard and less personable, but also potentially less confusing. 

@tram any thoughts?

**Comment by tram** [comment]
The other thing that is nice about Option 4, @hbillings, is that removing large chunks of content that repeat in the header from page to page will fight header blindness and help folks read the headers.

**Comment by hbillings** [comment]
@ericronne We should pair on this too. This might be a good housekeeping sprint design issue.

**Comment by ericronne** [comment]
oak doak!
