### ISSUE TITLE
Dollar sign in price column is misplaced in data capture step 4

### ISSUE THREAD

**Issue by toolness** [18F/calc#1026]
Not sure if this is already documented somewhere, but the **Price** column in the **Verify *N* rows of data** table looks like this on my Chrome / OSX:

> <img width="98" alt="screen shot 2016-11-08 at 4 46 20 pm" src="https://cloud.githubusercontent.com/assets/124687/20118567/f8303f8c-a5d2-11e6-87d1-0ff8e3b8286f.png">

**Comment by jseppi** [comment]
duplicate of https://github.com/18F/calc/issues/962 ?

**Comment by toolness** [comment]
Ah yeah, my bad!
