### ISSUE TITLE
Rename (or remove) load_data command and associated CSV files

### ISSUE THREAD

**Issue by toolness** [18F/calc#1028]
I just realized that the `load_data` command, which basically loads region 10 bulk CSV data (I think?), has an extremely similar name to Django's built-in [`loaddata`](https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-loaddata) command. We might want to rename it to `load_r10` (short for "load region 10") or remove the command entirely if that's easier (as I *think* the functionality has been superseded by the region 10 bulk upload feature).

**Comment by jseppi** [comment]
I am generally 👍  on removing `load_data` and `load_s70`. Though I could see a potential use case for pre-populating the initial database with the current csv data, I guess.

**Comment by jseppi** [comment]
related (and actually also calls for removing these commands): https://github.com/18F/calc/issues/840

**Comment by toolness** [comment]
Yeah, I do like the ability to instantly seed the db with a bunch of real (or at least real-ish, as time passes and the contracts go out of date) data.  We could potentially make a totally different command that uses `model_mommy` to seed the db with random data, but it might be easier to just leave `load_data` around, but rename it to `seed_db` or somesuch?

**Comment by toolness** [comment]
How about this:

* We get rid of all files in `contracts/docs` except `s70_data.csv` and `hourly_prices.csv`. Alternatively, we could keep only the files that end in `_sample.csv`; they're much smaller.  But since the big files are already in the git repo it seems like we might as well use those, I dunno.
* Rename `contracts/docs` to `contracts/example_data`
* Rename the `load_data` management command to `load_example_r10_data`
* Rename the `load_data` management command to `load_example_r10_data`
* Update the documentation accordingly

The only alternative I can think of is to get rid of _all_ of it but replace it with a `seed_db` command that uses `model_mommy` to recreate the same kind of records, but that feels like a lot of work.

**Comment by toolness** [comment]
Oh wait, I just thought of a different solution.  In #1714 I'm adding a `process_bulk_upload` command that is basically the same thing as `load_data`, only it works with XLSX files, but unlike `load_data`, it follows the exact same code path that's used during bulk upload (as its name implies).  So we could potentially just add Kelly's latest R10 XLSX file to the repo (or add it via Git LFS if we don't want to bloat the repo), which would then allow us to get rid of `load_data`, `load_s70` and all related code.

**Comment by jseppi** [comment]
I like the idea of directing new folks to download the production data and load it into to their local dev instance, definitely more so than including the Excel file.

**Comment by toolness** [comment]
Okydoky. The only thing with downloading the production data is that we wouldn't necessarily get the same `upload_source` mappings that we currently have, but I guess it is probably not that big a deal to replicate that stuff.

**Comment by toolness** [comment]
I guess I will work on adding this functionality, and then we can excise the `load_data` and `load_s70` jibberjabbers.
