### ISSUE TITLE
Consider making it possible to disable ethnio during development

### ISSUE THREAD

**Issue by toolness** [18F/calc#1030]
Somewhat related to #282, I realized now that we actually have a real ethnio screener, it shows up during development:

![2016-11-10_10-24-06](https://cloud.githubusercontent.com/assets/124687/20182451/d540d3f2-a72f-11e6-81ef-209ba038c6ae.png)

It's not that big a deal, but it can be a bit distracting during development. I think that Trammell might even be making it more eye-catching so we get more folks to opt-in, so it might be useful to have a way to disable it during development. (I thought that perhaps it'd remember that I closed it, but it doesn't seem to during development.)

**Comment by jseppi** [comment]
Hrm, yeah, and I wonder if having it on eats up credits or something. I don't have a clue how ethnio billing works, but if it is per page view, we'd certainly want to avoid targeting our localhosts.

**Comment by tram** [comment]
If it helps, there should be a cookie that keeps you from seeing the screener more than once every 60 days: http://help.ethn.io/hc/en-us/articles/200202525-Cookies

**Comment by jseppi** [comment]
Maybe make the screener id an env variable and only include the script when it is defined?
