### ISSUE TITLE
Consider making "Vendor name" an autocomplete field w/ suggestions

### ISSUE THREAD

**Issue by toolness** [18F/calc#1031]
When experimenting with using [Dedupe](https://github.com/datamade/dedupe), I noticed that some of our vendor names clearly refer to the same vendor but with slightly different spellings. For example, Lockheed Martin shows up as:

* Lockheed Martin Corporation
* Lockheed Martin Aspen Systems Corporation
* Lockheed Martin Corporation (d.b.a.) Lockheed Martin
* Lockheed Martin Integrated Systems, Inc.
* Lockheed Martin Federal Healthcare, Inc.

I guess some or all of these might not actually be duplicates, but independent corporate entities (especially the healthcare one) but it's hard to tell.  If any of them are duplicates, though, and if it's likely that the same vendor might have multiple price lists/contract numbers, then it might be useful to not only use dedupe on this field, but also provide autocomplete suggestions for the "vendor name" field so that users can select the most-frequently used spelling of a vendor rather than potentially risk adding another minor variation of the same company's name.

**Comment by jseppi** [comment]
I would bet that at least 3 of those are not duplicates. I wonder if we could instead collect something like [EIN](https://en.wikipedia.org/wiki/Employer_Identification_Number) to uniquely identify vendors.

**Comment by toolness** [comment]
O yea, that'd be nice!

**Comment by toolness** [comment]
FWIW, I made a [GSA eLibrary scraper](https://github.com/18F/calc-analysis/tree/master/elibrary-scraper) that allows us to look up the canonical name for the vendor, given a contract number, so we could use that instead of relying on CALC's vendor name field.
