### ISSUE TITLE
Button row on Step 3 Errors wraps lines when no valid rows

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1032]
Notice in the following screenshot that the Cancel button overflows to the next line:

<img width="996" alt="screen shot 2016-11-14 at 10 00 04 am" src="https://cloud.githubusercontent.com/assets/697848/20271705/41adb11c-aa51-11e6-8f34-95d147d86ce9.png">

This is on `step/3/errors` when a price list with no valid rows is uploaded. Perhaps the easiest fix would be to not display the "Continue without these Rows" button instead of disabling it.

**Comment by hbillings** [comment]
This should be fixed by the new card layout.
