### ISSUE TITLE
Consider cleaning up SIN number column

### ISSUE THREAD

**Issue by toolness** [18F/calc#1033]
While working on the price list functionality in #997 I thought it might be useful to compare a price against comparable offerings in the same SIN number.  However, as we found when working on #612, the SIN field in our database is inconsistently formatted.

Another odd thing is that we're not currently using that SIN field for anything--we're storing values in it, but we're not exposing those values to the user in any way, as far as I can tell (hmm, perhaps we do expose it via the API though, I'm not sure). Perhaps we should at the very least document the fact that its formatting is very inconsistent.

I tried writing a script that attempts to parse the SIN numbers but the formatting is *extremely* inconsistent and varied. It'd take a good amount of work to correctly parse all of them.

**Comment by jseppi** [comment]
Yeah, it is exposed via the API now, per the micropurchase PR: https://github.com/18F/calc/pull/696

**Comment by toolness** [comment]
Oh weird!  I thought #696 was purely cosmetic but it looks like you are right about the API change.

Well, I guess it is kind of funky since someone could e.g. search for SIN `874-2` and it wouldn't find a row whose SIN is `874-1,2` (which really means it's both SIN `874-1` *and* `874-2`). Blerg.

**Comment by jseppi** [comment]
It ended up being cosmetic mostly, but since the dev had already made the API changes, we decided to keep those as well.

**Comment by toolness** [comment]
I managed to write some code that attempts to parse out the individual SIN numbers. It's not perfect by any means, but here's some statistics on it so far.

<details>
<summary>Counts of SIN numbers</summary>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Description</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>874 1</th>
      <td>Consulting Services</td>
      <td>15566</td>
    </tr>
    <tr>
      <th>871 3</th>
      <td>System Design, Engineering and Integration</td>
      <td>12681</td>
    </tr>
    <tr>
      <th>871 1</th>
      <td>Strategic Planning for Technology Programs/Act...</td>
      <td>12121</td>
    </tr>
    <tr>
      <th>871 2</th>
      <td>Concept Development and Requirements Analysis</td>
      <td>11942</td>
    </tr>
    <tr>
      <th>871 6</th>
      <td>Acquisition and Life Cycle Management</td>
      <td>11650</td>
    </tr>
    <tr>
      <th>871 4</th>
      <td>Test and Evaluation</td>
      <td>11171</td>
    </tr>
    <tr>
      <th>871 5</th>
      <td>Integrated Logistics Support</td>
      <td>10189</td>
    </tr>
    <tr>
      <th>874 7</th>
      <td>Program and Project Management</td>
      <td>9878</td>
    </tr>
    <tr>
      <th>874 501</th>
      <td>Supply and Value Chain Management</td>
      <td>7851</td>
    </tr>
    <tr>
      <th>899 1</th>
      <td>Environmental Consulting Services</td>
      <td>6994</td>
    </tr>
    <tr>
      <th>874 507</th>
      <td>Operations &amp; Maintenance Logistics Management ...</td>
      <td>5912</td>
    </tr>
    <tr>
      <th>874 503</th>
      <td>Distribution and Transportation Logistics Serv...</td>
      <td>5601</td>
    </tr>
    <tr>
      <th>874 504</th>
      <td>Deployment Logistics Services</td>
      <td>5182</td>
    </tr>
    <tr>
      <th>874 6</th>
      <td>Acquisition Management Support</td>
      <td>4727</td>
    </tr>
    <tr>
      <th>874 505</th>
      <td>Logistics Training Services</td>
      <td>4417</td>
    </tr>
    <tr>
      <th>899 8</th>
      <td>Remediation and Reclamation Services</td>
      <td>3944</td>
    </tr>
    <tr>
      <th>874 4</th>
      <td>Training Services: Instructor Led Training, We...</td>
      <td>3824</td>
    </tr>
    <tr>
      <th>899 7</th>
      <td>Geographic Information Systems (GIS) Services</td>
      <td>3728</td>
    </tr>
    <tr>
      <th>899 3</th>
      <td>Environmental Training Services</td>
      <td>2992</td>
    </tr>
    <tr>
      <th>871 7</th>
      <td>Construction Management</td>
      <td>2785</td>
    </tr>
    <tr>
      <th>541 4B</th>
      <td>Video/Film Production</td>
      <td>1851</td>
    </tr>
    <tr>
      <th>541 1</th>
      <td>Advertising Services</td>
      <td>1754</td>
    </tr>
    <tr>
      <th>520 13</th>
      <td>Complementary Financial Management Services</td>
      <td>1529</td>
    </tr>
    <tr>
      <th>541 4A</th>
      <td>Market Research and Analysis</td>
      <td>1514</td>
    </tr>
    <tr>
      <th>541 5</th>
      <td>Integrated Marketing Services</td>
      <td>1426</td>
    </tr>
    <tr>
      <th>541 2</th>
      <td>Public Relations Services</td>
      <td>1352</td>
    </tr>
    <tr>
      <th>132 51</th>
      <td>Information Technology Professional Services -...</td>
      <td>1331</td>
    </tr>
    <tr>
      <th>541 3</th>
      <td>Web Based Marketing Services (Small Business S...</td>
      <td>1307</td>
    </tr>
    <tr>
      <th>520 12</th>
      <td>Budgeting</td>
      <td>1210</td>
    </tr>
    <tr>
      <th>874 2</th>
      <td>Facilitation Services</td>
      <td>1147</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>382 3</th>
      <td>TRAINING AND EDUCATIONAL MATERIALS</td>
      <td>71</td>
    </tr>
    <tr>
      <th>871 208</th>
      <td>Resource Efficiency Management (REM)</td>
      <td>67</td>
    </tr>
    <tr>
      <th>871 205</th>
      <td>Energy Program Support Services</td>
      <td>67</td>
    </tr>
    <tr>
      <th>874 597</th>
      <td>Ancillary Repair and Alterations</td>
      <td>56</td>
    </tr>
    <tr>
      <th>874 5</th>
      <td>Ancillary Supplies and/or Services</td>
      <td>50</td>
    </tr>
    <tr>
      <th>C R499</th>
      <td>Other Professional Services</td>
      <td>47</td>
    </tr>
    <tr>
      <th>801 001</th>
      <td>Surface Preparation</td>
      <td>43</td>
    </tr>
    <tr>
      <th>520 20</th>
      <td>Comprehensive Protection Solutions</td>
      <td>40</td>
    </tr>
    <tr>
      <th>520 19</th>
      <td>Data Breach Analysis</td>
      <td>40</td>
    </tr>
    <tr>
      <th>520 14</th>
      <td>Audit &amp; Financial Training Services -(SMALL BU...</td>
      <td>39</td>
    </tr>
    <tr>
      <th>871 203</th>
      <td>Training on Energy Management</td>
      <td>34</td>
    </tr>
    <tr>
      <th>871 211</th>
      <td>Energy Consulting Services</td>
      <td>34</td>
    </tr>
    <tr>
      <th>871 209</th>
      <td>Innovations in Energy</td>
      <td>34</td>
    </tr>
    <tr>
      <th>132 52</th>
      <td>Electronic Commerce Services - SUBJECT TO COOP...</td>
      <td>34</td>
    </tr>
    <tr>
      <th>51 501</th>
      <td>Needs Assessment and Analysis Services</td>
      <td>33</td>
    </tr>
    <tr>
      <th>811 003</th>
      <td>Complete Facilities Management</td>
      <td>33</td>
    </tr>
    <tr>
      <th>811 006</th>
      <td>Facilities Maintenance and Management Consulting</td>
      <td>33</td>
    </tr>
    <tr>
      <th>C F999</th>
      <td>Environmental Services</td>
      <td>31</td>
    </tr>
    <tr>
      <th>874 9</th>
      <td>Off-the-Shelf and Customizable Print, Audio, a...</td>
      <td>28</td>
    </tr>
    <tr>
      <th>871 210</th>
      <td>Water Conservation</td>
      <td>27</td>
    </tr>
    <tr>
      <th>520 10</th>
      <td>Transportation Audits - (SMALL BUSINESS SET AS...</td>
      <td>17</td>
    </tr>
    <tr>
      <th>540 3</th>
      <td>Reusable Laboratory Glassware</td>
      <td>17</td>
    </tr>
    <tr>
      <th>C R422</th>
      <td>Market Research and Public Opinion Services</td>
      <td>3</td>
    </tr>
    <tr>
      <th>C R701</th>
      <td>Advertising Services</td>
      <td>3</td>
    </tr>
    <tr>
      <th>595 28</th>
      <td>Social Services</td>
      <td>1</td>
    </tr>
    <tr>
      <th>541 99</th>
      <td>Introduction of New Services</td>
      <td>1</td>
    </tr>
    <tr>
      <th>595 25</th>
      <td>EEO Services</td>
      <td>1</td>
    </tr>
    <tr>
      <th>595 26</th>
      <td>Private Shared Service Center for non-Core HR ...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>595 22</th>
      <td>Private Shared Service Center for Core HR Serv...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>595 27</th>
      <td>HR Support: Pre-Employment Background Investig...</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</details>

**Comment by toolness** [comment]
I've added the code I used to parse out the SIN data to the new calc-analysis repo here:

https://github.com/18F/calc-analysis/blob/master/contract-analysis/sin-analysis.ipynb

**Comment by toolness** [comment]
I made a [GSA eLibrary scraper](https://github.com/18F/calc-analysis/tree/master/elibrary-scraper) that gives us definitive SIN numbers, but they're for a whole contract, rather than an individual labor category. That said, I _think_ the SIN column in our data just represents denormalized data that's the same for every labor category row in a given contract, but I could be mistaken. (Even if I am mistaken, at least we've got a decent superset of the SINs represented by a labor category.)

**Comment by hbillings** [comment]
What's the next step for employing the scraper?

**Comment by toolness** [comment]
I guess we'd really need to productionalize the code by moving it from Node to Python, and then have it be some sort of cron job that runs at regular intervals.  However, we'd also want to verify with Kelly that getting SIN numbers on a per-contract (rather than per-labor rate) basis would actually be useful.

That said, there's other advantages of the scraper too--we'd be able to validate against eLibrary's name of the contractor, remove hyperlinks to contract PDFs that eLibrary doesn't have them for, and other stuff.
