### ISSUE TITLE
Suggested tweaks to upload flow when data exists

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1035]
Forward: Step 2 -> Step 3, when data is found, display a modal over Step 3's upload box:
<img width="743" alt="screen shot 2016-11-15 at 10 02 02 am" src="https://cloud.githubusercontent.com/assets/509309/20315397/f3f01d96-ab1a-11e6-88f9-2a52993147c1.png">

"Review the current data" would pull up the current `step_3_data` page with both errors and valid data.

"Upload new data" would merely close the modal and allow the user to access the page behind it.

Back: Step 3 upload <- Step 3 errors
WIP

Back: Step 3 upload <- Step 4
WIP

Back: Step 3 errors <- Step 4
WIP

**Comment by jseppi** [comment]
Is this still a desired change, @hbillings?

**Comment by hbillings** [comment]
I think the stuff we talked about in the design studio makes this
irrelevant. Probably.

-- 
Heather Battaglia
Innovation Specialist, 18F
Chicago, IL

**Comment by jseppi** [comment]
ok, closing for now. Can reopen/reformulate if necessary.
