### ISSUE TITLE
Sortable table headers do not have sort indicator styling

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1050]
I'm fairly certain that the sortable tables used to have sort indicators (little up/down arrows), but they appear to not be there currently.

Not a huge priority since we aren't actually using sortable tables anywhere but the Style Guide currently (ref #871).

Image showing that the `th` with `.sorted.ascending` does not have a sort indicator:
<img width="670" alt="screen shot 2016-11-18 at 2 03 38 pm" src="https://cloud.githubusercontent.com/assets/697848/20444887/80f4afac-ad98-11e6-83bd-2141e17f8c09.png">

**Comment by jseppi** [comment]
I think this is very low priority because we aren't actually using our sortable table JavaScript anywhere currently (ref #871).

**Comment by hbillings** [comment]
@jseppi Oh! derp derp

**Comment by hbillings** [comment]
Removed sortable table example in #1207
