### ISSUE TITLE
Education Filter can have duplicate, yet unapplied, values selected

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1056]
To reproduce: 

1. Select one or more education filters from the custom checkbox dropdown. 
2. Reload the page
3. Click on the education filter again. Nothing will be highlighted, but the previously selected values will still be shown.
4. Select more education filters. They will be appended to the existing list.

Screenshots:
Before reload:
<img width="246" alt="screen shot 2016-11-22 at 5 03 37 pm" src="https://cloud.githubusercontent.com/assets/697848/20545647/e90ae88c-b0d5-11e6-9cc4-0db87a2badc8.png">

After reloading and again selecting filters:
<img width="241" alt="screen shot 2016-11-22 at 5 03 52 pm" src="https://cloud.githubusercontent.com/assets/697848/20545652/edd3c758-b0d5-11e6-8db5-f3791399aee3.png">

**Comment by jseppi** [comment]
Note I thought this was due to my eslint refactoring in #1053, but it is also present in the current prod code.

**Comment by toolness** [comment]
Just fixed by #1075!
