### ISSUE TITLE
Proposed Price highlight isn't aligned w/ other highlights

### ISSUE THREAD

**Issue by toolness** [18F/calc#1076]
This is how it looks on the "old" CALC that's still at calc.gsa.gov:

> ![old](https://cloud.githubusercontent.com/assets/124687/20834157/a4329bd6-b861-11e6-853b-4445acd4d9ae.png)

This is how it currently looks on `develop`:

> ![new](https://cloud.githubusercontent.com/assets/124687/20834159/ac5aec1e-b861-11e6-85ad-8110af52c6e9.png)

**Comment by jseppi** [comment]
I think it looks a bit better in #1066
