### ISSUE TITLE
Refactor date widget

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1079]
Ran across this while working on #1078. The date widget renders like this currently::
<img width="387" alt="screen shot 2016-12-02 at 1 21 12 pm" src="https://cloud.githubusercontent.com/assets/509309/20849083/3bce86aa-b892-11e6-81d4-484e3c5dfd0a.png">

The mocks look like this:
<img width="483" alt="screen shot 2016-12-02 at 1 21 32 pm" src="https://cloud.githubusercontent.com/assets/509309/20849092/44a6538e-b892-11e6-8772-e3bc15db4624.png">

The biggest change that needs to happen is that there needs to be a label for both fieldsets, with sub-labels(?) for "start" and "end." I'm not sure of the best way to do this accessibly. :-/

**Comment by toolness** [comment]
Hmm, how is this different from the way we're currently doing things?  We're already using `<fieldset>`s for each of these, each of which has three `<input>`s with their own labels... Screen-readers that support fieldsets should do a splendid job here and I'm unclear how the new design changes this?

**Comment by hbillings** [comment]
In the mocks, "Contract or current option period start and end" applies to both fieldsets instead of each one individually rendering that text.  The "Start" and "End" labels in the mocks would probably be the legend of each individual fieldset? I just don't know how that would render for a screen reader, or what element to use for the new overarching title. Or maybe I'm just way overthinking this?

**Comment by toolness** [comment]
Ah, yeah, I was thinking that "start" and "end" would indeed be the `<legend>`s, but that we'd have a bit of `.sr-only` in their so it might read like e.g.:

```html
<fieldset>
  <legend>start <span class="sr-only">of contract or current option period</span></legend>
<fieldset>
```

Something like that? I dunno.

**Comment by hbillings** [comment]
ahaaaaa, nice! Do you think it makes sense to try to make the `fieldset` template tag able to handle this use case? (Currently `fieldset` sets the legend to `sr-only` and displays the label, but both of them use `{{ field.label }}` for their content.)
