### ISSUE TITLE
Step 2 isn't restored when user goes back to step 1

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1084]
I've been doing a lot of back-and-forth navigation in implementing this card stuff, and I've found that this works and data is saved as expected:

Step 1 (add data) -> Step 2 (add data) -> Step 3 -> Step 2 (still has data)

but if I go all the way back to Step 1 from Step 3...

Step 1 (add data) -> Step 2 (add data) -> Step 3 -> Step 2 (still has data) -> Step 1 (still has data) -> Step 2 (no longer has data!)

**Comment by jseppi** [comment]
Fixed in https://github.com/18F/calc/compare/develop...no-step-data-overwrite
But GitHub is having some difficulties right now and is not letting me create a PR.
