### ISSUE TITLE
a.button.button-primary:hover text color is too dark

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1088]
Hovered display:
<img width="207" alt="screen shot 2016-12-07 at 11 04 24 am" src="https://cloud.githubusercontent.com/assets/697848/20978057/17249cc0-bc6d-11e6-96bb-6b3fb59f1854.png">

For this markup:

```html
<a href="#" class="button button-primary">Upload new price list</a>
```

**Comment by hbillings** [comment]
This is really weird. It appears to *only* happen when `href="#"` and not on other `a class="button button-primary` tags. Hrm.

**Comment by jseppi** [comment]
It happens on the <kbd>Edit</kbd> button Step 4 also, which has this markup:

```html
<a href="/data-capture/step/4?show_edit_form=on" class="button button-primary" data-edit-btn="">Edit</a>
```

<img width="95" alt="screen shot 2016-12-08 at 1 12 09 pm" src="https://cloud.githubusercontent.com/assets/697848/21023878/01820cf0-bd48-11e6-821f-2274ff0d48ff.png">
