### ISSUE TITLE
CSP is blocking New Relic browser monitoring

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1092]
<img width="284" alt="screen shot 2016-12-08 at 11 55 31 am" src="https://cloud.githubusercontent.com/assets/697848/21021288/6d7891b4-bd3d-11e6-8782-d5233e793541.png">

Can see it live in your dev console at https://calc-dev.apps.cloud.gov/

**Comment by jseppi** [comment]
barf, looks like New Relic doesn't "support" CSP:

https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-new-relic-browser#csp

**Comment by jseppi** [comment]
Though it does look like we could copy/paste their script instead of having it injected (hopefully!!!):

https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/add-apps-new-relic-browser#copy-paste-app

**Comment by toolness** [comment]
Hmm, I don't think I have a new relic login currently. Will have to sign up and then get access to CALC so I can get the snippet, I think.

**Comment by jseppi** [comment]
The CALC New Relic account shows that you are an admin

**Comment by jseppi** [comment]
Closed by #1106
