### ISSUE TITLE
Data Explorer - Reset button is invisible

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1093]
Got some kind of a ghost button thing going on with the "Clear Search" button on the Data Explorer:

<img width="705" alt="screen shot 2016-12-08 at 1 08 12 pm" src="https://cloud.githubusercontent.com/assets/697848/21023760/89d255b6-bd47-11e6-9b5f-a964faca6096.png">

Here it is on current prod CALC:

<img width="756" alt="screen shot 2016-12-08 at 1 10 08 pm" src="https://cloud.githubusercontent.com/assets/697848/21023795/aa3f5d08-bd47-11e6-98f5-a282e1ccabc4.png">

The markup for it is a bit weird because it is an `<input>` and not ` <button>` o_O

```html
<input id="reset-button" class="reset button" type="reset" value="Clear search">
```

**Comment by hbillings** [comment]
psh, who needs a reset button anyway

note to me when I get to this: delete the `#reset-button` styles in `data_explorer.scss` and add classes `button button-outline` to the input.
