### ISSUE TITLE
Add Favicon 

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1096]
We don't really have a logo icon to use, but maybe we could just use the GSA or TTS favicon for the time being? Or even just a blue square using one of the blues from the CALC banner?

Or the donkey...

**Comment by toolness** [comment]
👍 THE DONKEY

**Comment by hbillings** [comment]
@ericronne I think you had a favicon idea for CALC?

**Comment by jseppi** [comment]
he won't do it

**Comment by ericronne** [comment]
(•̀ᴗ•́)و

**Comment by jseppi** [comment]
i made one but he said no

![favicon](https://user-images.githubusercontent.com/697848/39061591-d0aeac72-4492-11e8-88bc-69ca5dc85fb9.png)

**Comment by hbillings** [comment]
:cry: it's so beautiful :sob:

**Comment by ericronne** [comment]
![images](https://user-images.githubusercontent.com/9259185/39061690-c397b0ea-448a-11e8-80be-38d0b525247c.jpg)

**Comment by tbaxter-18f** [comment]
I rolled this into #135

**Comment by jseppi** [comment]
![](https://media.giphy.com/media/l0HlMr2G3EKFgpUY0/giphy.gif)
