### ISSUE TITLE
Return value in __init__ in EscalationRateField

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1101]
QuantifiedCode piped up randomly and found this:

<img width="670" alt="screen shot 2016-12-09 at 1 08 50 pm" src="https://cloud.githubusercontent.com/assets/697848/21061140/b6ed5a5e-be10-11e6-8d70-ae838ac12788.png">

Looks like an easy fix. Know why this is a problem @toolness ?

**Comment by jseppi** [comment]
It was identified as "critical" FYI

**Comment by toolness** [comment]
Uh, weird. What is up with QuantifiedCode? Is its behavior supposed to be random?

Dunno why it would be a fix considered "critical".

**Comment by jseppi** [comment]
I really have no idea what is up with QC. As far as I can tell we don't have it hooked up any more, so not sure why it sporadically emails me.
