### ISSUE TITLE
Responsive fixes

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1107]
Things that don't quite render properly on smaller screens include:
- [ ] Nav (doesn't stack properly -- maybe leave out the link to upload?)
- [ ] Cards (should be removed altogether to save margin space)

...to be continued...

**Comment by toolness** [comment]
Is this sort of a duplicate of #1644 at this point?

**Comment by hbillings** [comment]
Yeah, basically. The things I mentioned here will probably end up being addressed by that issue anyway!
