### ISSUE TITLE
Design temp global nav

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1116]
Here's one navigation approach @hbillings and i worked out together. Let's discuss. It assumes that we 

@jeremyzilar @toolness @jseppi 

# Proposed nav options

## Basic users

 - Explore data
 - About CALC
   * Help

![proposed nav - basic](https://cloud.githubusercontent.com/assets/9259185/21205086/ffd26116-c21f-11e6-8e4d-f90c5b0b2154.png)

![site map - basic](https://cloud.githubusercontent.com/assets/9259185/21230268/0b9cd60e-c2aa-11e6-82e2-db3e11161898.png)

---

## Uploaders

 - Explore data
 - Upload prices
   * Price lists(?)
   * Details(?)
 - Your activity
 - About CALC
   * Help

![proposed nav - uploaders](https://cloud.githubusercontent.com/assets/9259185/21205096/058aa7e4-c220-11e6-81d1-a4ad4f832623.png)

![site map - uploaders](https://cloud.githubusercontent.com/assets/9259185/21228422/552b1cd8-c2a3-11e6-88e6-92e785e4efda.png)

---

## Super users

 - Explore data
 - Upload prices
   * Bulk upload
   * Price lists(?)
   * Details(?)
 - Dashboard
 - About CALC
   * Help

![proposed nav - super](https://cloud.githubusercontent.com/assets/9259185/21205100/093e9f26-c220-11e6-8201-e9ba02ba470b.png)

![site map - super](https://cloud.githubusercontent.com/assets/9259185/21228435/5d9fb98c-c2a3-11e6-827a-bc5bad2cc4cd.png)

**Comment by ericronne** [comment]
Here's a collaboratively revised version, evolved via the wise counsel of @hbillings @jseppi @tram and @toolness. In this paradigm, everyone's navigation is essentially identical. All users see the Add price list and Dashboard tabs, for example, regardless of whether they have the right to access the content and tools of those pages or not.

The login function lives where it's needed: as a button on both the Add price list and Dashboard pages. There is no other login tool.

My theory is that those unauthorized to upload price lists will see that tab and realize that the database grows thanks to many users, which seems like a nice branding statement to me. Brief descriptive text on that page could be designed to serve that purpose.

All users will see content on the **dashboard** landing page:
 - Everyone: 
   * All price lists
 - Anyone who can upload:
   * Your uploads
   * All price lists

![proposed nav v2 - index](https://cloud.githubusercontent.com/assets/9259185/21246181/bdf88860-c2ec-11e6-8af2-99dfd82eeb5b.png)

![site map v2](https://cloud.githubusercontent.com/assets/9259185/21246227/01387536-c2ed-11e6-8a10-b2ae7c66d0a0.png)

### Let's discuss!

**Comment by ericronne** [comment]
Here's a tweak on the above version, hopefully good enough for this release of the site. The previous layout (above) inaccurately shows that everyone has access to view all price lists. This is **not** the case. Consequently, there's no content to show users when they visit the dashboard page without having logged in. So i propose that we remove that tab from the default set.

So …

Prior to login, users see:
 - **Explore data**
 - **Upload price list** (working title) This page will have copy touting the crowd-sourced nature of the tool. As i said above, "My theory is that those unauthorized to upload price lists will see that tab and realize that the database grows thanks to many users, which seems like a nice branding statement to me. Brief descriptive text on that page could be designed to serve that purpose." Additionally, they can request upload access. Perhaps this page will also serve to prompt some users to let their CO compatriots about this cool feature.
 - **About CALC**

Logged in users will also see the Dashboard tab.

### Rough site maps and nav structure v4

![site map v4 - unregistered](https://cloud.githubusercontent.com/assets/9259185/21333279/4cbfa1ee-c614-11e6-8d15-73dc4a74bfe3.png)

![site map v4 - uploaders](https://cloud.githubusercontent.com/assets/9259185/21333287/5cdbe470-c614-11e6-848f-1b35083ebda3.png)

![site map v4 - admins](https://cloud.githubusercontent.com/assets/9259185/21333297/6306ac40-c614-11e6-86e8-e068189d260c.png)

**Comment by jseppi** [comment]
Comments to be taken or left: I still am partial to having a user menu, potentially accessed via a dropdown or something by the user email address. I like that the menu can have actions specific to that user's role (Add Price List, Review Price Lists, View My Dashboard, etc). 

To me, it seems like we will be kinda shoe-horning things into the tab interface, and that problem will only grow as additional functionality is implemented.

I know we want "Add price list" to be front and center, but realistically, the only reason the vast majority of users will even be logging-in is to upload data, so they probably won't necessarily need a special front-and-center link to encourage them to do so.

As I recall, the reason we started down the tab path to begin with was because there was a lot of repeated header info in the Price List Upload flow (like each step had a header indicating that the user was currently adding price list data). The tab was a convenient way to mark that the user was in that flow. If that is still part of the root issue we're trying to solve with the tabs, then maybe we can explore alternatives, like adding some text up in the main site header (next to the CALC logo or something).

**Comment by hbillings** [comment]
To expand on @jseppi's train of thought:

It feels like we have two sorts of areas on the site: public data analysis tools and private utilities. Maybe it makes sense to adopt the tab-based approach for the tools (which will soon increase in number, it seems), and to adopt the dropdown approach James's is talking about for the utilities. 

To avoid the "empty tab syndrome" caused when you're on a page that doesn't fall under a section (like all of the utilities), we could create a different header for the utility pages. I'm thinking about how Amazon has a "Your Account" page that's a lot different from browsing pages, or how Twitter/Facebook's profile pages are different from their feeds. Maybe the header on these pages just has a "back to home" link or something.

That said, I think the tab approach works fine *for now*. We can always roll out revamped nav with the homepage tool redesign + new colors.

**Comment by ericronne** [comment]
New version, which splits out "utilities" into their own menu. Discuss!

![site map v5](https://cloud.githubusercontent.com/assets/9259185/21862891/c3b4f148-d800-11e6-9321-aa808eab132e.png)

**Comment by jseppi** [comment]
One nit - "Manage CALC data" doesn't sounds quite right to me, because Data Admins can also manage users. Maybe "CALC Admin" or "Manage CALC" would work a little better?

Actually, maybe even better (but will require more work on the admin site) would be to have separate entries: "Manage CALC Data" and "Manage CALC Users."

**Comment by ericronne** [comment]
Sounds good to me. Next i'll take a look at visual design for the upper-right menu.

![site map v6](https://cloud.githubusercontent.com/assets/9259185/22032654/f146e32e-dcaa-11e6-9ea0-3cd7adafaeee.png)

**Comment by ericronne** [comment]
Here's a prototype which gives flesh to the above structure. The current nav gets blown away when the user hyper-jets into the Utility Zone, and the look becomes more utility-arian ...

### [Invision prototype of utility nav](https://gsa.invisionapp.com/share/BYA3ZM0PT#/215221007_Logged-In)

![logged-in](https://cloud.githubusercontent.com/assets/9259185/22130279/a3696006-de70-11e6-88a8-782d25d3b738.png)
![menu-hover-01](https://cloud.githubusercontent.com/assets/9259185/22130280/a36d7d3a-de70-11e6-9cc3-d216a0c07c8b.png)
![page-01-alt](https://cloud.githubusercontent.com/assets/9259185/22130281/a371f46e-de70-11e6-9511-4fef63e55ce7.png)

**Comment by ericronne** [comment]
I've split this design task off from the IA ( #1121 ). Let's determine a solid, flexible IA before continuing with design.

**Comment by ericronne** [comment]
Also spit out the user-account menu design into its own issue, #1381

**Comment by ericronne** [comment]
Revised and narrowed to encompass only the current site + data capture …

![home - temp](https://cloud.githubusercontent.com/assets/9259185/23085543/f00a4e06-f52d-11e6-8c3c-fd582df92603.png)

**Comment by ericronne** [comment]
Swapped "about" and "admin" tabs, so functional sections are grouped. Looks like we're good to go with this, pending copy edits to intro (#1383)

![home - logged in - temp](https://cloud.githubusercontent.com/assets/9259185/23185381/df963b0c-f848-11e6-9b96-4385b47f77e5.png)
