### ISSUE TITLE
Determine whether a traditional navigation approach is appropriate

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1119]
We've had some backs and forths regarding whether to retain the current navigation structure or not. Let's figure it out for good.

### Traditional
Buttons like we are already implementing in the new design, linking to the various sections in the site...

![image](https://cloud.githubusercontent.com/assets/9259185/21230116/82ce8e58-c2a9-11e6-900b-870327890cb8.png)

### "Tool-esque"
Eliminate the site-wide nav and contextually integrate navigation throughout the site, sort of like CALC is already...

![image](https://cloud.githubusercontent.com/assets/9259185/21230736/8ced99cc-c2ab-11e6-8aa2-472ac944d683.png)

@hbillings @jeremyzilar @jseppi @toolness

**Comment by jseppi** [comment]
For the first option, which "tab" would be active for the Replace Price List Upload flow that I'm working on in #1089?

**Comment by ericronne** [comment]
I don't think i was aware of that feature.
We need to figure out the overall IA. I made an issue :D #1121

That factor should definitely be considered as we try to decide between traditional and toolesque, though.

I'm feeling like traditional may be the way to go. It gives us a lot of flexibility to expand, eg. But we'll chat on it.

**Comment by ericronne** [comment]
Closing in favor of #1116
