### ISSUE TITLE
Define temp IA: for official launch of data capture

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1121]
Some rough, high-level options are laid out in #1116 

@jseppi @jeremyzilar @hbillings @toolness

**Comment by jseppi** [comment]
Is this solved, @ericronne?

**Comment by ericronne** [comment]
Marking as blocked until we hold our design studio on @EricSchles's and @toolness's features.

**Comment by ericronne** [comment]
cc @hbillings

**Comment by ericronne** [comment]
Here are some envisioned expansion areas from the [CALC strategy pitch deck](https://docs.google.com/a/gsa.gov/presentation/d/1ad7k2FB8noKEWPHq1j2QxriNzco97EgrisL1eWIagiU/edit?usp=sharing). These may inform the IA discusion …

![image](https://cloud.githubusercontent.com/assets/9259185/22479118/33ab9388-e7b2-11e6-8f9d-1442f5e5417c.png)

**Comment by ericronne** [comment]
Here's the [**working IA google doc**](https://docs.google.com/a/gsa.gov/document/d/1b5JX6-awt5ERBaYvbAU1TsOlAod-anXDDU3_cU_NmY4/edit?usp=sharing) from our "card sorting" exercise, and a [**WIP IA**](https://github.com/18F/calc/wiki/%5BWIP%5D-Information-architecture) i've added to the wiki.

**Comment by ericronne** [comment]
And here's how it might play out in the nav / site map …

### Default
![default](https://cloud.githubusercontent.com/assets/9259185/22953193/cbb4e32c-f2d5-11e6-81bc-e63a487e7f62.png)

### Logged in
![logged in](https://cloud.githubusercontent.com/assets/9259185/22953210/d88a51d6-f2d5-11e6-83b4-4d90d202c020.png)

### Site map
![site map v7](https://cloud.githubusercontent.com/assets/9259185/22953225/e4bc9aae-f2d5-11e6-9c3b-2110f01c3b10.png)

**Comment by ericronne** [comment]
Unblocked this, since we have a potential home for the  @EricSchles and @toolness features: "Analyze and plan"

**Comment by ericronne** [comment]
Revised and narrowed to encompass only the current site + data capture …
![site map v8 - temp](https://cloud.githubusercontent.com/assets/9259185/23082902/ffb8a95e-f520-11e6-9b3a-4fa3b8e7359d.png)

**Comment by ericronne** [comment]
Officially promoting this to "good enough to try" status. Next: implementation.
