### ISSUE TITLE
Use auto scroll thingy on about page

### ISSUE THREAD

**Issue by toolness** [18F/calc#1123]
I just noticed that the auto-scrolly thing we use in data capture and the styleguide isn't used on the **About** page. There are some internal links on that page so it'd be nice if the browser smoothly scrolled to them.

Actually, there's also a _Return to the top_ link at the bottom of the data explorer, it might be worth enabling it on that page too (as long as it doesn't conflict w/ the existing data explorer code--which it might, since both the data explorer and the autoscroller use the history API).

**Comment by ericronne** [comment]
**Return to top** is now live, and and has an updated style on `develop`. 

**About** in-page nav pulled into its own issue: #1835

**Comment by hbillings** [comment]
Reopening because this issue was about implementing autoscrolling, not the return to top link.
