### ISSUE TITLE
Upload widget can overflow on long file names

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1130]
Here's an example from the R10 upload, but I bet it happens on all the other instances of the widget as well:

<img width="637" alt="screen shot 2016-12-16 at 11 26 39 am" src="https://cloud.githubusercontent.com/assets/697848/21272928/c7b38e3c-c386-11e6-90f8-a7d0e872e69f.png">

**Comment by toolness** [comment]
Ooo I wonder if we should use [`text-overflow: ellipsis`](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) here?!
