### ISSUE TITLE
In Admin tables, datetimes are not localized

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1132]
Looks like maybe they are UTC?

<img width="430" alt="screen shot 2016-12-16 at 11 25 38 am" src="https://cloud.githubusercontent.com/assets/697848/21272985/1c0f0d8a-c387-11e6-9d8e-2fab746a74a5.png">

@toolness: ideas on this one?

**Comment by jseppi** [comment]
@toolness: just noticed that in our `settings.py`, we have `TIME_ZONE = 'UTC'`. That's probably why it is all in UTC.

**Comment by toolness** [comment]
Er what should they be localized to, though?  EST?

**Comment by jseppi** [comment]
It would be cool if they were shown localized to the current user's location, but probably not necessary. Some kind of indication that they are UTC might be an acceptable fix.
