### ISSUE TITLE
Can't select text in main header

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1133]
Not sure if bug or not, but seems a bit weird: Basically I can't highlight/select text in the header on the main page. It looks like, when using the DOM explorer, that the `<nav>` element is on top of all the text:

<img width="1211" alt="screen shot 2016-12-16 at 11 53 42 am" src="https://cloud.githubusercontent.com/assets/697848/21273073/8db04e5e-c387-11e6-90b7-f100a48c6cbb.png">

the `.row` that actually contains the main heading and intro text looks like it has no height:

<img width="1152" alt="screen shot 2016-12-16 at 11 54 06 am" src="https://cloud.githubusercontent.com/assets/697848/21273079/93044bda-c387-11e6-8c24-1804ca347b6b.png">

@hbillings any ideas if this is bad or not or what is going on?

**Comment by hbillings** [comment]
I'm going to guess this is probably a `float` issue. Throwing the `clearfix` class on the row that has no height might fix it.
