### ISSUE TITLE
Improve the home-page "bullet" area

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1140]
## Home-page header (for context, and not yet using these colors btw)
![image](https://cloud.githubusercontent.com/assets/9259185/21325629/e1037b96-c5ec-11e6-9821-fe1d62cd3b52.png)

## Area in need of improvement
![image](https://cloud.githubusercontent.com/assets/9259185/21316999/d479e7e4-c5c8-11e6-824e-ed7b8bc75b5e.png)

## Needs header text

 - [x] Rewrite text
"With …" is a placeholder; any better ideas?
"CALC offers …" seems to communicate the basic idea, but doesn't fit with all four: "CALC offers fully burdened" eg.

![image](https://cloud.githubusercontent.com/assets/9259185/21317022/fd0e74cc-c5c8-11e6-826b-4f76103d0614.png)

"CALC data includes …" works if we add "rates" after "fully burdened." (thx @hbillings!)
*Shall we implement this?*
![image](https://cloud.githubusercontent.com/assets/9259185/21326878/2e9604e6-c5f2-11e6-8fcc-15391b7bb0b0.png)

"About CALC data" seems more fitting, but then it would be confused with the about section. We could link it to that page, but that feels weird to me.

## Visuals need adjustment

 - [x] Shrink the icons
 - [ ] Shrink the type
 - [x] Center stack the icons (#1127)
 - [x] Left align the text

We can pair on this if you like :)

thx!

**Comment by ericronne** [comment]
cc @jeremyzilar

**Comment by ericronne** [comment]
Color reference...
![image](https://cloud.githubusercontent.com/assets/9259185/21364647/577d7fd6-c6b7-11e6-95d9-0064b9794110.png)

Text: #c5d6de
4 icons: #839ea8
Divider: #436a79

**Comment by hbillings** [comment]
Changed the colors in #1145

**Comment by hbillings** [comment]
@ericronne How much should the type be shrunk? It's at 16px currently; our `$small-font-size` variable is 12px.

**Comment by hbillings** [comment]
Here's how it currently stands, though note the icons will be white after merging #1145.
<img width="353" alt="screen shot 2016-12-20 at 4 33 53 pm" src="https://cloud.githubusercontent.com/assets/509309/21373241/28cc749c-c6d2-11e6-920e-e46ec65ec967.png">
