### ISSUE TITLE
Style price list details data page

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1149]
The `data-capture/price-lists/<price list number>` pages could really use some style help. 
- The same inline editing styles we want to apply to step 4 should apply here.
- The warning about editing details causing an approved price list to become unapproved is too subtle, and it's only on the vendor details -- not the price list re-upload flow.
- Having the price list's status in an alert box is weird -- I suggested something in #980 
- The spacing between the vendor details and the price list upload is too tight.
- The placement of the "Invalid Rows" spin-out is odd, and that's not how I'd expect those details to be displayed.
- After re-uploading a new price list, there should be some sort of visual indicator at the price list that it's been re-uploaded.
![screencapture-0-0-0-0-8000-data-capture-price-lists-1-1482282436791](https://cloud.githubusercontent.com/assets/509309/21373858/d013a8d4-c6d6-11e6-9560-08b889a64097.png)

**Comment by ericronne** [comment]
Here's a design for the meat of this page …

![price list details](https://cloud.githubusercontent.com/assets/9259185/21945592/b2e8c5ae-d9a1-11e6-814f-ed3b5ae04bb8.png)

**Comment by ericronne** [comment]
Here are the label colors …
![image](https://cloud.githubusercontent.com/assets/9259185/23036919/279505da-f44a-11e6-9913-a5055309c2be.png)

### Pending Review
**BG** #FBEEBE
**Icon and text** #825C1E

### Rejected
**BG** #FAD0D0
**Icon and text** #BC1630

### Approved
**BG** #E6EDC2
**Icon and text** 61701C

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Style price list details pages](https://trello.com/c/QWtdHarC/235-style-price-list-details-pages)

**Comment by ericronne** [comment]
Implemented yet @hbillings? I forget!

**Comment by hbillings** [comment]
Not yet; this is a Django thing, IIRC -- oof
