### ISSUE TITLE
Implement new table error styles

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1151]
There are some new Sketch styles that haven't been implemented yet. Chief among these changes:
- losing the pink background (yay!)
- adding a red exclamantion point icon
- moving the error message to a tooltip on hover instead of inlining it
<img width="816" alt="screen shot 2017-01-11 at 9 03 13 am" src="https://cloud.githubusercontent.com/assets/509309/21857182/cf0dfc02-d7e1-11e6-88ee-cb840af510a6.png">

**Comment by ericronne** [comment]
My sketch layout...

![image](https://cloud.githubusercontent.com/assets/9259185/21857444/11125dc4-d7eb-11e6-81e7-c7d3f8b10eed.png)
