### ISSUE TITLE
Consider SVG for header icons

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1152]
Pulling this out from a comment I made: https://github.com/18F/calc/pull/1144#issuecomment-268618485

I think it would be beneficial to replace our header PNG icons (ceiling, donkey, etc) with SVG versions. They source SVGs shouldn't be too hard to track down on https://thenounproject.com/

This has multiple benefits:
- SVGs are easier to style (ie changing colors)
- SVGs can be inlined, so clients would make fewer server requests
- SVGs would likely be smaller in "file" size

**Comment by ericronne** [comment]
If we keep these icons in the redesign, would switch to svg for sure.

I made a new branch (bullet-sizing-etc) off ui-bug-fixes so i can mess with icon formatting and typography.

**Comment by ericronne** [comment]
Here's what i'm thinking for the hero area of the home page. The terms that had icons are put into sentence form, with glossary links for each.

![image](https://user-images.githubusercontent.com/9259185/38139103-9a89f890-33f3-11e8-9268-62e43249c6d0.png)

**Comment by jseppi** [comment]
Yeah, that's pretty good...

**Comment by hbillings** [comment]
I'm going to close this for now because it seems like we're moving away from icons. We can re-open if we decide not to go that route.
