### ISSUE TITLE
Change the schedule filter to be descending

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#1157]
For example, it would go 899 down to 132 then have consolidated at the bottom.

**Comment by jseppi** [comment]
This will also need to be changed in #1075

**Comment by jseppi** [comment]
@KellyBailey: like this?

<img width="242" alt="screen shot 2016-12-23 at 2 09 17 pm" src="https://cloud.githubusercontent.com/assets/697848/21461671/7352cab8-c919-11e6-9dd7-6a3c775c4d75.png">
