### ISSUE TITLE
Move Steps/StepRenderer into a separate file

### ISSUE THREAD

**Issue by toolness** [18F/calc#1173]
I didn't want to do this in #1161 because it'd totally screw up the diff, but I'd like to move the `Steps` and `StepRenderer` classes out of `data_capture\views\common.py` and into a separate file.  IMO they are important enough to warrant it, and when looking for them I frequently forget that they're in `common.py` (I use Sublime Text to find any files in my repo containing the text "step" and get confused when nothing relevant shows up).

I guess we could call it `data_capture\views\steps.py`, though then it'd have a file name clash with `frontend\steps.py` (which is being added in #1161).  I suppose we could just move `Steps`/`StepRenderer` into `frontend\steps.py`, since they are both front-end related and not *fundamentally* specific to data capture, even though that's currently the only place where they're being used... Hrm.

Thoughts?

**Comment by jseppi** [comment]
:+1: Moving to separate file sounds good to me. I think `frontend` is a good place, but up to you!
