### ISSUE TITLE
Cannot upload R10 Data when using prod URL

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1198]
Error from logs:

```
2017-01-04T14:48:08.59-0600 [APP/PROC/WEB/1]ERR [04/Jan/2017 20:48:08] WARNING [django.request:98] Forbidden (Referer checking failed - no Referer.): /data-capture/bulk/region-10/step/1
```

I believe this has something to do with the csrf check not working because of how we're using CloudFront.

It is likely the Price List Upload flow will fail similarly.

**Comment by jseppi** [comment]
@toolness: any ideas on this one?

**Comment by jseppi** [comment]
Ok, pretty sure this is caused by CloudFront not forwarding the Referer header. As documented at http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html, it does not forward it unless specifically configured to do so.

**Comment by toolness** [comment]
Ahh dangit!

I guess one good thing is that our styleguide actually has POST forms -- e.g. https://calc.gsa.gov/styleguide/radio-checkbox -- so we can write some automated tests that verify prod is working as expected by hitting those POST endpoints that aren't protected by auth.

**Comment by jseppi** [comment]
Yeah. Pretty sure it is specifically AJAX POSTs that will fail under this condition.

**Comment by toolness** [comment]
Oh, that radio checkbox form on the styleguide fails too, and I don't believe it's an ajax post...

**Comment by jseppi** [comment]
Ah, right you are!

**Comment by toolness** [comment]
This has been fixed on prod, right? And it was a CloudFront config issue rather than something fixable in our codebase?

**Comment by jseppi** [comment]
Yes. Sorry, forgot I had opened an issue for it.
