### ISSUE TITLE
manifest-prod.yml needs to specify production url

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1200]
Otherwise it will get dropped during a zero-downtime-deploy, as I just experienced.

**Comment by toolness** [comment]
What do you mean by "dropped"?

**Comment by jseppi** [comment]
It goes away :(
I had to manually remap it with `cf map-route calc-prod calc.gsa.gov`.

**Comment by jseppi** [comment]
I posted about how to accomplish this in #cloud-gov-support: https://gsa-tts.slack.com/archives/cloud-gov-support/p1483628486001887
