### ISSUE TITLE
Headers on tables are too big

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1202]
They run into each other, force the widths of the content cells to be too great in some cases (especially numerals) and are generally a pain. They're our default `16px` currently. @ericronne, what do you think?
<img width="785" alt="screen shot 2017-01-04 at 5 44 12 pm" src="https://cloud.githubusercontent.com/assets/509309/21664696/6e8e73a2-d2a5-11e6-9224-0e275508a0e6.png">

**Comment by hbillings** [comment]
@ericronne Here's what 14 looks like:
<img width="809" alt="screen shot 2017-01-06 at 1 24 12 pm" src="https://cloud.githubusercontent.com/assets/509309/21731799/74bbb00e-d413-11e6-9022-73e34b61917e.png">

Tell me more about the alignment?

**Comment by ericronne** [comment]
Some of the alignment funkiness is discussed in [this slack thread] (https://gsa-tts.slack.com/archives/calc/p1484258246000547).

The biggest problem i see is with minimum years of experience. In the layout above, eg, my brain merges two columns together. I see, "5 Hour."

Here's one way things could be arranged...
![x](https://cloud.githubusercontent.com/assets/9259185/21936948/d64b27f2-d97a-11e6-91ca-3cbff12366ba.png)

And there's @jseppi's space-saving thought (#1240), which we can chat on, too

**Comment by jseppi** [comment]
Will be closed by https://github.com/18F/calc/pull/1245

**Comment by jseppi** [comment]
all fixed, @hbillings?

**Comment by hbillings** [comment]
Done in #1285
