### ISSUE TITLE
Design an email template

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1208]

**Comment by ericronne** [comment]
Keep it simple.

eg...
http://leemunroe.github.io/responsive-html-email-template/email.html

**Comment by ericronne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Design simple html email template](https://trello.com/c/psZ8vFon/223-design-simple-html-email-template)

**Comment by ericronne** [comment]
Here's a draft, let's discuss! If we roll it out before we update the home-page design and site colors, we should adjust the colors to match the current palette.

## Desktop
![email-desktop-insitu](https://cloud.githubusercontent.com/assets/9259185/22599495/c7734d26-e9fc-11e6-91bf-e9799ab95bf7.png)

## Mobile
![email-mobile-insitu-resized](https://cloud.githubusercontent.com/assets/9259185/22599515/de453de8-e9fc-11e6-9a56-8051514acb31.png)

**Comment by hbillings** [comment]
I like this design overall for the email that a CO would get upon an admin taking action on one of their price lists. A couple of thoughts:
- There probably should be two separate email designs, one for admins and one for COs. Admins should get "digest" style

**Comment by ericronne** [comment]
@hbillings is there a content sample approximating what admins would get?

**Comment by jseppi** [comment]
@ericronne see https://github.com/18F/calc/tree/develop/data_capture/templates/data_capture/email

`approval_reminder.html`, `bulk_upload_failed.html`, and `bulk_upload_succeeded.html` are emails that go to admins.

You can generate sample emails:
1. make sure you have `docker-compose up` running in a terminal window
1. open `http://localhost:1080` in your web browser to view your local MailCatcher
1. in another terminal window run `docker-compose run app python manage.py send_example_emails`. Your MailCatcher should get populated with versions of all the emails that CALC sends.

**Comment by ericronne** [comment]
Looks like we actually aren't using "digest" emails — with links to individual price lists to be reviewed. @hbillings had the thought to let the user know how many PLs they have awaiting approval. Sound useful? If so, pretty straightforward to implement @jseppi?

**Comment by jseppi** [comment]
We are. The "digest" is the `approval_reminder.html`

**Comment by ericronne** [comment]
So the full list will appear in the email, in place of ` https://example.com/unreviewed_price_lists `?

**Comment by jseppi** [comment]
no, there is no list, just the link to the page with the unreviewed lists.

**Comment by ericronne** [comment]
Then what do you think about [this notion](https://github.com/18F/calc/issues/1208#issuecomment-278152690)?

**Comment by jseppi** [comment]
> let the user know how many PLs they have awaiting approval

We used to have that, but when we had the Writing Lab review, they struck it (ref https://github.com/18F/calc/pull/1274/files).

**Comment by ericronne** [comment]
Hm would be curious to hear their rationale.

**Comment by ericronne** [comment]
@jseppi i'm dumping the various emails into the template, to ensure that i've covered all of the formatting bases.

As i go, i'm playing with some alternate verbiage, because i'm a rabble rouser. If any of it seems useful, cool. If not, shrug.

Question re the bulk-upload-error email: Do we plan to include the entire traceback in the body of the email? Any way that could live on a web page? thx!

**Comment by jseppi** [comment]
Sounds good!

Yes, the traceback will just be going in the email.

**Comment by ericronne** [comment]
Are the tracebacks often long and scary looking?

**Comment by jseppi** [comment]
Probably

**Comment by jseppi** [comment]
Maybe a better solution is to email the traceback to calc@gsa.gov and leave it out of the email to the Data Administrator altogether.

**Comment by ericronne** [comment]
nom.

**Comment by ericronne** [comment]
Did some content mods over in #1349

**Comment by ericronne** [comment]
Here's a version which uses the styles (i.e. logo, colors) that are currently on the live site. If we implement these templates before the overall site refresh, this is the guide …

![email-old-colors--temp](https://cloud.githubusercontent.com/assets/9259185/22796182/004c37fe-eebf-11e6-9d01-20503b07ee7a.png)

### And [here's the sketch file](https://drive.google.com/open?id=0BwWYNZcEDfwaNEZaaGRrVllENlE).

**Comment by toolness** [comment]
This is basically done now, right? Especially since it's been implemented by #1407?

**Comment by ericronne** [comment]
Yep. Will do a new issue for color and style mods to implement once the new colors and such are blown out sitewide.
