### ISSUE TITLE
Redesign Price List Details page

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1216]
This is currently what a user sees when they examine a price list in their account. Ideally, whatever we do to this page would also be something we do to the site admin's detail view. Currently, they're ugly in different ways. [Edited to add the correct screenshot.]
![screencapture-0-0-0-0-8000-data-capture-price-lists-3-1483749414921](https://cloud.githubusercontent.com/assets/509309/21737536/fb615e42-d436-11e6-9b09-88e5c2e1efb7.png)

**Comment by ericronne** [comment]
Howdis?

![price list details](https://cloud.githubusercontent.com/assets/9259185/21966071/2c594d00-db32-11e6-9859-c91be1338372.png)

**Comment by hbillings** [comment]
GORGEOUS.

I'm really digging the valid/invalid rows toggle. I wanna user test that to make sure folks see the invalid one, but holy crow is that 🔥

**Comment by hbillings** [comment]
Oh, one little thing: I think we'll want to keep the "uploaded by," "submitted at," "status changed on," and "status changed by" fields somewhere where they aren't editable. Also, @jseppi can correct me on this, but I don't think we want to allow users to change the schedule once they've submitted a list (because there's no way for us to re-process the data with the new assumptions about the new schedule).

**Comment by jseppi** [comment]
@hbillings is correct: the Schedule cannot be changed.

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Style price list details pages](https://trello.com/c/QWtdHarC/235-style-price-list-details-pages)
