### ISSUE TITLE
process.env.NODE_ENV might not be set to "production" on builds to calc-dev

### ISSUE THREAD

**Issue by toolness** [18F/calc#1225]
I just noticed that our redux logging middleware (introduced in #1075) is turned on at https://calc-dev.app.cloud.gov/, which suggests that `process.env.NODE_ENV` isn't set to `"production"` when building the front-end bundle.  (Ideally any AST branches that test on it should also be dropped at build time, to make our production bundle smaller.)

**Comment by jseppi** [comment]
Hrm, the bundle is built during the CI build, so I guess we just need to add `NODE_ENV=production` in `.travis.yml.`

**Comment by jseppi** [comment]
Renamed to be a little more clear. We actually have a separate staging env now (`calc-staging`) and this issue seemed to be specifically about the dev instance (`calc-dev`).

However -- this brings up another issue. Right now both staging and production releases are done from locally built and pushed code, instead of from CI. It would be better to have those happen in CI as well.

**Comment by jseppi** [comment]
Update: #1113 is now closed, so we should have fully automated deploys from CI to `staging` and `prod` now 🎉 

Still need to figure out how to prod build for those release. Maybe another gulp task called `build:prod` or something like that that just brutes the `process.env.NODE_ENV` to `"production"` and does the normal build task.  We could run that task in `deploy-travis.sh`...I dunno, just spitballing...

**Comment by jseppi** [comment]
heh, there's no reason for the separate gulp task actually, `NODE_ENV` just needs to be set before running `gulp build`

**Comment by jseppi** [comment]
eeep, @toolness, I think the `if` statement around requiring the middleware logging will never actually work, because `process.env.NODE_ENV` is undefined in the browser: https://github.com/18F/calc/blob/develop/frontend/source/js/data-explorer/explorer.js#L30

**Comment by toolness** [comment]
Oh, we just need to make it defined then :)  I forget how to do that with browserify...  It's a standard practice tho, it's how React defines dev-specific stuff in their bundles too.  I know how to bust it up in webpack but browserify always confuses me. 😣 

Oh it looks like it's actually an UglifyJS option, not a browserify option. Here's an example:

https://github.com/processing/p5.js/pull/1318/files#diff-35b4a816e0441e6a375cd925af50752cR257

I will bust up a PR soon!

**Comment by toolness** [comment]
I hate computers.

**Comment by jseppi** [comment]
How about this https://github.com/hughsk/envify ?

**Comment by toolness** [comment]
yeah i am busting that up now, i just hate computers.
