### ISSUE TITLE
Some constants in data-explorer's constants.js are duplicated from Python code

### ISSUE THREAD

**Issue by toolness** [18F/calc#1226]
As of #1075, there are a number of constants in `frontend/source/js/data-explorer/constants.js` that are duplicated from Python, e.g.:

* The education constants `AA`/`BA`/`MA`/etc and their corresponding human-friendly labels.
* The worksite codes and labels
* The business size codes (`s` and `o`) and associated labels
* etc.

It might be nice to not have these in two separate places, or at least have tests in place that verify that both places keep them in-sync.

**Comment by hbillings** [comment]
@toolness Is this a transition sprint task? (I admit I'm not entirely sure how consolidating them would work, but this seems like the sort of stuff we're trying to target.)

**Comment by toolness** [comment]
Yeah, I can't really think of any way to keep things DRY without inadvertently introducing some new fancypants mechanism that will be harder to figure out to use than it's worth, so I think we should just document things as well as possible (e.g. above the education constants on the python side, mention "yo if you change these, be sure to also change them on the JS side" and vice versa).
