### ISSUE TITLE
Proposed price highlight no longer fades in/out

### ISSUE THREAD

**Issue by toolness** [18F/calc#1228]
By "proposed price highlight" I mean this, defined in `highlights.jsx`:

> <img width="232" alt="screen shot 2017-01-11 at 8 09 50 am" src="https://cloud.githubusercontent.com/assets/124687/21849750/5d2e35ae-d7d5-11e6-8742-aa13fe77ae9d.png">

Before #1075, it faded in/out as a proposed price was set/unset, but now it no longer fades, it just pops in and out of existence.

**Comment by jseppi** [comment]
this seems like it hasn't been an issue for anyone. close it?
