### ISSUE TITLE
"Contract year" radios on data explorer look a bit wonky

### ISSUE THREAD

**Issue by toolness** [18F/calc#1229]
I'm not sure if this is a regression caused by #1075 or something else, but I noticed that the **Contract year** radios on the data explorer have a bit of top-margin on them that looks wonky:

<img width="190" alt="screen shot 2017-01-11 at 8 14 24 am" src="https://cloud.githubusercontent.com/assets/124687/21849889/1152897c-d7d6-11e6-8a46-aa89e010be3b.png">

There also seems to be a lot of space between the label and the radios... HMMM.

**Comment by jseppi** [comment]
I think it is related to this change: https://github.com/18F/calc/commit/e9b7a43ba5b8dc481307948d05e0d3f9bbb1fbac#diff-6866aff988ee76b013ea3995ec1fb8a7R7

I undid that change locally and the buttons looked correct (though everything else looked whacky).
