### ISSUE TITLE
Development packages (eg, redux-logger) should not be included in production bundles

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1244]
As mentioned in https://github.com/18F/calc/pull/1243, even though the `redux-logger` doesn't actually get `require`'d in `explorer.js` when `NODE_ENV=='production'`, I am pretty sure its code is still included in the bundle. This is not ideal because it adds extra dead code to the bundle.

**Comment by jseppi** [comment]
I guess we could do something like

```js
  if (process.env.NODE_ENV) {
    bundler = bundler.exclude('redux-logger');
    bundler = bundler.exclude('redux-logger/lib');
  }
```

in `gulpfile.js` but blech, that stinks to have to manually `.exclude` stuff like that.

**Comment by jseppi** [comment]
I thought https://github.com/nolanlawson/rollupify might work for us, but it says it doesn't work on things that are `require`'d >.<

**Comment by jseppi** [comment]
Ok, after some research, I don't think it is possible to not include `redux-logger` in our production bundle other than the `bundler.exclude` method mentioned previously.

There's no way to conditionally include ES6 module `import`s, so we have to use to `require` for `redux-logger`. Fortunately the size different is only 10kb in the non-gzipped version, and less than that in what we actually serve, so I guess we can not worry about it for now.

**Comment by toolness** [comment]
Hmm it is definitely doable, I've done it before in other projects--it all depends on envify actually converting every occurrence of `process.env.NODE_ENV` into the string literal `"production"`, so that conditionals in the transformed code become constants that evaluate to false, which uglify then removes via its dead code removal mechanism.  I thought uglify does dead code removal by default, but maybe we have to enable it?

Oh wait... um... but we're browserifying the code before uglifying it so I guess maybe it makes sense that browserify would include the uglify bundle.... OMG THIS IS SO MUCH EASIER WITH WEBPACK

**Comment by toolness** [comment]
Can we just switch to webpack.

**Comment by toolness** [comment]
Nevermind, it looks like we just have to use uglify*ify* on our code!  Whee!

**Comment by jseppi** [comment]
Yeah, I saw that uglifyify package. Seemed weird. I agree webpack would be cooler. How much of an effort would it be to convert the non-data-explorer js bundles and all the sass bundles?

**Comment by toolness** [comment]
Hmm good question--would we *have* to convert the sass bundles?  We don't currently use browserify for SASS, do we?  I thought webpack did weird things with SASS/CSS, by including it as JS that is then dynamically injected or some junk, which would break our progressive enhancement strategy, but I could be wrong.

I think if we focused on *just* the JS, the only weird part would be the vendor bundles that just consist of those concatenated files.  But we use `gulp-concat` for that... so I think that using webpack as *just* a replacement for what we're currently using browserify for wouldn't be hard--it's using webpack as a replacement for also gulp-concat and sass that I don't really know anything about...

**Comment by jseppi** [comment]
Right, we aren't using browserify for sass, but we are using gulp. I also find the way webpack deals with css a bit confusing. I think it inlines it into the JS bundle, and then you can use that `extract-text-plugin` to un-inline it.

So you're saying we add webpack just to replace all the browserify build steps, but keep gulp for everything else? I think in that case I agree it wouldn't be too bad to setup webpack itself, but running two JS build tools might be a little funky. docker-compose would probably help with that though.

**Comment by toolness** [comment]
Ohhh shoot, yeah, I forgot that webpack is kind of a replacement for gulp too.  D'oh!

Hmm I think we should noodle on this a bit and not make any decisions just yet. 😁

**Comment by jseppi** [comment]
stupid front end
