### ISSUE TITLE
Visually tweak Step 3 Errors design implementation

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1266]
via live bug squash!

**Comment by jseppi** [comment]
I....can't tell what this issue is about. Can you elucidate, @ericronne?

**Comment by ericronne** [comment]
@hbillings and i are going to pair (today?) to adjust/improve/massage the layout

**Comment by ericronne** [comment]
Going async on this, since schedules are a 🐻  ...

### Here's my thought, in visual form. Let's discuss (ideally IRL)! …

![upload-03b-errors-v2_720](https://cloud.githubusercontent.com/assets/9259185/22353296/6e7c3600-e3e5-11e6-8c83-90e370ad1610.png)

**Comment by hbillings** [comment]
I think this is done, right @ericronne?

**Comment by hbillings** [comment]
@ericronne i can haz triangle svg? 🙏

**Comment by ericronne** [comment]
[s'pose.](https://drive.google.com/open?id=0BwWYNZcEDfwaaEJ4SnhPUmlBc1U)

**Comment by jseppi** [comment]
What are you using that triangle svg for, @hbillings?

**Comment by hbillings** [comment]
@jseppi So I can't actually see the thing @ericronne linked to, but I'm trying to get the little warning triangle he's got in his mocks next to "We found errors in three rows of your data."

**Comment by jseppi** [comment]
haha cool cool, just wanted to make sure we weren't both working on #1413 because the triangle is used there also :)

**Comment by hbillings** [comment]
Oh! Yeah, different triangles, lol. ^_^

**Comment by ericronne** [comment]
# Let's try this [again](https://drive.google.com/open?id=0BwWYNZcEDfwaeUdsSm04cEdCSE0).

**Comment by ericronne** [comment]
# Here's a [cleaned-up version](https://drive.google.com/open?id=0BwWYNZcEDfwaV1ppRjYwaXdfbFk). Thx, @jseppi!
