### ISSUE TITLE
Modify footer design to accommodate the recent updates link more compactly

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1272]
@jseppi added a useful "Read about recent updates to CALC" link to the footer. I'll adjust the design to attempt a more compact, shorter layout.

Layout from #1271 …
![image](https://cloud.githubusercontent.com/assets/9259185/22302177/419ae3fe-e2f3-11e6-9823-c343e8d677d1.png)

cc @hbillings

**Comment by jseppi** [comment]
We could also potentially add the icons credits to the About page, maybe in a "Credits" section. And actually, after reading up on how we should be giving attribution, we should be linking the actual icon names to their associated Noun Project pages, per https://thenounproject.zendesk.com/hc/en-us/articles/200509928-How-do-I-give-creators-credit-in-my-work-

**Comment by ericronne** [comment]
Ah, then we should indeed move the credits to the About page, or the attribution will get too long. Win win.

**Comment by ericronne** [comment]
Any objections to deleting the contact email address and simply linking "email us"? That'd help, too.

**Comment by ericronne** [comment]
@tram ^^

**Comment by tram** [comment]
It would be nice to have the email address visible. If it's just in an email link, folks either have to…
1. know to roll over it to get an email address (if they are computer-savvy enough to know that's a thing they can do) and be motivated to do it when they see the link, or
2. use the browsers mailto: functionality which isn't always wired up right and/or trusted.

That said, it's not _that_ big a deal, but I'd rather cut some prose than the email address.

Also, are we using noreply-dev@calc or calc@gsa? No sweat either way. Just curious.

**Comment by jseppi** [comment]
The address is filled in based on a setting. In prod, the setting value is "calc@gsa.gov". That screenshot was from my local dev, so it was a weird value.

**Comment by jseppi** [comment]
This one closed @ericronne?

**Comment by ericronne** [comment]
Yes! With #1333. Thx!
