### ISSUE TITLE
The /updates/ view should auto-hyperlink to issues / PRs

### ISSUE THREAD

**Issue by toolness** [18F/calc#1296]
Some of the CALC 1.0-era release notes refer to specific issue numbers using standard GitHub notation (e.g. `#123`). It would also be nice to refer to them for our newer release notes, especially if a feature's PR has nice screenshots/animated GIFs or has lots of discussion justifying a decision.

It'd be kind of a pain to do this manually in the Markdown itself, though.

The Python library we're using to render markdown at `/updates/`, though, does support adding plugins, and I bet it wouldn't be that hard to add one that converts issue numbers to hyperlinks.

**Comment by jseppi** [comment]
When GitHub does this autolinking, it has the benefit of knowing which numbers are for issues/PRs that actually exist, and whether the number is for an issue or a PR. I suppose we could just make sure we always only use numbers for actually existing issues. 

Or, we could ping (maybe just `HEAD`) the expected URLs before converting a number to a link, but this could be gnarly/expensive.

**Comment by jseppi** [comment]
Oh! GitHub is smart enough to resolve to either `/issues/<id>` or `/pull/<id>` regardless of what the type of `<id>` is.
