### ISSUE TITLE
Document/support how to use the python debugger w/ docker

### ISSUE THREAD

**Issue by toolness** [18F/calc#1300]
@hbillings had to set this up last week and it looked confusing. We should document this and add any required packages to `requirements-dev.txt` so it's not hard for folks in the future!

@hbillings what did you have to do? Seppi said it had something to do with `--service-ports`...

**Comment by hbillings** [comment]
I'd be happy to file a PR if that's helpful! 

I added `ipdb` to my local `requirements-dev.txt`, installed it, and then did `import ipdb; ipdb.set_trace()` where I wanted to get the debugging output. Then I ran `docker-compose run —service-ports app`, which made the magic ephemeral docker ports available to `ipdb` and dumped me into the interactive debugging session I was looking for.

**Comment by toolness** [comment]
Ah cool!! Yeah a PR would be rad!
