### ISSUE TITLE
Consider migrating our developer documentation to Sphinx

### ISSUE THREAD

**Issue by toolness** [18F/calc#1301]
Our developer docs are getting kinda big.  Aside from our already-big `README.md`, we've got a variety of other markdown files in our root directory, some of which (I'm looking at you, `updating_data.md`) might not be fully up-to-date.

It might be worth it to actually consider migrating our docs to use Sphinx, which is the military-grade solution that [cg-django-uaa](http://cg-django-uaa.readthedocs.io/en/latest/) uses.  Aside from producing really pretty docs, it makes it a lot easier to create docs that consist of multiple different pages with nice tables of contents linking them together, and a built-in search UI. It also supports markdown, so we wouldn't need to convert all our stuff to reStRuCtuReDTeXt or whatever.

Anyhow, just a thought.

**Comment by jseppi** [comment]
heh, yeah, not a bad idea
