### ISSUE TITLE
Seem to be missing CORS header on calc.gsa.gov

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1307]
It seems that API responses (through api.data.gov), when made from the production url (`calc.gsa.gov`) are missing the `Access-Control-Allow-Origin` header, and thus being blocked by the browser.

I have no idea when or why this happened, but I noticed it tonight while deploying `v2.1.0` to production. It persisted after the deployment as well. It hopefully just happened as a result of the deployment but I'm not completely sure.

This behavior is not exhibited when visiting the "direct" address, ie https://calc-prod.app.cloud.gov (or on equivalent staging or dev instances), which leads me to believe that maybe the header is getting stripped by CloudFront, but of course, I can't tell. And I'm fairly certain this wasn't happening until recently (ie, during the deployment, otherwise I think _someone_ would have emailed us or otherwise let us know).

As a temporary fix, I've added the header in our API Umbrella configuration at api.data.gov:
<img width="508" alt="screen shot 2017-02-01 at 12 04 58 am" src="https://cloud.githubusercontent.com/assets/697848/22496750/26eb4f16-e812-11e6-99a4-8e790a12fae8.png">

cc @toolness

**Comment by jseppi** [comment]
Hrm, new theory: CloudFront isn't stripping the `Access-Control-Allow-Origin` header, it isn't being added by the `django-cors-headers` middleware due to `HTTP_ORIGIN` not matching (see logic at https://github.com/ottoyiu/django-cors-headers/blob/862c68d1eb65455cf0051c4f124a4eb4341b68f2/corsheaders/middleware.py#L99)

**Comment by jseppi** [comment]
I'm not even clear why we are using `django-cors-headers`. I think we could just add `Access-Control-Allow-Origin: *` to every response via an extremely simple custom middleware and get rid of that dependency all together.

**Comment by jseppi** [comment]
Maybe there are security concerns with adding it everywhere -- so perhaps it should just be added to API responses.

**Comment by jseppi** [comment]
Newer theory: 
* AJAX'd calls to get rates data do not have a `Cache-Control` header at all
* non-AJAX'd calls to the rates URLS do not have the `Access-Control-Allow-Origin: *` header.

So, new theory is that someone (perhaps even our New Relic monitor) visited the api endpoint directly, so it had no `ACAO` header. That response then got cached by CloudFront, and then subsequent AJAX'd requests to it were thus missing the `ACAO` header, leading to the CORS error in the browser.

**Comment by jseppi** [comment]
^ that theory also kinda explains why it happened late at night. Nobody had visited the front page in a while, so CloudFront's cache went stale, and then New Relic pinged the API, which put the non-`ACAO` response into the CloudFront cache.

**Comment by toolness** [comment]
Ahhh good thinkin'!  Noice.

So uh, should we just add a `Cache-Control` header then?

Also, is CloudFront configured to pass along the `Origin:` header as mentioned in [Configuring CloudFront to Respect Cross-Origin Resource Sharing (CORS) Settings](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-cors)?

**Comment by jseppi** [comment]
Yeah, I think adding the `Cache-Control` header will very likely fix the problem.

I don't know for sure if CF is passing `Origin:` but I think it probably is since the site was working other than late last night. I don't have a self-service way to check :\

**Comment by toolness** [comment]
I am so befuddled.

Does API Umbrella talk to calc.gsa.gov or calc-prod.app.cloud.gov?

**Comment by jseppi** [comment]
Oh, very good question. It talks to `calc.gsa.gov`. I wonder if we should switch it to `calc-prod`...

**Comment by jseppi** [comment]
I can try that this evening

**Comment by toolness** [comment]
yeah that might be good--calc-prod doesn't have cloudfront in front of it, right?

**Comment by jseppi** [comment]
Correct

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure out CORS error on production](https://trello.com/c/QtCyWcSa/228-figure-out-cors-error-on-production)

**Comment by jseppi** [comment]
Ok, I modified our api.data.gov settings to proxy to `calc-prod.app.cloud.gov` instead of through `calc.gsa.gov` and removed the `ACAO` header that I added last night to mitigate the problem. Everything seems to be working 🎉 

Here's a sampling of the headers coming back from the ajax request to `/api/rates`:
<img width="208" alt="screen shot 2017-02-01 at 11 04 13 pm" src="https://cloud.githubusercontent.com/assets/697848/22537808/39af6c88-e8d3-11e6-8faa-8f6683fbb7fe.png">

Both `Access-Control-Allow-Origin` and `Cache-Control` are properly set!
