### ISSUE TITLE
Factor out changelog utils into a separate python package

### ISSUE THREAD

**Issue by toolness** [18F/calc#1314]
Hmm, so after I made cg-django-uaa, I thought it'd be useful to have the same changelog utils we have in CALC present over there, so that we had a well-documented release process + changelog for it too.

Which made me think that maybe we should factor out the ol' changelog utils into a separate python package. I dunno.

**Comment by toolness** [comment]
Could just be a bunch of doggone yak-shaving.

**Comment by hbillings** [comment]
Does the yak still need shaving tho

**Comment by toolness** [comment]
Ehhh, IMO this is really up to other projects factor out of CALC, rather than for CALC to factor out of itself, IMO.  So I guess I will just close the bugger.
