### ISSUE TITLE
Change title of data explorer page to be name of search

### ISSUE THREAD

**Issue by toolness** [18F/calc#1315]
@tram just had a great suggestion: since it's likely that COs have multiple CALC tabs open to different searches, what if we change the title of the page (i.e., the tab in their browser) from **CALC / Home** to **[labor category name] - CALC search**?  That way the CO would then have a bunch of differentiated tabs rather than identical ones.

(Just tried out Google and this is what they do. Noice.)

**Comment by tram** [comment]
Sweet! I like the Google Search approach you mentioned Atul of "[search query] - Google Search", so maybe something like "[search query] - CALC results"? @jeremyzilar, whadya think?

**Comment by jseppi** [comment]
Referencing back to #1372 since, depending on the clarification for how to "fix" that issue, we might not want to show the query in the title of the page either.

**Comment by toolness** [comment]
I dunno, dude. Unless the security folks really think that [Google has the same problem](https://www.google.com/search?q=blargy+blarg+blarg+pompzomdpmpzomv), it seems like an ok thing to do.

**Comment by jseppi** [comment]
The fix to #1372 was to simply add some max length validation, so I think it's safe to implement the suggestion here.

**Comment by jseppi** [comment]
I used this in a previous project: https://github.com/nfl/react-helmet
