### ISSUE TITLE
Tooltip can be "overrun" by text in Step 3 Errors table

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1317]
<img width="196" alt="screen shot 2017-02-03 at 12 36 22 pm" src="https://cloud.githubusercontent.com/assets/697848/22603546/7906410a-ea0d-11e6-8aa6-310bba007c64.png">

**Comment by hbillings** [comment]
I think this might no longer be an issue with the new table styling. (I can't reproduce it, at least.) Could you confirm?

**Comment by jseppi** [comment]
huh, got some even weirder behavior when trying to reproduce:

Looks good:
<img width="815" alt="screen shot 2017-02-22 at 10 30 58 am" src="https://cloud.githubusercontent.com/assets/697848/23221215/17427916-f8ea-11e6-8a22-3b456b4ad16a.png">

But then when I hover the error, the icon "jumps" under the text:
<img width="175" alt="screen shot 2017-02-22 at 10 31 03 am" src="https://cloud.githubusercontent.com/assets/697848/23221237/2769024c-f8ea-11e6-9184-9531ba80a112.png">

And then when I un-hover, it is still in its bad place:
<img width="137" alt="screen shot 2017-02-22 at 10 31 08 am" src="https://cloud.githubusercontent.com/assets/697848/23221280/4a340d80-f8ea-11e6-8d60-c1cf95489db8.png">

**Comment by jseppi** [comment]
tables are the worst

**Comment by hbillings** [comment]
where is the stabby murder emoji

**Comment by jseppi** [comment]
here's my test spreadsheet if that's helpful:
[Demo Example.xlsx](https://github.com/18F/calc/files/794204/Demo.Example.xlsx)

**Comment by hbillings** [comment]
@ericronne, would something like this be okay, or do you think this looks janky? Getting the icon to inline at the beginning of the line is easy; getting it to inline at the end of the line with the underline isn't. The best way I've found to fix it at the end makes it often break off onto its own line, which doesn't look good either >_< 
<img width="812" alt="screen shot 2017-02-22 at 4 12 19 pm" src="https://cloud.githubusercontent.com/assets/509309/23237244/bcf75e1a-f919-11e6-81e4-21b7960c6908.png">

**Comment by hbillings** [comment]
This is also a possibility:
<img width="589" alt="screen shot 2017-02-22 at 4 15 15 pm" src="https://cloud.githubusercontent.com/assets/509309/23237351/2214aa78-f91a-11e6-9044-d52bb2845f58.png">

**Comment by hbillings** [comment]
What the tooltip would look like:
<img width="179" alt="screen shot 2017-02-22 at 4 18 37 pm" src="https://cloud.githubusercontent.com/assets/509309/23237426/99fb6f54-f91a-11e6-8759-4343569e31b8.png">

**Comment by ericronne** [comment]
Per our slack chat, let's kill the icon for now (since the dotted underline and red color should be sufficient indicators to the user), but keep it when required fields are blank.

**Comment by jseppi** [comment]
Fixed in #1415
