### ISSUE TITLE
Admin - .paginator contents formatting is janky 

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1326]
On list views that have a lot of entries (for example, the Users list on prod), the `.paginator` at the bottom of the list view has some bad contrast and spacing going on:

<img width="517" alt="screen shot 2017-02-06 at 4 20 22 pm" src="https://cloud.githubusercontent.com/assets/697848/22668940/30843612-ec88-11e6-9729-92cb9b9f0191.png">

Here's the markup from that screenshot:
```html
<p class="paginator">
    <span class="this-page">1</span> 
    <a href="?p=1" class="end">2</a> 
165 users
&nbsp;&nbsp;<a href="?all=" class="showall">Show all</a>
</p>
```

**Comment by hbillings** [comment]
Ew, gross. Is this on prod?

**Comment by jseppi** [comment]
yeah
