### ISSUE TITLE
Figure out how to run production_tests in an automated way

### ISSUE THREAD

**Issue by toolness** [18F/calc#1331]
Now that we have production tests (via #1323), we should run them in an automated way, somehow.

Possibilities:

1. Set up an `rq_scheduler` job that runs them on a regular interval. We'd want to make sure that on calc.gsa.gov, the tests would actually be run against the cloudfronted version of the app, i.e. not via some kind of local loopback or internal LAN connection.

2. As @jseppi mentioned in https://github.com/18F/calc/pull/1323#pullrequestreview-20580340, we could have the travis deploy script run it after deploys to production/staging/etc.

**Comment by jseppi** [comment]
Maybe option 3 is to run via Travis cron?

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Travis cron job for running production test suite](https://trello.com/c/ZGBHbNeT/238-setup-travis-cron-job-for-running-production-test-suite)
