### ISSUE TITLE
Query string isn't always correctly built

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1334]
This bug came up in a user interview. The user relies on the chart's average for price analysis, and a couple of weeks ago noticed that the chart was no longer responding properly to queries.

It looks like Search and Go don't build the proper query strings.

To reproduce the Go button issue:
- Type in Systems Administrator. Don't hit search or enter.
- Click in Proposed Price box. Enter a price (test was $53.13)
- Click Go next to proposed price field
- Chart will say $53.13 proposed, $111 average. Note that in this case, the only argument in the query string is `proposed-price`. There is no labor category in the string. 

To reproduce the Search button issue:
- Enter a labor category. Don't hit enter.
- Click Search.
- Chart will return all results. Note that no query string is formed.

**Comment by tram** [comment]
I just asked the participant to try hitting Enter after typing a labor category and that didn't work for her, either. She's running IE 11 on Windows 7.

**Comment by jseppi** [comment]
So for the "Go button" issue, is the expected behavior that even though nothing was searched for, the labor category should have been updated when the Proposed Price Go is clicked?

**Comment by jseppi** [comment]
Clicking "Search" is definitely broken :\

Hitting <kbd>enter</kbd> works for me on Chrome, so I'm guessing that is somehow an IE11-related bug.

**Comment by tram** [comment]
It works for me on Chrome, too.

**Comment by toolness** [comment]
> I just asked the participant to try hitting Enter after typing a labor category and that didn't work for her, either. She's running IE 11 on Windows 7.

Hmm, I'm unable to reproduce this specific case in IE 11 on Windows 10.  I was able to reproduce the other cases from this issue's original description, though, and I think I fixed those in #1340.
