### ISSUE TITLE
Visual bug: headers appear to jump as page loads (in chrome, eg)

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1341]
For the backlog …

![jumpyjump](https://cloud.githubusercontent.com/assets/9259185/22715160/5a624960-ed55-11e6-878d-e1296d0422bd.gif)

Discussed in brief [on slack](https://gsa-tts.slack.com/archives/calc/p1486496535000314).

**Comment by jseppi** [comment]
Interestingly, I am not able to duplicate this issue on a slow connection (eg, from in-flight wifi).
