### ISSUE TITLE
Pin all node dependencies

### ISSUE THREAD

**Issue by toolness** [18F/calc#1345]
Given #1343 and other problems like it that I've run into in the past, I recommend pinning our node dependencies in our `package.json`.  This will improve dev/prod parity, as well as making the development environment more consistent across our own laptops.

I suspect there is a node-based solution similar to the python-focused `requirements.in` recommended by #514.  If we do something like this, we can make regular PRs that just update the minor/patch version numbers of our node dependencies. I think this will make it a lot easier to track down regressions that are due to package upgrades.

Since node's dependency space is hierarchical rather than flat, it might even behoove us to use `npm shrinkwrap` and commit its results to the repository, but I'm not sure. It looks like this [Keeping Your npm Dependencies Immutable](https://ponyfoo.com/articles/immutable-npm-dependencies) blog post outlines some best practices (well, practices that the author thinks are best, at least).

What do you think @jseppi?

**Comment by jseppi** [comment]
Yeah, I'm 👍 for pinning, and would be ok with using `shrinkwrap`.
