### ISSUE TITLE
Asset downtime during production deploys

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1347]
During production deployments, we had experienced long periods of asset files (CSS and JS) getting 404'd, as described in https://github.com/18F/calc/issues/1257. We thought that https://github.com/18F/calc/pull/1260 would solve it, but during yesterday's production deployment I still had brief window of ~getting served a stale version of our `index.html`, which was referencing now non-existent static assets (see screenshot)~ getting a 404 error on a static asset (see screenshot). The window of missing assets seemed shorter than in previous cases, but that's non-scientific/anecdotal.

<img width="1270" alt="screen shot 2017-02-07 at 4 40 31 pm" src="https://cloud.githubusercontent.com/assets/697848/22743669/7bc06278-ede0-11e6-984f-896202b1370c.png">

**Comment by jseppi** [comment]
Oh wow, just noticed. The file `main.min.1c97b5454e84.css` that is 404ing in that screenshot is actually the _new_ version of `main.min`, not the old one. So it doesn't seem to be that an old `index.html` (which would be referencing an old `main.min`) is the problem, but rather that the new `main.min` is for some reason unavailable!

I am very confused...

**Comment by toolness** [comment]
Hmm, how many webserver processes (uh, "web dynos" in Heroku parlance) do we have running?  Could it be possible that we have some that are serving the new `index.html`, while the request for `main.min.1c97b5454e84.css` is hitting an *old* server process that doesn't have the file?

**Comment by toolness** [comment]
If that is the problem, it could potentially be solved by moving the static assets into an S3 bucket, so that there's a "single source of truth" for static assets.  However, the problem would still manifest itself for URLs that don't refer to static assets, which is a bummer. Blarg!

**Comment by jseppi** [comment]
Hrm yeah, that's a possibility I hadn't realized (request for new asset going to old "venerable" app).

Another _potential_ (but similar) scenario: During deployment, we scale the old app down to 1 instance, and deploy 2 new instances of the new app. Maybe it is the difference in startup time between the 2 new app instances, which would kind of explain why only that 1 css file was 404ing in the screenshot: the other requests were going to new-app-instance-1, which was completely started, but that request was going to new-app-instance-2, which was not yet started.

I think your explanation is more likely though.

**Comment by jseppi** [comment]
So maybe we need to stop using the `zero-downtime-push` thing and either find another that doesn't bind the domain until the deployment is finished, or write our own script. Barf.

**Comment by toolness** [comment]
Huh, I wonder if someone on Slack has suggestions? This seems like it'd be a common problem amongst cloud.gov-based apps...

**Comment by jseppi** [comment]
Can you start that discussion since I'm tied up with this ATO stuff the rest of the week?

**Comment by jseppi** [comment]
During today's `v.2.3.0` deployment to staging I encountered a very brief window of JS/CSS downtime, so I guess CloudFront isn't the issue here.

<img width="383" alt="screen shot 2017-02-22 at 2 34 35 pm" src="https://cloud.githubusercontent.com/assets/697848/23231279/d5220d6c-f90c-11e6-99d1-cfe3e4abde2f.png">

**Comment by jseppi** [comment]
So, I think the the problem is: When we deploy, we are deploying 3 apps. The web app is the one thats "split" into the old `-venerable` and the new version, which splits traffic between the two apps. Unfortunately `autopilot` waits until all three apps are deployed before it gets rid of the `-venerable` app, so there is a like a 5-10 minute window where web requests can get split.

There's a fix in `autopilot` to properly handle an appname argument, but it has not been put into a release yet: https://github.com/contraband/autopilot/pull/24#issuecomment-290439299

**Comment by jseppi** [comment]
New version of `autopilot` has been released https://github.com/contraband/autopilot/releases/tag/0.0.3. This version takes into account the app name parameter. We'll have to modify our deploy script to push multiple apps, but it should hopefully take care of the downtime documented here.

**Comment by jseppi** [comment]
This was fixed in https://github.com/18F/calc/pull/1651
