### ISSUE TITLE
Content design: Suggestions for templated email text

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1349]
I've taken the liberty of messing with some of the text on the various system-generated CALC emails. Here's my proposed content, in text and layout form …

### [approval_reminder.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/approval_reminder.html)

>**Five price lists need your review**
We notice you haven't approved five submitted price lists in CALC. When you can, please review and approve them at https://example.com/unreviewed_price_lists.
*The CALC Team*
Button: Review these price lists now
**Questions?**
Have questions about how to review and approve? Please contact us by replying to this email.

![approval_reminder html](https://cloud.githubusercontent.com/assets/9259185/22757835/f9b24a76-ee11-11e6-8b8a-41d314ee5834.png)

### [bulk_upload_failed.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/bulk_upload_failed.html)
>**There's a problem with your upload**
Unfortunately we found an error when processing the Region 10 data files #{{ upload_source.id }} you uploaded to CALC on Friday, January 20.
Please visit https://region10link.com to try uploading again.
*The CALC Team*
Button: Try uploading again

![bulk_upload_failed html](https://cloud.githubusercontent.com/assets/9259185/22757854/11df254c-ee12-11e6-9c04-c5a06864c1ab.png)

### [upload_succeeded.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/bulk_upload_succeeded.html)
>**Your uploaded data is now live in CALC!**
The Region 10 data files #{{ upload_source.id }} you uploaded to CALC on Friday, January 20, have been approved and added to the CALC tool (https://calc.gsa.gov). Thanks for helping make CALC a better tool for all of its users!
24 rows of rate information have been loaded and previous Region 10 data has been removed from the CALC database.
5 rows were not parsed and could not be used.
*The CALC Team*
Button: View these price lists now
**Questions?**
Please reply to this email with any questions. We’ll get back to you within two business days.

![bulk_upload_succeeded html](https://cloud.githubusercontent.com/assets/9259185/22758764/acd54286-ee15-11e6-9b5e-ed45b748b748.png)

### [price_list_approved.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/price_list_approved.html)
>**Your price list has been approved!**
The price list you submitted to CALC on Friday, January 20, has been approved and added to the CALC tool (https://calc.gsa.gov). Thanks for helping make CALC a better tool for all of its users!
The submitted price list was for contract GS-12-3456 with Jimmy’s Coding and Landscaping.
Visit https://details-link-yadayada.gov to view it.
*The CALC Team*
Button: View your price list
**Questions?**
Please reply to this email with any questions. We’ll get back to you within two business days.

![email-sample-bulk-approved](https://cloud.githubusercontent.com/assets/9259185/22757976/64994114-ee12-11e6-918d-fb11ebaa437e.png)

### [price_list_rejected.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/price_list_rejected.html)
>**Your price list has been rejected**
Unfortunately the price list you submitted to CALC on Friday, January 20 has been rejected.
The submitted price list was for contract GS-12-3456 with Jimmy’s Coding and Landscaping. 
Visit https://details-link-yadayada.gov for details.
*The CALC Team*
Button: View the details
**Questions?**
Please reply to this email with any questions. We’ll get back to you within two business days.

![email-sample-price-list-rejected](https://cloud.githubusercontent.com/assets/9259185/22759000/79a3a7a8-ee16-11e6-8c3f-df5d46591fc0.png)

### [price_list_retired.html](https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/email/price_list_retired.html)
>**Your price list has been retired**
The price list you submitted to CALC on Friday, January 20 has been retired, and its pricing data will no longer be visible in CALC.
The submitted price list was for contract GS-12-3456 with Jimmy’s Coding and Landscaping. 
Visit https://details-link-yadayada.gov for details.
*The CALC Team*
Button: View your retired price list

![email-sample-price-list-retired](https://cloud.githubusercontent.com/assets/9259185/22758033/8b81906a-ee12-11e6-8512-b0b66e7e09ba.png)

I've never updated html files on git, but am happy to give it a try and integrate whatever changes here sound good. Thx @hbillings @jseppi @toolness @tram!

**Comment by jseppi** [comment]
Sweet, these designs look great!

**Comment by ericronne** [comment]
Do you think "One of your price lists has been retired" would throw off someone who's only uploaded one? 🤷‍♂️

**Comment by jseppi** [comment]
This is good to close, right, @ericronne?
