### ISSUE TITLE
Implement email designs and updated text

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1351]
Implement the html template design introduced in #1208 for the various emails (text over in #1349).

Provided we're able to tackle this prior to implementing the new colors, we should [use this as our guide](https://github.com/18F/calc/issues/1208#issuecomment-278721398) …

@hbillings @jseppi

**Comment by ericronne** [comment]
FWIW, i did *not* add ^ that ^ label! #gitgrrr

**Comment by toolness** [comment]
The email designs were fixed by #1407, and it looks like @ericronne is putting the finishing touches on the text in #1440.

**Comment by jseppi** [comment]
This is done!
