### ISSUE TITLE
Review and/or update contributing-internal.md

### ISSUE THREAD

**Issue by toolness** [18F/calc#1359]
While working on #1353, I noticed that `CONTRIBUTING-internal.md` exists, and that I've never read it. It seems to be an artifact left over from the CALC 1 team, and it points to the old "hourglass" Trello board that we no longer use.

We should probably review this at some point and update it as needed.

**Comment by toolness** [comment]
@jseppi do you think we should just get rid of this?  I dunno how much value there is in documenting our workflow, especially since it seems to change depending on the context, and the docs could easily go out of date...

**Comment by jseppi** [comment]
Toss it!
