### ISSUE TITLE
Write a basic front-end development guide

### ISSUE THREAD

**Issue by toolness** [18F/calc#1360]
There's a blurb in our setup instructions that mentions the fact that front-end assets at `/frontend/source` and built via gulpfile into `/frontend/static/frontend/built` but that isn't a lot to go on.  I think we should pull that information out into a very basic front-end guide (easily findable via the work being done in #1353) that mentions things like:

* The style guide at `/styleguide/`
* The front-end test suite at `/tests/`
* The high-level distinction between data capture's largely static, web component-based front-end vs. the data explorer's more dynamic React/Redux-based front-end

It doesn't (and *shouldn't*, for reasons of maintainability) have to be that long.

What do you think @jseppi @hbillings?

**Comment by jseppi** [comment]
Great idea!

**Comment by hbillings** [comment]
Yes!! we might also want to write just a little bit about philosophy (we loosely follow BEM, etc)
