### ISSUE TITLE
Review wiki sandbox deploy instructions

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1361]
https://github.com/18F/calc/wiki/How-to-Deploy-to-your-cloud.gov-Sandbox

Possibly remove?

**Comment by toolness** [comment]
Heh heh, yeah, I think that might be a good idea.

It also seems like https://github.com/18F/calc/wiki/How-to-Deploy-to-your-AWS-Sandbox is largely superseded by the docs in the README (soon to be in the `/docs/` folder), though I wrote the repo docs to be largely independent of AWS/AWS sandboxes, so it might still be useful to keep AWS-specific stuff in there.

**Comment by jseppi** [comment]
If we do keep these sandboox instructions, they should probably be moved to the regular `docs/` folder so that we don't have things spread out unnecessarily.

**Comment by toolness** [comment]
Ah yeah, gud point.
