### ISSUE TITLE
Link to /docs/ on dev server from README?

### ISSUE THREAD

**Issue by toolness** [18F/calc#1362]
Since the docs will soon be deployed by our dev instance at https://calc-dev.app.cloud.gov/docs/ now, I wonder if it might be a good idea to actually link to them from the README, rather than telling users to look in `/docs/` in the repo?

**Comment by jseppi** [comment]
hrm, not a bad idea. I would be a little wary of putting "expectations" on `dev` to have to be up/up-to-date. I guess if it was something like "Check in `/docs/` or _try_ looking at  https://calc-dev.app.cloud.gov/docs/ (may be out-of-date)."

**Comment by hbillings** [comment]
@toolness Is this a transition sprint task?
