### ISSUE TITLE
Use dictionary merges in the cloud docker-compose YAML example

### ISSUE THREAD

**Issue by toolness** [18F/calc#1364]
Currently our [docs for deploying to the cloud via Docker](https://github.com/18F/calc/blob/develop/docs/docker.md#deploying-to-cloud-environments) involve making a custom docker-compose file that has a *lot* of repetition in it:

```yaml
version: '2'
services:
  app:
    build:
      dockerfile: Dockerfile.cloud
    environment:
      - DEBUG=yup
  rq_worker:
    build:
      dockerfile: Dockerfile.cloud
    environment:
      - DEBUG=yup
  rq_scheduler:
    build:
      dockerfile: Dockerfile.cloud
    environment:
      - DEBUG=yup
```

But I just learned from CM in https://github.com/18F/omb-eregs/pull/39#issuecomment-279426877 that YAML actually supports weird symbols like `<<` and `&` and `*` to do merging and stuff!! I bet we can use it to make the above code less verbose.  We might also be able to make some of our other docker-compose YAML files less verbose too, I'm not sure.

**Comment by jseppi** [comment]
whoa
