### ISSUE TITLE
Add thesaurus/synonyms for labor category terms

### ISSUE THREAD

**Issue by toolness** [18F/calc#1375]
Part of Kelly's feedback on #997 is that it'd be nice if the price list analysis could take common labor category abbreviations into account, e.g.:

* "Jr." and "Junior" are the same thing
* "Sr." and "Senior" are the same thing
* "SME" and "Subject Matter Expert" are the same thing

and so on.

Obviously this will also be useful for standard CALC search, not just the price list analysis functionality.

The only problem is that figuring out how best to implement it is non-trivial.

Postgres actually has a [ridiculously customizeable Dictionary system](https://www.postgresql.org/docs/9.5/static/textsearch-dictionaries.html) but the problem is that customizations require changing the filesystem of the postgres server, which [AWS RDS does not support](https://forums.aws.amazon.com/message.jspa?messageID=626892).  So we might have to hack this.

Right now I am thinking one approach may be to add a `normalized_labor_category` field to the `Contract` model which will basically be the labor category post-processed by some normalization code that takes our custom terminology into account. We can then have our `search_index` be based off this normalized field instead of the raw `labor_category`.

**Comment by toolness** [comment]
So one approach to this, #1378, has been merged into the price list analysis branch, but nothing has been merged into the `develop` branch yet.

@jseppi want to talk about this sometime soon?

**Comment by jseppi** [comment]
yeah! Schedule some time on my calendar whenever. My blocks should all be up to date.

**Comment by toolness** [comment]
Update: talked to @jseppi about this today and we've decided to ditch the tsquery approach of #1392 and pursue the normalization approach of #1378, as it's conceptually simpler and more flexible, despite the up-front cost of re-normalizing the database whenever our normalization algorithm changes.

**Comment by toolness** [comment]
I'm also removing the "branch: price list analysis" label from this since it's already merged into PL analysis, but has yet to be merged into `develop`.
