### ISSUE TITLE
pytest raises spurious "cannot collect test class 'SkipTest'" warning

### ISSUE THREAD

**Issue by toolness** [18F/calc#1377]
When running tests, we get one pytest warning, and it's irrelevant:

```
WC1 /calc/hourglass/tests/tests.py cannot collect test class 'SkipTest' because it has a __init__ constructor
```

kind of silly that pytest is trying to process `SkipTest` as a test case, but I guess it's because it has the word `Test` in it or something. Would be nice to get rid of this so that if any *real* warnings appear, we're more likely to pay attention.

**Comment by jseppi** [comment]
Interestingly I cannot find a way to make py.test _ignore_ a specific class name pattern

**Comment by toolness** [comment]
Ugh that is annoying.  I wonder if we should import it as something that doesn't have the word `Test` in it, like `SkipMe`, so that py.test doesn't look at it?  Because it's the same class reference, it should still be treated as a skipped test when thrown.

This feels like a silly problem to have.
