### ISSUE TITLE
Make the site intro pithier, and easier to digest

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1383]
Rewrite header text to be more concise, and to serve as a springboard into the About section (where the educational heavy lifting can be done).

**Comment by ericronne** [comment]
### Current header, in layout form (minus nav)
![image](https://cloud.githubusercontent.com/assets/9259185/22990353/83338ae6-f37e-11e6-8d3e-56ba1d5d0588.png)

### Alternate copy draft
_This reflects my best guess, given my limited understanding of the CALC's conceptual space. @KellyBailey has the final word._

![image](https://cloud.githubusercontent.com/assets/9259185/22990528/1bbb76b6-f37f-11e6-83f8-052fba283de3.png)

> **Search awarded ceiling rates for contracted labor**
>
> Research professional service labor categories quickly and easily, to make better-informed decisions. Results shown are fully burdened, awarded hourly rates from GSA IDIQ service schedules.
>
> Learn about CALC >

cc @jseppi @hbillings @tram

**Comment by ericronne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to quickly understand what CALC is and how I can use it.](https://trello.com/c/deZOdAi0/167-as-a-user-i-want-to-quickly-understand-what-calc-is-and-how-i-can-use-it)

**Comment by jseppi** [comment]
Maybe simpler:

> Conduct market research on professional service labor categories quickly and easily. Results shown are fully burdened, awarded hourly rates from GSA IDIQ service schedules.

**Comment by jseppi** [comment]
> Search pricing data from GSA IDIQ schedules to quickly and easily conduct market research on professional services. Results shown are fully burdened, awarded hourly rates.

**Comment by ericronne** [comment]
I like the first one better, since the headline also starts with "Search."

**Comment by KellyBailey** [comment]
In the spirit of pithiness, how about:

**Search awarded services hourly rates for government contracts**

CALC lets you conduct market research for labor categories quickly, helping you make better informed decisions. Results shown are from Federal Government contracts. 

Learn about CALC >

**Comment by KellyBailey** [comment]
I am leaning toward more general intro because I want to start adding prices from contracts other than schedules and IDIQs.

**Comment by KellyBailey** [comment]
Maybe we can rework this blurb that is below the visualization to stand out more:

The rates shown here are fully burdened, applicable worldwide, and representative of the current fiscal year. This data represents rates awarded at the master contract level.

**Comment by KellyBailey** [comment]
I'm liking the color and fonts.

**Comment by ericronne** [comment]
@KellyBailey should we include "ceiling rates" somewhere, so users don't assume we have the rates actually paid?

> **Search awarded services hourly rates for government contracts**
> CALC lets you conduct market research for labor categories quickly, helping you make better informed decisions. Results shown are from Federal Government contracts.
> Learn about CALC >

**Comment by ericronne** [comment]
Done! Can make a new issue if we find that the new below intro fails to adequately ground new visitors.

![image](https://user-images.githubusercontent.com/9259185/38428201-d76fce96-3980-11e8-8b9c-247097a25008.png)
