### ISSUE TITLE
Normalize postgres version and test against it

### ISSUE THREAD

**Issue by toolness** [18F/calc#1388]
It'd be nice to have tests in [`hourglass/tests/test_configuration.py`](https://github.com/18F/calc/blob/develop/hourglass/tests/test_configuration.py) that ensure travis, dev/prod/staging, and our docker-compose setup all use the same version of postgres, but right now they're actually in conflict:

* `.travis.yml` specifies postgres 9.3
* `docker-compose.yml` specifies 9.4
* I have no idea what we use on dev/staging/prod

If there's no way to express what version of postgres CloudFoundry/AWS should use in our repo (the way  we specify the python version via `runtime.txt`) then it might be good to add a check in `/healthcheck` that queries the DB for its version and makes sure it's something expected.

This seems increasingly important as we improve CALC's performance and functionality by using features introduced in postgres' more recent versions.

**Comment by jseppi** [comment]
cloud.govs `aws-rds` service broker does not seem to surface any version information about the RDS instances it creates unfortunately.

**Comment by jseppi** [comment]
Roger suggested using `SELECT version()`, which I guess we could call from Django to surface the version to `/healthcheck`

**Comment by toolness** [comment]
Cool--I also just noticed that Django's postgres driver appears to have a [`pg_version()` method](https://github.com/django/django/blob/master/django/db/backends/postgresql/base.py#L273-L276) too. It's automatically cached, so I guess it could be slightly more efficient, uh, if we're worried about our healtcheck endpoint getting DoS'd or something.

**Comment by jseppi** [comment]
FYI, just ran `SELECT version()` on `calc-dev` and got this back:

`'PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit'`
