### ISSUE TITLE
Add a content guide

### ISSUE THREAD

**Issue by toolness** [18F/calc#1390]
I think we should add a project-specific content guide to our docs.

Here are examples of other project-specific 18F content guides: https://github.com/18F/Design-Wiki/wiki/Content-Guide

The one item I would like to see in our content guide is an adherence to using [SENTENCE CASE](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98) because, among other benefits, it is **frendlier** and **easier to define**.

Whaddya say @hbillings @ericronne ?!

**Comment by ericronne** [comment]
Good idea. For brevity and maintainability, do you think it should only note CALC-specific rules, as well as where our style differs from the [18F content guide](https://pages.18f.gov/content-guide/)?

**Comment by hbillings** [comment]
@toolness @ericronne Is this a transition sprint task?

**Comment by toolness** [comment]
Hmm, it's up to y'all really!  I'm fine w/ not having it be a transition task, but if folks think it's important then let's bust it up!
