### ISSUE TITLE
"Add price data" pg: Content and design for when authorized users *are* logged in

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1412]
"Add price lists" will always be visible, regardless of whether a user or not a user is logged in.

## Logged in users will see the data upload tool …

*Rough wireframes:*
![image](https://cloud.githubusercontent.com/assets/9259185/23187043/fc17a418-f84e-11e6-9598-4271bda714df.png)
![image](https://cloud.githubusercontent.com/assets/9259185/23187061/13476d30-f84f-11e6-80f6-f7eec37724de.png)

## But we need to create the default / not-logged-in content (and design)

*Rough wireframe:*
![image](https://cloud.githubusercontent.com/assets/9259185/23187016/dcf563ae-f84e-11e6-961f-74d78bcce507.png)

**Comment by ericronne** [comment]
Leverage this email for content …
![image](https://cloud.githubusercontent.com/assets/9259185/23475543/83205354-fe7d-11e6-8d55-e601bc7799d7.png)

**Comment by hbillings** [comment]
Is this still relevant, @ericronne?

**Comment by ericronne** [comment]
I think the tutorial content would definitely be handy to have on the site for new logged-in users to reference. If you agree, i'll …

- [ ] design a place on the site for this to live

 I had designed a motif where it would be visible to *anyone*, but some worry that might confuse those who don't have the authority to do so. 

![image](https://user-images.githubusercontent.com/9259185/41240465-27d38dec-6d60-11e8-9511-4f03842026a7.png)

#1460 is the related pr, very long in the tooth.

**Comment by ericronne** [comment]
To Do:
- [ ] Design a way for logged-in users to access this tutorial....

![image](https://user-images.githubusercontent.com/9259185/45384923-0ae15080-b5d5-11e8-925d-5be6dc66199d.png)
