### ISSUE TITLE
Implement account menu (with current site look)

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1413]

**Comment by ericronne** [comment]
As defined in #1381 

![image](https://cloud.githubusercontent.com/assets/9259185/23187445/6b400e88-f850-11e6-8bfc-56e9a21f2683.png)

**Comment by ericronne** [comment]
![image](https://cloud.githubusercontent.com/assets/9259185/23187764/ac943066-f851-11e6-8023-2adeceb11563.png)

**Comment by jseppi** [comment]
I volunteer

**Comment by ericronne** [comment]
### [Sketch file}(https://drive.google.com/open?id=0BwWYNZcEDfwaYjNIZUttVVdsbEE)

**Comment by jseppi** [comment]
How I open this??

**Comment by ericronne** [comment]
Ooh you need Sketch!
Shouldn't be critical in this case, since it's so simple. But you might want to get your hands on it for future fun. 

LMK if you have q's re the design, of course. Once you've created it, i can tweak the css, if needed. Thx!

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I should be able to access "My activity" and "Log out" from an easily navigable location.](https://trello.com/c/JXBYBuLk/241-as-a-user-i-should-be-able-to-access-my-activity-and-log-out-from-an-easily-navigable-location)

**Comment by jseppi** [comment]
@ericronne do you have an svg for the triangle next to the user email address?

this one seems good to me:

```svg
<svg width="400" height="400" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
  <path d="M183.138 172H16.862L100 28"/>
</svg>
```

**Comment by ericronne** [comment]
Too many letters and numbers!
## [Here's mine](https://drive.google.com/open?id=0BwWYNZcEDfwaaEJ4SnhPUmlBc1U)

**Comment by jseppi** [comment]
that's 5x the bytes!

**Comment by ericronne** [comment]
blame sketch!
how do if view the one you like?
¯\_(ツ)_/¯

**Comment by ericronne** [comment]
haha. um. ... ur trolling me?

**Comment by jseppi** [comment]
I'll use yours, but I cleaned it up using this handy web app https://jakearchibald.github.io/svgomg/:

```svg
<svg width="10" height="7" viewBox="0 0 10 7" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 0l4.95 6.905L9.9 0"/>
</svg>
```

**Comment by ericronne** [comment]
*bookmarked*

**Comment by jseppi** [comment]
blurf, menu background gets eaten on Admin page:

<img width="612" alt="screen shot 2017-02-22 at 12 18 06 pm" src="https://cloud.githubusercontent.com/assets/697848/23225855/1962f6ee-f8f9-11e6-8e50-6d3624b5dfa8.png">

**Comment by jseppi** [comment]
hrm, not sure how that happened actually, and now I can't recreate. The menu seems to fit in the admin header completely:

<img width="645" alt="screen shot 2017-02-22 at 12 34 29 pm" src="https://cloud.githubusercontent.com/assets/697848/23226554/91c026be-f8fb-11e6-92c5-dbfa834b2f10.png">

**Comment by ericronne** [comment]
That subnav is ad hoc; i wouldn't worry about it for now.
