### ISSUE TITLE
"Help us improve" link at top-right of every page doesn't do anything

### ISSUE THREAD

**Issue by toolness** [18F/calc#1424]
> <img width="234" alt="screen shot 2017-02-23 at 11 29 07 am" src="https://cloud.githubusercontent.com/assets/124687/23268322/5983837a-f9bb-11e6-9df8-2a884b9d5eea.png">

I just realized it's a link to `#help-wanted`, which doesn't exist on most/all pages, so clicking it does nothing. 😞

**Comment by jseppi** [comment]
ha, dang. I wonder what it's intention was. I can't think of any content we have that would be relevant right now, so maybe best to remove it?

**Comment by hbillings** [comment]
It should link to the data capture tool, because contributing there helps CALC. :trollface:
