### ISSUE TITLE
Standardize border radius

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1426]
I set our `$border-radius` variable to `0` a while back to standardize things that had rounded corners with the USWDS, but there are a few things that need a border radius of `4px`. The variable should reflect the latter, and places where the border radius is explicitly set to `0` to override various things should be removed because it's sort of an antipattern.

**Comment by jseppi** [comment]
👍 When implementing the user menu I was surprised when I searched for a border-radius variable and found it set to 0, so ended up hard-coding the value there.

**Comment by jseppi** [comment]
@hbillings: I think this may have been mitigated by the recent move to WDS in #1672.
