### ISSUE TITLE
Evaluate Yarn for managing node deps

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1427]
Might alleviate #1345!

We can probably store the yarn lockfile in our node_modules docker volume.

**Comment by toolness** [comment]
NOICE i'm up for it!

**Comment by jseppi** [comment]
I was using it locally for a while and it worked fine. We don't have any fancy node deps, so I doubt there will be any problems switching to it.

**Comment by jseppi** [comment]
Want to bust this up, Docker Master @toolness?

**Comment by jseppi** [comment]
Should be straightforward, right? 

- Replace `npm install` with `yarn` in `update.sh` and `.travis.yml`
- Commit `yarn.lock`
- Update docs

**Comment by jseppi** [comment]
hrm, maybe I'm almost done already... https://github.com/18F/calc/pull/1463
