### ISSUE TITLE
Consider backporting refactorings from R10 price list gleaner into develop branch

### ISSUE THREAD

**Issue by toolness** [18F/calc#1430]
@jseppi , you made some refactorings in #1284 (creating a `spreadsheet_utils` module, moving some of the XLS utils into `data_capture/tests/common.py`, changing the initialization options for `FakeWorkbook`, etc) that are making it a bit challenging to keep #997 in sync with `develop`... do you think any of those refactorings would make sense to backport into `develop`?

It's ok if not, I just figured I'd ask.

**Comment by jseppi** [comment]
Yeah! I think they'd be good to go into `develop`. I can work on my git-fu to try to get it done.
