### ISSUE TITLE
Ignore roman numerals in price list search

### ISSUE THREAD

**Issue by toolness** [18F/calc#1438]
From Kelly:

> Is there a way to ignore any levels after the labor category? I think you had it fixed for some labor categories, but some of the other labor categories were including them. I think you got it to ignore numbers, but I think some include roman numerals.

I guess we could do this by adding a list of "stop words" to the analysis and stripping roman numerals.

Should this apply to the data explorer too, though?  i.e. should a search for "engineer II" actually just show results for "engineer"?

**Comment by jseppi** [comment]
huh, seems like the roman numerals are somewhat useful for indicating seniority/experience. Or at least _commonly_ used in CALC's current data.

However, it does make some sense to me for using just the base term ("engineer") and then using the experience/education/etc filters for adjusting seniority.

**Comment by toolness** [comment]
Yeah, based on our screenhero conversation today, I think it makes sense to *not* treat roman numerals as stop words in the search index, but to remove them from labor category names when doing price list analysis.

**Comment by jseppi** [comment]
Closed by #1458
