### ISSUE TITLE
In PL analysis, only search for stuff that is >= edu and exp level

### ISSUE THREAD

**Issue by toolness** [18F/calc#1452]
This basically removing that one "finder" that searches for comparables at the same education level and min exp + 4 years.

**Comment by ericronne** [comment]
@tadhg-ohiggins / @hbillings i believe this resolved and close-worthy, true?

**Comment by hbillings** [comment]
I'm not entirely sure what "finders" means in this context, tbh.

**Comment by ericronne** [comment]
Got me. The merged pr says "fixes #1452," so it appears @toolness considered it done.
