### ISSUE TITLE
Step indicator styling: current site colors

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1464]
Currently the steps indicator has only two states: 
**Not yet visited:**
![image](https://cloud.githubusercontent.com/assets/9259185/23524065/b6361590-ff4e-11e6-8a3f-b7379a73a1ce.png)
and **You are here / Completed**, which both get identical treatment:
![image](https://cloud.githubusercontent.com/assets/9259185/23524081/cee78a7e-ff4e-11e6-9e08-06ce7d8e57e3.png)

## How that looks in action
![image](https://cloud.githubusercontent.com/assets/9259185/23523975/725023fc-ff4e-11e6-854b-61f80726d9f4.png)

## Update to match this design
![image](https://cloud.githubusercontent.com/assets/9259185/23555832/0a5caf02-fff0-11e6-8eee-924b63f11041.png)

**Note: we also wanted to add interactivity to the circles, so users could have random access to any page they've already completed. Will do another issue...

**Comment by ericronne** [comment]
Check icon is fontawesome:
fa-check [&#xf00c;]

**Comment by jseppi** [comment]
@ericronne I fixed it for you. Just need to surround stuff like that with backticks

```
`code-y stuff`
```

**Comment by ericronne** [comment]
🇺🇸

**Comment by hbillings** [comment]
Is this different from #1253?

**Comment by ericronne** [comment]
Yes, it excludes the interactive part (in hopes of getting 'er done), and also only covers the current site color scheme, as you can see by the issue title.*

*Which i changed just now, after you pointed me to the issue. I knew i'd made that!

**Comment by hbillings** [comment]
@ericronne Does this still need doing?

**Comment by hbillings** [comment]
@ericronne ping

**Comment by ericronne** [comment]
Yes! Please! Thank you!
Actually i may be able to do some of this on my own. 🤔 

Here's another reference from a duplicative issue …
![step indicators](https://cloud.githubusercontent.com/assets/9259185/22077597/67c88b36-dd7a-11e6-9d53-e473bb098f59.png)

**Comment by hbillings** [comment]
That screenshot has different colors from the one in this issue -- which should it be?

This is probably going to take some witchery; let me know when you'd like me to butt in.

**Comment by ericronne** [comment]
The old colors were stopgap. These are correct …

![image](https://user-images.githubusercontent.com/9259185/39057863-f6e6130c-447f-11e8-8a3d-0553cec82fcc.png)

The upload screens need to have colors updated (#1817)

**Comment by ericronne** [comment]
![image](https://user-images.githubusercontent.com/9259185/39060357-bd7a2bce-4486-11e8-87a0-1fd4478fad5e.png)

**Comment by hbillings** [comment]
Blocked until we figure out what functionality the step bar is supposed to have as a navigation tool. See associated PRs.
