### ISSUE TITLE
Add update_normalized_search_field command

### ISSUE THREAD

**Issue by toolness** [18F/calc#1470]
I just realized that in our shadowed `manage.py update_search_field` command, introduced in #1378, the majority of execution time is spent updating the full-text search indexes rather than actually checking to see if any `normalized_labor_category` fields need updating--at least in the common case where no fields need updating.

The main reason we're running this command in `cf.sh` and `update.sh` is for the unusual case where our algorithm for normalizing labor categories has changed; if nothing's changed, we're not going to need to re-index the search field, yet we're still doing that, because that's what `update_search_field` is intended for. 

So instead, it might be better to stop shadowing `update_search_field` and just add a new `update_normalized_search_field` command that *only* updates the search indices if any `normalized_labor_category` fields were changed.

This should speed up `update.sh` and `cf.sh` a bunch, in the common case at least.

Thoughts @jseppi ?

**Comment by jseppi** [comment]
Maybe keep `update_search_field` shadowed and add a second command (`update_normalized_search_field`) or add a flag to the shadowed `update_search_field`?

**Comment by jseppi** [comment]
But I don't feel strongly either way :)
