### ISSUE TITLE
Small bug: Loading indicator partly hidden by Filters

### ISSUE THREAD

**Issue by brethauer** [18F/calc#149]

**Comment by maya** [comment]
@brethauer Yes, I moved it to the graph div and then moved it back bc it was causing a bug in Firefox that messed up the layout:

move- https://github.com/18F/calc/commit/1e405e6334050416ee13a14e8f5eb4e8c72e63ba
undo- https://github.com/18F/calc/commit/c0dd3db66db2e9ff0e80b57dbbab0c8ed8cc554d

**Comment by maya** [comment]
Here is a fix: https://github.com/18F/calc/pull/157
