### ISSUE TITLE
Make /healthcheck/ always return 200 because CloudFront is weird

### ISSUE THREAD

**Issue by toolness** [18F/calc#1516]
On calc.gsa.gov right now, we haven't set up the `Site` object, which means that the page's source contains the following post-#1407:

```html
<link rel="canonical" href="https://example.com/">
```

And that means that pasting CALC's URL into sites like Facebook does the following:

![pasted image at 2017_03_23 08_00 am](https://cloud.githubusercontent.com/assets/124687/24249082/47f2b434-0fa8-11e7-8203-e22ab4a26f85.png)

😞

**Comment by toolness** [comment]
Er, also, `/healthcheck/` should verify that `request.META['HTTP_HOST']` is the same as the current `Site`'s `domain` property. I meant to add that to #1407 but .. wait, no, I *did* add it!

Ummm and `curl -I 'https://calc.gsa.gov/healthcheck/'` gives me:

```
HTTP/1.1 500 Internal Server Error
```

because the payload is:

```json
{  
   "version":"2.5.1",
   "is_database_synchronized":true,
   "canonical_url":"https://example.com/healthcheck/",
   "request_url":"https://calc.gsa.gov/healthcheck/",
   "canonical_url_matches_request_url":false,
   "rq_jobs":0
}
```

@jseppi is New Relic not currently checking `/healthcheck/` or something?

**Comment by jseppi** [comment]
No, we don't have New Relic setup to monitor `/healthcheck/`. Will add it now!

**Comment by jseppi** [comment]
Ugh, wait, we actually did have it setup. Unsure why it wasn't alerting...looking into it.

**Comment by jseppi** [comment]
Theory that @toolness and I just came up with: When we should be getting a `500` error, CloudFront is instead serving a cached version of its last known good response.

**Comment by jseppi** [comment]
🤦‍♀️ 
From: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html

> If your origin returns a 5xx error code, CloudFront serves the object even though it has expired. For the duration of the error caching minimum TTL (five minutes by default), CloudFront continues to respond to viewer requests by serving the object from the edge cache.

**Comment by toolness** [comment]
I actually vaguely recall reading this a few months ago but I didn't (and still don't) actually understand what it *means*.  Does it basicall mean that CF will be serving the last-good response?

CF is so confusing...

**Comment by toolness** [comment]
um, so i guess another alternative is just to have `/healthcheck/` always return 200, but include the `"is_everything_ok"` key in it, and we check against that instead of the doggone response code.

bleh.

**Comment by jseppi** [comment]
There are a lot of situations described on that linked page, but from what I can gather it is that CF keeps serving the last-good response, regardless of expiration headers, when the response was 5xx. Interestingly, it looks like if it is 4xx, it will actually return the error, but not the requested "object".

**Comment by jseppi** [comment]
This is so whacky

**Comment by jseppi** [comment]
Yeah, always returning `200` is the only thing that seems like it will work. Which is goofy IMO, but 🤷‍♀️

**Comment by toolness** [comment]
Ok I will bust a PR soon!

**Comment by jseppi** [comment]
![](https://media.giphy.com/media/l3V0nKt696ClG9Xws/giphy.gif)
