### ISSUE TITLE
Add section on new relic to monitoring.md

### ISSUE THREAD

**Issue by toolness** [18F/calc#1521]
It might be useful to specifically document how we set up monitoring on new relic in the `monitoring.md` file that was added in #1520.

We can mention our pinging of the `/healthcheck/` endpoint. Are there any other major checks we should mention @jseppi?

**Comment by jseppi** [comment]
Our production test suite, once we have it running somewhere.

**Comment by hbillings** [comment]
@toolness Is this a transition sprint task? Or is this done? (I see the `/healthcheck/` endpoint mentioned, but I don't see any mention of New Relic specifically.)

**Comment by toolness** [comment]
Um, good question--this is definitely something I should look into now that Seppi's gone!
