### ISSUE TITLE
Consider using Flow or TypeScript

### ISSUE THREAD

**Issue by toolness** [18F/calc#1527]
So we've been using mypy for our python code and I feel like it's been useful.  It's especially nice because it's all standard Python 3.6, so it's not some "superset" of the language that we need to learn to use it effectively.  It also means there isn't an extra build step involved in compiling and running the code.

As much as I like TypeScript, it doesn't have these advantages, because it's a superset of JS that requires extra work for developers and it introduces an annoying build step.

An alternative to TypeScript that I haven't explored yet is Flow.  One of the interesting advantages it has over TypeScript is that it's possible to annotate code using *comments* instead of Flow's JS superset:

https://flowtype.org/en/docs/types/comments/

This could allow us to sprinkle in strong typing on our JS much like we've been doing for our python.  What do you think @jseppi ?

**Comment by toolness** [comment]
Another neat thing about Flow is that it understands React natively (understandable, since it's also by Facebook).  In particular it understands the `propTypes` React Components use, so our existing use of `propTypes` will automatically be used for Flow's static analysis, which is pretty awesome.

**Comment by toolness** [comment]
I've been playing around with Flow's comment syntax on [18F/a11y-metrics](https://github.com/18F/a11y-metrics).

I really like how I don't have to deal with a build step to get the benefits of strong typing, but I am a bit bummed by the lack of syntax highlighting when all the type annotations are in comments.

An interesting thing I learned about Flow's standard (non-comment-based) syntax is that, unlike TypeScript, it's only concerned with *stripping out* type annotations rather than *transforming code*.  TypeScript is a bit complex in that in addition to strong typing, it also does what Babel does, i.e. transpiling ESwhatever to ES5.  In contrast, Flow just has a Babel transform called [flow-remove-types](https://github.com/flowtype/flow-remove-types), which I suspect is a lot simpler and possibly easier to integrate into existing asset pipelines than TypeScript.

**Comment by jseppi** [comment]
I have been wanting to give `Flow` a try, but I'm a little reluctant to spend time adding yet another development thing to the project I guess. Seems like we've been doing a lot of dev tooling and not much feature building recently :\

Is it just as easy as adding https://babeljs.io/docs/plugins/syntax-flow/ and `flow-remove-types` to our webpack's babel config? And then I guess also setting up our local editor to support flow? That doesn't sound too bad actually.

**Comment by toolness** [comment]
ummm wait what would the difference be between using flow and typescript then?  would we have to get permission to use flow from the front-end guild?  i thought that's what we'd have to do if we wanted to use typescript...

maybe "typescript" is actually really bad for branding--makes it sound like a separate language instead of just sprinkling type safety on top of JS...

anyhow, i'd be up for using regular flow syntax, though at that point we might want to more carefully evaluate the tradeoffs between it and typescript.  the native understanding of React in flow is nice, but i'm curious if typescript has a larger community of third-party type annotations.

**Comment by jseppi** [comment]
I don't think I was arguing in favor of Typescript o_O I also don't think there's any case where we need to get _permission_ from the guild.

**Comment by toolness** [comment]
Oh sorry, *I* was arguing in favor of TypeScript, and I think I was worried it might be violating front-end guidelines because of how it's like a "superset" of JS or whatever.  Maybe I was just imagining that people would take issue with that, when in fact perhaps no one cares.

I mentioned [above](https://github.com/18F/calc/issues/1527#issuecomment-289943414) that Flow understands `propTypes` natively but in fact that no longer seems to be the case (the blog post I linked to re: that was from Flow's announcement in 2014).  I suppose it is all for the best since Flow's (and TypeScript's) type system is so much richer than that `propTypes` stuff.

**Comment by toolness** [comment]
Huh, I just noticed that TypeScript actually supports [type-checking normal `.js` files](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files) now, and what's really neat is that it actually parses JSDoc comments if they're present.  This is really cool because it means we can just document our code and TypeScript will make sure it all checks out.

**Comment by toolness** [comment]
FWIW, we started using TypeScript on the OMB policy library and it worked really well, as runtime errors basically disappeared (but I'm biased).  It works especially well with VSCode (much better than it did with Sublime Text, which often got out-of-sync with the actual feedback from the typescript compiler).

That said, we weren't using React on the code that we were TypeScript'ing, and React code _does_ get a bit verbose because of the fact that all your components have to be parameterized based on `props` and `state`.

**Comment by jseppi** [comment]
And TypeScript would require rewriting all our Data Explorer frontend JavaScript code in that language, right?

**Comment by toolness** [comment]
Nope, TypeScript plays pretty well with regular ol' JS.  Similar to the way mypy works, we can intermingle TS with JS.  I've heard that flow is a bit better at making inferences about mixed typed-and-untyped codebases, though... but TypeScript has way more third-party type annotations that have been contributed by the community, so there's pros and cons.

**Comment by jseppi** [comment]
Cool! I had thought it was its own language. Clearly I need to do some catch-up reading!

**Comment by toolness** [comment]
Oh, I mean, it's a typed superset of JS... it doesn't actually change JS's semantics though, it just constrains what can be done with it, so that you don't end up doing property lookups on `null` and stuff like that.  And even if there are type errors that typescript raises, it can still output your code to JS, so that you're not actually limited from doing anything that JS lets you do.  Really all the "typescript compiler" does, aside from the type checking, is _strip out_ the type information so that normal JS interpreters can run your code.  (It can also do some generic transpilation stuff like Babel does, but that's an extra bonus, and one that we probably wouldn't use since we've already got babel.)

Another way of thinking of it is that it's just a glorified linter, that lets you annotate your code with special instructions to the linter, which the linter then strips out for you so you can actually run your code.
