### ISSUE TITLE
Factor out a price-list specific step template

### ISSUE THREAD

**Issue by toolness** [18F/calc#1534]
As mentioned in https://github.com/18F/calc/pull/1491/files#r106563694:

> I think we made `step.html` back when price list upload was the *only* step-based workflow that existed, but I wonder if it might make sense to make a `data_capture/price_list/step.html` base template at this point, and move this replay code in there...

**Comment by hbillings** [comment]
@toolness does it make sense to do this as part of the transition sprint?

**Comment by toolness** [comment]
Hmmmm, in an ideal world I think it might be, but given all our other priorities for the transition sprint, I think it's OK that we just leave it documented here, but keep it off the milestone.
