### ISSUE TITLE
Refactor DAP related code into separate module

### ISSUE THREAD

**Issue by jeremiak** [18F/calc#1538]
The [DAP workaround in calc](https://github.com/18F/calc/blob/9c0793fe793c1505bd44a7f41a5ef3370758191f/frontend/source/js/common/dap-hacks.js) is broadly useful to all projects at 18F that are using DAP and are single page apps. I think it would be great to have this code refactored as a small module that I could use in the 18f/crime-data-explorer application.

**Comment by jseppi** [comment]
Instead of propagating the workaround, is there anyone at DAP we can work with to get https://github.com/digital-analytics-program/gov-wide-code/pull/48 (I think that's the right one) merged in? 

cc @toolness

**Comment by toolness** [comment]
It looks like the contents of https://github.com/digital-analytics-program/gov-wide-code/pull/48 were actually included in https://github.com/digital-analytics-program/gov-wide-code/commit/84a8e2c85ddbdb63a736410f7c102df4b9bc56f5, which basically means our fixes are actually in DAP now! So I'm closing this issue.
