### ISSUE TITLE
Automated travis deploys to dev are failing

### ISSUE THREAD

**Issue by toolness** [18F/calc#1556]
Looks like the [relevant line](https://travis-ci.org/18F/calc#L1332) is:

```
error: Server error, status code: 400, error code: 100002, message: The app name is taken: calc-dev-venerable
```

**Comment by jseppi** [comment]
You will have to manually go to the dev space and delete the existing `calc-dev-venerable` (`cf delete calc-dev-venerable`), then run another dev build+deploy.

**Comment by jseppi** [comment]
Closing since solution was given, and we aren't on Travis any longer (though the same thing could happen in Circle or even with manual deploys).
