### ISSUE TITLE
Add cron-type run of production tests once CircleCI supports it

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1565]
Due to the migration to CircleCI (https://github.com/18F/calc/pull/1563), we no longer have daily cron builds to run our suite of production tests. CircleCI is apparently adding this type of functionality. We should use it once it is available.

**Comment by afeld** [comment]
Now supported! https://circleci.com/docs/2.0/configuration-reference/#schedule

**Comment by jseppi** [comment]
Grabbing this one...
