### ISSUE TITLE
Add back sauce/web-driver tests to CI builds

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1566]
During the migration to CircleCI (https://github.com/18F/calc/pull/1563) time was too short to get our tests running in WebDriver IE via Sauce like we had in Travis (ref: https://github.com/18F/calc/blob/302cc668e7325aa7a7752bf1ee80d9b4c1e83bb6/.travis.yml#L29 )

Refs:
- https://github.com/18F/calc/pull/1563/files#1d37e48f9ceff6d8030570cd36286a61R25
- https://github.com/18F/calc/pull/1563/files#1d37e48f9ceff6d8030570cd36286a61R135

**Comment by toolness** [comment]
Fixed by #1669!
