### ISSUE TITLE
Data Administrators should be able to delete users

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1577]
Data Administrator role should have the `auth.delete_user` permission so that they can remove inactive users.

In lieu of that change being made, a user targeted for removal can instead have all roles removed, which will effectively be a removal from access to any functionality.

**Comment by jseppi** [comment]
Actually I think we just intended marking users as not active instead of deleting them:

<img width="787" alt="screen shot 2017-09-20 at 8 21 26 am" src="https://user-images.githubusercontent.com/697848/30646001-1c60a830-9ddd-11e7-994d-4f7110953e4d.png">

I think that means we should remove the display of the Delete button for users who do not have the `auth.delete_user` permission.

**Comment by toolness** [comment]
Yup, that's correct, the philosophy was to make it as hard as possible to _actually_ delete things from the DB; rather, mark them as inactive so that "deletion" is easy to undo.

**Comment by jseppi** [comment]
Closing!
