### ISSUE TITLE
Results table breaks mobile layout

### ISSUE THREAD

**Issue by blacktm** [18F/calc#158]
The responsive layout looks awesome, BTW. Only issue is an overflow isn't set on the results table, so the whole page width is affected. The fix is pretty simple:

On the `#results-table`, wrap in a `<div>`, and set styles of wrapper to:

```
width: 100%;
overflow: scroll;
```

Now just the table can be scrolled horizontally without affecting the rest of the page.

**Comment by maya** [comment]
Thanks for that catch! I've implemented that fix here #159

**Comment by blacktm** [comment]
@maya Awesome, glad I could be useful!
