### ISSUE TITLE
Terminate session after browser close or 15 minutes of inactivity

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1584]

**Comment by toolness** [comment]
FWIW, I think that cloud.gov helps us with this a bit--it doesn't necessarily solve this issue, but it helps with security. Basically, the UAA tokens we get from cloud.gov only last 15 minutes, and we auto-refresh them transparently, unless cloud.gov denies the refresh, in which case we have to forcibly log out the user. See https://github.com/18F/cg-django-uaa/pull/24 for more details.

In the case of this issue, though, I guess we further want to set Django's cookie settings to behave in this way.

**Comment by jseppi** [comment]
Looks like they intended to say that both the session clear on browser close AND on 15-minutes-of-inactivity need to happen.

**Comment by jseppi** [comment]
Given that we don't have a good way of detecting idle time as @toolness pointed out, for now we'll just go with expiring the session cookie upon browser close via the`SESSION_EXPIRE_AT_BROWSER_CLOSE` setting.
