### ISSUE TITLE
Docs should specify that "python" should launch python 3, not python 2

### ISSUE THREAD

**Issue by josefdaly** [18F/calc#1602]
Would be helpful to note that python 3 should be default python binary.

**Comment by jseppi** [comment]
Hi @josefdaly - the python version is specified (currently as `3.6.2`) in https://github.com/18F/calc/blob/develop/docs/setup.md. If that's not clear, then a PR would be appreciated.

**Comment by toolness** [comment]
Hmm, I think what @josefdaly means is that running `python` from the command-line should start python 3.6.2, which is a bit different from "having python 3.6.2 installed".  For example, frequently multiple versions of python are installed on a system, and `python` actually runs python 2.7, while `python3` is the command tied to a python 3.x version.

So we might want to explicitly mention that aside from having 3.6.2 installed, running `python` from the command-line should actually start 3.6.2, and not some other version of python.

(@josefdaly , if I'm misinterpreting you, please let me know!)

**Comment by josefdaly** [comment]
@toolness That is what I meant. It is clear that 3.6 is a dependency but on many systems, `python` points to 2.7 instead of 3.x. Probably not absolutely necessary, but would add a tad of clarity.

**Comment by afeld** [comment]
Might want to tell people to run `python3` instead, no?

**Comment by jseppi** [comment]
I've never had to run `python3` personally. Is that the more common practice? It seems like systems I've been on have had `python` set to a v3 version, though I'm generally operating on my work Mac and/or in Docker, so maybe I'm missing that situation (or some other script took care of setting up that alias).
