### ISSUE TITLE
Potentially replace Selenium/PhantomJS/WebDriver with Puppeteer

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1624]
[Puppeteer](https://github.com/GoogleChrome/puppeteer) is a headless Chrome with a fairly easy-to-use NodeJS API. It might make our local PhantomJS-tests easier/more reliable.

Should investigate more.

**Comment by toolness** [comment]
Yeah! I've used it and I like it a lot. Only caveat is that it does require a relatively recent version of node, like 7 or 8, so we might need to upgrade our  version of node, but that shouldn't be too much of a problem.

**Comment by toolness** [comment]
err so the one thing about puppeteer though is that it's chrome-specific.  one of the advantages of selenium/webdriver is that it's implemented for all major browsers, so it's easier to test our stuff across all of them. if that's not a big concern though, and we're really just interested in testing the integration of our front-end w/ our back-end, then this could be a good solution.

**Comment by jseppi** [comment]
Yeah...we seem to have no current cross-browser testing services currently approved at GSA :\

**Comment by toolness** [comment]
We started using PhantomJS on CircleCI on #1669, and ever since then (it's been about a week) we haven't had any weird random fails on it like we did with Travis.  Given that PhantomJS works fine and we've already got a decent number of reliable Selenium-based tests, I don't think this is super high priority.

**Comment by jseppi** [comment]
Had a bunch of random selenium failures again today with #1736 :\

**Comment by jseppi** [comment]
Looking into this...

**Comment by jseppi** [comment]
Closing per comments form @toolness above. Can open a new issue in the future if necessary.
