### ISSUE TITLE
Write and implement a site description for search engines like google

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1636]
Current google results for [gsa contracting labor](https://www.google.com/search?ei=M1-xWqTnIY_s5gLEkoLwBA&q=gsa+contracting+labor&oq=gsa+contracting+labor&gs_l=psy-ab.3...3311.3311.0.4108.1.1.0.0.0.0.85.85.1.1.0....0...1.1.64.psy-ab..0.0.0....0.5SNShBYxosM) are essentially gibberish …

![calc meta info ugh](https://user-images.githubusercontent.com/9259185/37678288-9a59934e-2c4b-11e8-8469-1a62ba426fb4.png)

- [ ] Write a meaningful description
- [ ] Implement in the code

**Comment by ericronne** [comment]
The summary differs based on the search query. _I need to learn more about how this stuff works._

### Results of a search for "[gsa contracting rates](https://www.google.com/search?ei=hX6xWr3DI8Hr5gKerbbgDQ&q=gsa+contracting+rates&oq=gsa+contracting+rates&gs_l=psy-ab.3..0i30k1.850.850.0.1220.1.1.0.0.0.0.247.247.2-1.1.0....0...1.1.64.psy-ab..0.1.246....0.LXmPYYYgJh8)"

![image](https://user-images.githubusercontent.com/9259185/37684191-3efef95a-2c5d-11e8-91bb-4eac4ef07dd9.png)

### Looks like we have "[gsa labor rates](https://www.google.com/search?ei=iH6xWo_jC8Lv5gKSl5bIDw&q=gsa+labor+rates&oq=gsa+labor+rates&gs_l=psy-ab.3..0j0i7i30k1l4j0j0i7i30k1l2j0i30k1l2.315783.316368.0.317055.5.5.0.0.0.0.130.406.3j1.4.0....0...1.1.64.psy-ab..1.4.402...0i13k1.0.yEeMU44EZWI)" covered pretty well

![image](https://user-images.githubusercontent.com/9259185/37684332-b459fc7c-2c5d-11e8-8975-222ce3d5bc61.png)

### Again, "[gsa contracting labor](https://www.google.com/search?ei=xX-xWv-uOtHm5gKKo5QY&q=gsa+contracting+labor&oq=gsa+contracting+labor&gs_l=psy-ab.3..0i22i30k1l4.183949.189247.0.191046.21.20.1.0.0.0.140.1958.13j7.20.0....0...1.1.64.psy-ab..0.21.1961...0j0i67k1j0i131k1j33i160k1.0.vWEfduFGcso)"

![image](https://user-images.githubusercontent.com/9259185/37684498-32f35380-2c5e-11e8-806e-2b415337e1cc.png)

### Btw assisted search … very interesting …

![image](https://user-images.githubusercontent.com/9259185/37684617-a08fc90a-2c5e-11e8-9c4c-334faeac36bd.png)

![image](https://user-images.githubusercontent.com/9259185/37684576-892881b2-2c5e-11e8-867f-177b84bff4e8.png)

CALC is impressively the top result for a number of searches! 🥇

**Comment by jseppi** [comment]
Related: https://github.com/18F/calc/issues/135

**Comment by hbillings** [comment]
@toolness @ericronne Is this a transition sprint task?

**Comment by toolness** [comment]
I am _super_ confused by this issue--I don't understand why google acts one way with one query, but a totally different way for another query.  I dunno, man.

Purely in the interest in keeping the scope of transition un-bloated, I think we should keep it out of the milestone.
