### ISSUE TITLE
Revise release/deployment procedures to a 2-tier system

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1637]
The current release procedure is a bit over-complicated and we did not historically make much use out of the `staging` branch/deployment. I think it would be a good idea to switch to just a two-tier system (with `develop` and `production` branches).

This change would involve:

- updating documentation
- removing unused steps in CircleCI

**Comment by jseppi** [comment]
This is mainly a question for Kelly, I think.

**Comment by jseppi** [comment]
This is mainly a question for @KellyBailey. Do we/you still want a `staging` environment?

**Comment by toolness** [comment]
@jseppi is there anything we can do in lieu of a definitive answer from @KellyBailey on this?  like could we have a PR ready with checkbox items for things to do on cloud.gov, so we know exactly what needs to be done if he eventually gives the 👍 after you bust out?

**Comment by jseppi** [comment]
Sure. I'll start one!
