### ISSUE TITLE
Use uswds_forms for more things

### ISSUE THREAD

**Issue by toolness** [18F/calc#1646]
From #1640:

- [ ] Consider getting rid of some of our CSS that makes Django's default classes--`errorlist`, `helptext`, etc--look like USWDS. (This is because django-uswds-forms is able to tell Django 1.11 to use the official USWDS classes instead.)
- [ ] Consider replacing our custom `{% fieldset %}` template tag with [`{% fieldset %}` from uswds-forms](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#fieldset).
- [ ] Consider using [`uswds_forms.UswdsForm`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsForm) and/or [`uswds_forms.UswdsErrorList`](http://django-uswds-forms.readthedocs.io/en/latest/reference.html#uswds_forms.UswdsErrorList), if they'd simplify our codebase.

Note that a wrinkle in all this is the fact that our version of uswds doesn't seem to be prefixed with `usa-`, which breaks some of uswds_forms' assumptions.

**Comment by hbillings** [comment]
Discussion of the wrinkle in #1657

**Comment by toolness** [comment]
@hbillings let me know if you want to pair on this!

**Comment by hbillings** [comment]
Moved to this sprint because it goes hand-in-hand with #1840
