### ISSUE TITLE
Possible certificate bug? 

### ISSUE THREAD

**Issue by brethauer** [18F/calc#167]
Screenshot sent in by a DoD user, on IE9

![image](https://cloud.githubusercontent.com/assets/7635133/7886073/7dd98d5c-05f5-11e5-8a42-7214aef48cb1.png)

**Comment by brethauer** [comment]
@jroo @theresaanna  The person who reported it said she is getting errors for both Discovery and CALC... so would this indicate it's something on her network side I would assume?

**Comment by theresaanna** [comment]
@jroo Any other thoughts? If not, I think I might ask the devops folks what they think.

**Comment by borromeotlhs** [comment]
This should probably be a bug reported through the users network admins. Most likely the certificate chain of trust isn't correct or just isn't installed properly on their network.  Besides that, the certificate isn't handled by either of those pieces of software, right?

**Comment by jseppi** [comment]
Closing this because it is appears to be something wrong with the user's network. New Relic monitoring also validates the cert and is reporting that everything is hunky dory.
