### ISSUE TITLE
Price List Upload - date parts don't fit into date input widgets 

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1696]
I think this happened as part of the move to WDS (#1672)

<img width="390" alt="screen shot 2018-04-03 at 11 22 00 am" src="https://user-images.githubusercontent.com/697848/38261986-80ca215a-3731-11e8-9973-6f2d2e0df708.png">

**Comment by jseppi** [comment]
more easily visible in the style guide: https://calc-dev.app.cloud.gov/styleguide/#dates

**Comment by hbillings** [comment]
whyyyyyy I thought I fixed this already (thanks for catching it again)
