### ISSUE TITLE
Alert messages should be displayed with a consistent style throughout the user experience

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1697]
We've given some design attention to error alerts, but haven't addressed styling for alerts overall. Let's.

**Comment by ericronne** [comment]
Note discussion in #1689

**Comment by ericronne** [comment]
Let's inherit as much of the [USWDS alert styling](https://designsystem.digital.gov/components/alerts/) as is possible without clashing with the CALC styling …

![calc alerts](https://user-images.githubusercontent.com/9259185/39382110-20772b70-4a2a-11e8-9381-2e662e1c205e.png)

**Comment by toolness** [comment]
I'm moving this issue out of this sprint as we discussed (I think?) on Slack, but feel free to change it back if you disagree...

**Comment by ericronne** [comment]
Totally. They're already documented in their current form in the style guide, so that meets the criteria for this sprint. If we have extra time at the end of the sprint, we can look at updating the style then.
