### ISSUE TITLE
Icon credits are no longer needed (provided Kelly approves the header redo)

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1716]
- [x] Get Kelly's 👌 on the header redesign, in particular the intro paragraph which replaces the current set of "icon bulleted" text …
![image](https://user-images.githubusercontent.com/9259185/38378716-29c0b01a-38c4-11e8-9925-27755efd5092.png)

- [x] Delete the icon credits from the about page …
![image](https://user-images.githubusercontent.com/9259185/38378746-442a4c36-38c4-11e8-8224-f11ad8c15273.png)

**Comment by KellyBailey** [comment]
I like it. Let's go with it.

Kelly Bailey,MBA,PMP

Technical Product Manager,

CALC.GSA.GOV

Office of Professional Services

and Human Capital Categories(PSHC)

Federal Acquisition Service (FAS)

U.S. General Services Administration (GSA)

Phone: 253-347-9702

**Comment by jseppi** [comment]
credits were removed in https://github.com/18F/calc/pull/1730. All done!
