### ISSUE TITLE
Design Assets

### ISSUE THREAD

**Issue by maya** [18F/calc#172]
This is a living issue to keep all of our design assets in one place
## Sprint 11
- [slider](https://cloud.githubusercontent.com/assets/5249443/8146757/a141a2b4-11ff-11e5-912d-a9fd53a89987.png)
- [ideas all together](https://cloud.githubusercontent.com/assets/5249443/8125648/4e60f842-109c-11e5-9a65-e4c900c345bf.jpg)
## Sprint 10
- [toggle line](https://cloud.githubusercontent.com/assets/5249443/8051651/0a2eb548-0e34-11e5-992d-53e852c0204b.jpg)
- [toggle button](https://cloud.githubusercontent.com/assets/5249443/8051652/0a300f60-0e34-11e5-81c6-3ed893b9e277.jpg)
- [standard deviation](https://cloud.githubusercontent.com/assets/5249443/8051435/19ca942a-0e31-11e5-8a94-adb709cf3f3e.jpg)
- [price callout simple](https://cloud.githubusercontent.com/assets/5249443/8051125/4e1f3f18-0e2d-11e5-93c1-4c493b38f0e5.png)
- [price callout bullets](https://cloud.githubusercontent.com/assets/5249443/8051123/4e1b8864-0e2d-11e5-9167-f4b43744ed98.png)
- [price callout gray bg](https://cloud.githubusercontent.com/assets/5249443/8051124/4e1f33d8-0e2d-11e5-87cf-38044ce88287.png)
- [price callout header](https://cloud.githubusercontent.com/assets/5249443/8051042/07ce0356-0e2c-11e5-9c81-1a6520383e6c.jpg)
- [checkbox filter](https://cloud.githubusercontent.com/assets/5249443/8045806/df439ffe-0dea-11e5-9f6f-a3d4773de719.png)
- [sketch from design studio #2 - histogram redesign](https://cloud.githubusercontent.com/assets/5249443/8045875/7eb2b55c-0deb-11e5-890f-8ee1a59c1e17.jpg)
- [sketch from design studio #1 - clarify prices](https://cloud.githubusercontent.com/assets/5249443/8045942/ee68fb5e-0deb-11e5-9909-f185a5b463d0.JPG)
## Sprint 9
- [buttons blue](https://cloud.githubusercontent.com/assets/5249443/8046014/7918a588-0dec-11e5-9d1e-e4f4e759a2e8.jpg)
- [buttons gray](https://cloud.githubusercontent.com/assets/5249443/8046012/7915fce8-0dec-11e5-86dc-d34a1d9582fd.jpg)
- [buttons slim](https://cloud.githubusercontent.com/assets/5249443/8046013/7916841a-0dec-11e5-951d-c543ca7b0e1a.jpg)
- [buttons slim 2](https://cloud.githubusercontent.com/assets/5249443/8046015/7918d332-0dec-11e5-8a7b-8d8be99beb15.jpg)
## Sprint 8
- [sample link](#)
- [sample link](#)

...

**Comment by maya** [comment]
This is where I'll add all the design files that I'll link to above:

![checkbox](https://cloud.githubusercontent.com/assets/5249443/8045806/df439ffe-0dea-11e5-9f6f-a3d4773de719.png)

**Comment by ericronne** [comment]
OBE: A lot of these styles have been updated
