### ISSUE TITLE
Ensure new focus styles meet 508 compliance

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1720]
These seem pretty light to me, even on my nice Mac screen. We should check them to see if they're 508 compliant.
<img width="505" alt="screen shot 2018-04-05 at 6 45 41 pm" src="https://user-images.githubusercontent.com/509309/38398534-a551c7f4-3901-11e8-9764-aa341fa849b4.png">

**Comment by ericronne** [comment]
#1740 covers 👍
