### ISSUE TITLE
Discuss whether a login utility should be added to the header

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1735]
To log in, authorized users currently have to scroll all of the way to the bottom of the very-long home page. Should we duplicate this function in the header (where it's often found on websites)?

Adding it there would increase its visibility, which could be good (and/) or bad. Let's discuss, and then possibly consider a test.

Already implemented in the `er-header-login` branch (see #1701)

**Comment by jseppi** [comment]
What would you like to find out in such a user test?

**Comment by ericronne** [comment]
At a basic level, whether people easily find it an log in. (Little doubt they will.)

But i'm curious to know what reactions people have to this call to action:
![image](https://user-images.githubusercontent.com/9259185/38579958-41477a80-3cce-11e8-8fa7-05725fa97b19.png)

Will it confuse people? Pique their interest? Make them realize that CALC is "crowd sourced"? Make them jealous since they probably don't have the right to log in? e.g.

@tram thoughts?
