### ISSUE TITLE
Card bottom border gets funky

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1741]
UGH WHY.
<img width="1084" alt="screen shot 2018-04-10 at 12 31 23 pm" src="https://user-images.githubusercontent.com/509309/38576337-15a82054-3cbb-11e8-99f7-86c77e79265c.png">

**Comment by jseppi** [comment]
Not totally sure where you're seeing this, but it might be because of a `:last-child` pseudo-class that is hitting `div.card__footer` instead of `div.card`. I ran into something similar yesterday while I was reviewing #1702.

**Comment by hbillings** [comment]
WHY WHY IS THE CARD FOOTER OUTSIDE THE MAIN ELEMENT augh
