### ISSUE TITLE
Stop using api.data.gov as the primary API endpoint for CALC

### ISSUE THREAD

**Issue by toolness** [18F/calc#1747]
We discussed this recently on a call but I don't think we have an issue for it, so I thought I'd add one here.

Currently, on production/staging/development ~~(but not staging or development)~~ we restrict the IP addresses of clients of `/api/` to the [API Umbrella](https://apiumbrella.io/) instance at [api.data.gov](https://api.data.gov/).  This, in turn, proxies everything at `/gsa/calc/` through to the production instance's `/api/` path.  However, we don't do this on local dev instances.

I _think_ this was originally done so that api.data.gov could take care of things like API keys, rate limiting, and analytics without CALC having to worry about it.  However, in practice, we don't use API keys and haven't had to care about rate limiting.  And the analytics could, I think, just as easily be ensured by simply ensuring that all API requests are logged, which would then ensure that they're in our ELK stack at [logs.fr.cloud.gov](https://logs.fr.cloud.gov), where all our other logging data is (in fact, this may already be the case).

There's a number of drawbacks to this strategy:

* It complicates the code and documentation.  For example, we've got an [`API_HOST` constant](https://calc.gsa.gov/docs/api.html#access-from-calc-front-end-code) in the front-end code which needs to be documented and understood by anyone who on-boards to CALC.  Additional tests need to be written which take the proxying into account, and there are even outstanding issues (like #1692 and #1694) that exist because of this setup and haven't yet been resolved.

* It massively deviates from [dev/prod parity](https://12factor.net/dev-prod-parity).  Because the proxy only operates on the production/staging/dev instances~~, we can't even see if bugs exist on staging, to say nothing of our development systems~~. This means that bugs are very easy to creep in and go unnoticed; see e.g. #1692 and #1694, which have probably been around for years but we've only just noticed them recently.

* For the above complications, it doesn't seem to provide much benefit. As mentioned earlier, we don't currently need rate limiting or API keys, and the analytics could be done via our ELK stack.  It could potentially be argued that migrating away from api.data.gov would _simplify_ how we do analytics while also making our analytics more powerful: API Umbrella doesn't seem to offer very advanced (or even particularly user-friendly) analytics functionality, while Kibana offers all kinds of ways to analyze/visualize data.

Given all this, it might behoove us to migrate away from api.data.gov and just have production/staging/dev CALC access its API at `/api/`~~, just like dev and staging do~~.

**Comment by jseppi** [comment]
I'm 👍 to this. 

One minor correction: `staging` and `dev` (but not local develop instances) _are proxied_ through api.data.gov as well.

**Comment by toolness** [comment]
I think as a prerequisite for this, we should make sure that it's possible to create similar analytics in Kibana that we're already getting through api.data.gov.  I suspect we should already be able to do this, since the API requests are ultimately still coming to our server, the IP address will just always be the same API umbrella instance rather than the end-user's actual IP.

**Comment by toolness** [comment]
@jseppi do you think we're ready to close this one now?

**Comment by jseppi** [comment]
Yup!

Closed by #1766.
