### ISSUE TITLE
Rethink education filter

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1753]
The CALC API supports either returning only the rates that match the selected education level, _or_ returning rates that match the selected education level and up.

The UI works in the former matter, only returning rates that match exactly the education level selected. However, this is unclear in the UI and can be a little weird: if the user selects both "Associates" and "Ph.D," they will get back only rates that match one or the other. The display of the selected levels is kind of weird, and the dropdown-with-checkboxes is an odd pattern.
<img width="200" alt="screen shot 2018-04-12 at 1 34 42 pm" src="https://user-images.githubusercontent.com/509309/38699781-42e8727a-3e56-11e8-93f3-8bd1109ba323.png">

Consider changing this dropdown to min/max ranges, a la real estate search utilities:
<img width="321" alt="screen shot 2018-04-12 at 1 36 24 pm" src="https://user-images.githubusercontent.com/509309/38699861-84c05e06-3e56-11e8-88e6-426221aa22f5.png">

**Comment by ericronne** [comment]
@KellyBailey could i impose upon you to reiterate the explanation you verbally gave yesterday, of why a user might want to conduct a "split" search for "Associates" and "PhD," eg? Thanks!

**Comment by ericronne** [comment]
Here's a simple radio-button design, which returns results for the selected education level _and higher_. With the current checkbox design, calc returns only results which exactly match the selected level(s). A switch to radio buttons means that only one option can be chosen, though, so this design also includes any higher education level in the results, too. This parallels my proposed design change to the [experience widget](https://github.com/18f/calc/issues/1754).

@KellyBailey do you think this would meet user needs?

@hbillings @tram thoughts?

![image](https://user-images.githubusercontent.com/9259185/45175701-a8064880-b1d3-11e8-95ac-6c86e55fb2be.png)

**Comment by ericronne** [comment]
God willing and the creek don't rise — and there's a team to tackle it — it shall come to pass: #2147
