### ISSUE TITLE
Rethink experience filter

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1754]
The library we're using for the experience slider is *huge.* The experience slider itself is not necessary -- the min-max dropdowns available do the same job. We've talked before about doing user testing to see if 5-year buckets would be sufficient, instead of giving folks the granularity seen currently (does anyone need to search for someone with exactly 22 years experience? we don't know).

We could combine this with #1753 to come up with a standard pattern for optional min/max filters.

**Comment by toolness** [comment]
> does anyone need to search for someone with exactly 22 years experience? we don't know

Actually we DO know!

Sort of... Remember the [API log analysis](https://github.com/18F/calc-analysis/blob/master/log-analysis/log-analysis.ipynb) I did back at the end of 2016?  The data is a bit old, but I suspect the stats are still similar:

**Distribution of minimum experience**

![download](https://user-images.githubusercontent.com/124687/38702287-391854f0-3e6e-11e8-8a10-1e4ee55726e6.png)

Vertical axis is number of requests, horizontal is the minimum experience setting.

**Comment by hbillings** [comment]
AHA! I had that graph in my head, but couldn't remember where it was from!

So based on this, maybe it would be helpful to offer single years through 10 years, 2-year increments through 15, and 5-year increments after that.

**Comment by ericronne** [comment]
I get that they search for numbers greater than 15; **but** my question is how many contracts refer to such a high level of experience? If i wanted to find examples for 25 years of experience and searched `15+`, would the results be manageable, or a slew?

**Comment by ericronne** [comment]
So it is written, so shall it be done.
Provided there is a team to do it. ✊
#2147
