### ISSUE TITLE
Explorer search box improvements

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1759]
The data explorer search tool has a couple quick-fix issues
![image.png](https://images.zenhubusercontent.com/555b449c4f7a08fbb7f2de17/b0a1c2cf-b5e5-446e-ad4a-34316ae6c8f6)

- [x] Add "Search labor rates" as a label above the text field as an `h2`, to make for a high-profile visual anchor
- [ ] ~Change the prompt text to read: "Separate multiple terms with commas (Engineer, Analyst, etc.)"~
- [x] "Clear search" is misleading, because the button also resets filters, etc. Change to: "Reset"
- [ ] Fix the radio-button formatting so they don't run together

**It should look kinda like this:**
![image.png](https://images.zenhubusercontent.com/555b449c4f7a08fbb7f2de17/7c8d5350-45a9-4729-b7df-10fdfeea8353)

**Comment by hbillings** [comment]
Why did we decide against the prompt language change?

**Comment by tram** [comment]
:shrug: Just added it into this week's design studio. Any rejiggering of elements may (will likely?) change the descriptive text.

**Comment by ericronne** [comment]
Wait, added what? We can make this match the test plan. I preserved partly in the interest of changing as little as possible as we move into a research phase which will likely involve dramatic changes, and partly to err on the side of instruction clarity. (Keeping two instructional lines, rather than killing one.)
