### ISSUE TITLE
Design: chart callouts (avg, standard deviation, proposed $)

### ISSUE THREAD

**Issue by brethauer** [18F/calc#176]
![image](https://cloud.githubusercontent.com/assets/7635133/8166884/9a9a5c7a-1368-11e5-91ad-da76ecdd1d98.png)

**Comment by brethauer** [comment]
This is a test of how we can use GH issues for design discussions.

**Comment by brethauer** [comment]
How can we differentiate the average from the standard deviation?  They run together a little / have equal weight.  Sort of same w/ proposed price.  Almost makes we wonder if in-chart labeling is the way to go if our callouts are getting too complicated?

**Comment by maya** [comment]
We can try different font sizes like this: 
![standard deviation mockup](https://cloud.githubusercontent.com/assets/5249443/8167150/2cce3cb4-1351-11e5-857d-fc73111caa7a.jpg)

**Comment by maya** [comment]
I think this is a good thing to A/B test @brethauer, but if you need any other versions before, let me know!
