### ISSUE TITLE
Design: price callouts

### ISSUE THREAD

**Issue by maya** [18F/calc#177]
Here are a few versions of the price callouts. 

**Here was the problem**: People using the tool, assumed that the prices were the base hourly rates for professional services (lower) and we want to clarify that they are ceiling rates (higher with other things included).

We think that bringing out these four things will help achieve this:
- Ceiling prices 
- Fully burdened
- Professional services
- Worldwide rates

**Before**:

Previously we had these items below the graph in two sentences with grayed out text.

![price callout before](https://cloud.githubusercontent.com/assets/5249443/8167805/80da2cb0-1355-11e5-86aa-4ce7f0cf8e40.png)

**New mockups**:

In the header with icons:

![price callout mockup](https://cloud.githubusercontent.com/assets/5249443/8167777/566b0102-1355-11e5-9122-3d5dfcf53c6c.jpg)

Below the graph, more subtle:

![price callout bullets](https://cloud.githubusercontent.com/assets/5249443/8167775/564cdad8-1355-11e5-8a77-9f5eb00b4ac8.png)
![price callout gray bg](https://cloud.githubusercontent.com/assets/5249443/8167776/565d5584-1355-11e5-837d-4e3398ecb2ff.png)

**Comment by brethauer** [comment]
Per our conversation today, we're moving forward with #1 (icons in header).  @maya will implement
