### ISSUE TITLE
Verify that we can extract the same analytics from Kibana that we can from api.data.gov

### ISSUE THREAD

**Issue by jseppi** [18F/calc#1773]
From https://github.com/18F/calc/issues/1747#issuecomment-380946859:

> ...we should make sure that it's possible to create similar analytics in Kibana that we're already getting through api.data.gov. I suspect we should already be able to do this, since the API requests are ultimately still coming to our server, the IP address will just always be the same API umbrella instance rather than the end-user's actual IP.

**Comment by jseppi** [comment]
We can get the same types of counts in kibana with queries like:

```
rtr.path:/api/rates AND @cf.app:calc-prod
```

example:

<img width="1223" alt="screen shot 2018-04-16 at 9 51 33 am" src="https://user-images.githubusercontent.com/697848/38816474-c75f309a-415b-11e8-958b-f74f68e754e1.png">

**Comment by jseppi** [comment]
@toolness: anything else you were thinking about for validating the analytics?

**Comment by toolness** [comment]
Nice! 

The api.data.gov analytics also give us access to the raw logs but they're _really_ hard to find through the UI.  But they're what I used to do my [log analysis](https://github.com/18F/calc-analysis/blob/master/log-analysis/log-analysis.ipynb).   That said, the `@message` in the screenshot can be used to get the same information, I think.

**Comment by jseppi** [comment]
Cool, then I will close this and merge #1766!
