### ISSUE TITLE
"Trigger JavaScript Error" button in styleguide seems very green

### ISSUE THREAD

**Issue by toolness** [18F/calc#1791]
At the very bottom of the guide:

> ![trigger-js-error](https://user-images.githubusercontent.com/124687/38890798-6e079f78-4250-11e8-913b-558b87351725.png)

On [production](https://calc.gsa.gov/styleguide/#compatibility-mode) it appears to be red.

**Comment by hbillings** [comment]
I wonder if this has to do with the color variable work @ericronne's been doing? Maybe we need to revisit the colors of primary/secondary buttons?

**Comment by ericronne** [comment]
I'm sure that's the reason. Yes i need to do a global look at how the primary and secondary colors are applied. Issuing it…

Will likely need a 🍐

**Comment by ericronne** [comment]
Will be closed by #1916
