### ISSUE TITLE
Validate that sortable table HTML is still correct

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1796]
Rows within the main page sortable table define a `th` for each row. I _think_ this is an accessibility thing (or was one at one point) but it's funky and I'd like to verify it's still valid.

**Comment by jseppi** [comment]
Yeah, `th scope="row"` is good for accessibility: https://www.w3.org/WAI/tutorials/tables/two-headers/

It looks like our main page table is using it properly.

**Comment by ericronne** [comment]
Resolved then, @hbillings?
