### ISSUE TITLE
Add guidelines for enabling local linting for IDEs/editors on the host system

### ISSUE THREAD

**Issue by toolness** [18F/calc#1799]
It'd be nice to document our general strategy for using IDEs and text editors with CALC.  Typically this is done by installing a virtualenv and/or npm on the host machine and installing the python and/or node dependencies on the host system, so that local editors can offer syntax completion and such.

However, this strategy isn't well-known, and it's also error-prone.  For instance, right now I've created a virtualenv called `venv` in the root directory of CALC.  This works fine with VS Code, which is able to detect the virtual environment, but unfortunately `pytest` and other tools go digging into it when looking for files to test/lint/etc, which completely messes up the development workflow.  I guess one solution to this might be to put the virtualenv outside of the CALC root directory, but all of this back-and-forth gets cumbersome and it'd be nice if we could document some editor-agnostic best practices for folks.

**Comment by jseppi** [comment]
Yeah, good idea! I do something similar but use `pyenv` to manage and activate my virtualenv, and then launch vscode from the same terminal with the activated env.

**Comment by toolness** [comment]
ah cool, `pyenv` makes the virtualenv outside of the CALC repo, right?  That is spiffy.

**Comment by jseppi** [comment]
Yep!
I think I recall vscode working well with pipenv as well.

**Comment by toolness** [comment]
Additional note: running `yarn install --ignore-engines` will work around e.g. having node 8.x on your host system, even though our `package.json` currently wants 6.x.
