### ISSUE TITLE
Document less-than-ideal aspects of existing CALC data

### ISSUE THREAD

**Issue by toolness** [18F/calc#1829]
e.g.:

* That some data has no education or experience metadata

* That some labor categories are duplicated multiple times w/ differing fields (education, sin number, etc) - see #1021, #1029

* That some data is anomalous (e.g. the $700 Teleprompter Operator) - see #1432

* ~~The `sin` field is messed up - see #1033~~ Addressed this in #1850.

* Depending on when the data was updated, the "current price" column may not actually be accurate - see #545.

**Comment by toolness** [comment]
Hmm, I'm not sure where this documentation should actually _live_.  One possibility is to actually add a view that reports all the less-than-ideal aspects, e.g. shows a list of all duplicate rows, super expensive teleprompter operators, and so forth.  This could be used by data administrators to clean up the data sources if they want.

Otherwise, I'm a bit fearful of documenting these things anywhere in the actual codebase, simply because the problem isn't really with the codebase--it's with the data in the db.

Thoughts @hbillings?

**Comment by hbillings** [comment]
I almost feel like we need to sketch out a documentation architecture plan at this point. We've got technical docs and style docs, but we don't really have anything like procedural docs that I'm aware of. (I'm thinking about things like documenting how to add a new schedule to the app, gotchas with working with the Django admin, and stuff like this, for instance.)

At the same time, I don't want to get into documentation bloat...but if we face the potential of not overlapping with the team that picks this up, it seems like we're going to need to err on the side of more hand-holding. To me that's where data quality issues would come in. What do you think?

**Comment by hbillings** [comment]
Also, `The $700 Teleprompter Operator` is my next band name.
