### ISSUE TITLE
Create designs for responsive CSS

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1841]
In #1644, we agreed that responsive design for the data explorer would be helpful.

This is blocked until we do more of the testing/heuristic modifications of the data explorer.

**Comment by toolness** [comment]
Regarding the table--and assuming we keep the table--Lea Verou just wrote a blog post called [Responsive tables, revisited](http://lea.verou.me/2018/05/responsive-tables-revisited/) which may be helpful.

**Comment by ericronne** [comment]
Here are mobile designs. Will break out some elements into separate issues. The table design is based on the "Tablesaw" [swipe table](http://filamentgroup.github.io/tablesaw/demo/swipe.html) and [toggle](http://filamentgroup.github.io/tablesaw/demo/toggle.html) features.

## Home
![image](https://user-images.githubusercontent.com/9259185/45976355-294f3f00-c00c-11e8-820e-862409109d92.png)


## Sub page (About)
![image](https://user-images.githubusercontent.com/9259185/45976396-3e2bd280-c00c-11e8-9cd5-22be1c82f9a2.png)
