### ISSUE TITLE
Refine design for admin section

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1854]

**Comment by tbaxter-18f** [comment]
I wonder if we should do _less_ in the admin section, and better leverage what's already in the Django admin with a light skinning. Currently we're breaking a fair bit of free functionality Django gives you, and I wonder how much efforts in the admin subtract from efforts elsewhere. I understand I may be missing some key context on why the decision was made to completely reskin the the admin, but I do wonder if it's really worth it.

**Comment by ericronne** [comment]
Want to pair and walk me through these freebies we're missing?
