### ISSUE TITLE
Style the style guide

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1858]
## An "issue thread" to discuss style guide visual development

**Comment by ericronne** [comment]
@toolness / @hbillings are we able to dynamically add info such as the "font stack" specs seen here without too much pain? I'm loath to hard code such things, since they might go stale …

![image](https://user-images.githubusercontent.com/9259185/39654862-70cf9d0e-4fbc-11e8-952c-f6007255ecb8.png)

**Comment by ericronne** [comment]
Thoughts on this style for code?

![image](https://user-images.githubusercontent.com/9259185/39656275-4393f1f2-4fc4-11e8-8671-ad35e24a410d.png)

**Comment by hbillings** [comment]
Is this issue different from #1848?

**Comment by ericronne** [comment]
I read the other issue as implementation, and created this to be a running "visual reference" / list of the components as i design them. Sorry for the confusion. If it's easier for you, i can use that issue. Yercall

**Comment by toolness** [comment]
Er, just FYI, changing the colors of the code might not be super easy--we're using a third-party library that does syntax highlighting. I know changing the color scheme is _possible_ but it might not necessarily be easy. And there may be colors that we need that aren't on your screenshot (e.g. colors used for `<!-- html comments -->` etc).

**Comment by ericronne** [comment]
Oh interesting. Is there a reference where i can see what else it does?

**Comment by toolness** [comment]
Yup, I think we are using [Prism.js](http://prismjs.com/) for our syntax highlighting needs.

**Comment by hbillings** [comment]
I guess I like it when issues can be closed by pull requests, and I've got a PR open to close #1848. But I don't really want to shoehorn all this in there. Maybe it would actually be better to have separate pull requests for each component?

Also, can you say more about dynamically adding the font stack specs? What would it generate those from, in your perfect world?

**Comment by ericronne** [comment]
Looks like `default` is the current theme. "Punctuation" such as brackets doesn't contrast sufficiently to meet 508 guidelines, but the only ones that seem to make the cut are over dark backgrounds (`Funky` (which is very jarring) and `Tomorrow Night`). I'm inclined to leave as is for now. If we fold up the code into a tab, eg, that _might_ make it a little less of an issue.

**Comment by ericronne** [comment]
Multiple PRs is wiser, i'm sure. Can we do a hangout to suss?

**Comment by ericronne** [comment]
I need to know the constraints of the design, so i can be sure that my design can be implemented more easily.

I have no idea how the style guide is generated.

**Comment by hbillings** [comment]
Sure!

I mean, what does "dynamically generated" look like? It seems like you mean "not hardcoded," but I don't know what you'd want the canonical reference for typography to be?

**Comment by ericronne** [comment]
@toolness could i simply tweak the values in this file? …

![image](https://user-images.githubusercontent.com/9259185/39717464-efc03306-51f8-11e8-9fe1-6ae936be693e.png)

**Comment by ericronne** [comment]
splitting out into sep issues
