### ISSUE TITLE
Figure out how to show focus states in the style guide

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1886]
Focus states are referenced in the style guide, but the example which [perports to show one](https://calc.gsa.gov/styleguide/#forms) (without requiring the user to click in the field) isn't working.

The fastest fix here may be to simply write text that prompts the user to click into a text box in order to see the focus state.

Related: #1740

**Comment by ericronne** [comment]
Okay this interactive approach requires no new styles. Cool?

![image](https://user-images.githubusercontent.com/9259185/39895218-0dab8fd2-546f-11e8-8219-f6edcaf6e664.png)

@hbillings @toolness

**Comment by toolness** [comment]
Hmm, are we in full control of the focus state CSS, or is some of it coming from USWDS?  If we're in full control of it, I think we could just add a `.styleguide-focus` to any CSS rule that mentions `:focus`, e.g.:

```css
:focus {
  outline: 10px solid pink;
}
```

would become

```css
:focus, .styleguide-focus {
  outline: 10px solid pink;
}
```

Then in the styleguide we could just add `.styleguide-focus` to anything that we want to appear focused.

Oh, I just looked and this is actually the technique the USWDS uses for its own style guide, e.g. its [buttons documentation](https://designsystem.digital.gov/components/buttons/):

> ![usa-focus](https://user-images.githubusercontent.com/124687/40056350-22248dc6-5819-11e8-9a15-ef7801a8c98f.png)

They have a `.usa-focus` class that is probably only really intended for use in their styleguide.

For that matter, the USWDS also has aliases for their hover and active states too, so if we wanted, we could make those and show the hover and active states on our styleguide too, without requiring the user to interact with the page.

**Comment by ericronne** [comment]
Sounds good if it works. FEDesigner req'd

**Comment by hbillings** [comment]
yep, this is how we should be doing it.
