### ISSUE TITLE
As a data administrator, I want the Schedule title in the data explorer to be changed to Schedule / Contract Vehicle

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#1929]

**Comment by toolness** [comment]
So there are multiple places in the data explorer where the word "Schedule" appears.

One is in the dropdown filter:

> ![dropdown](https://user-images.githubusercontent.com/124687/40841421-5eaf0606-6578-11e8-9858-43d8c0c2f6e5.png)

Another is in the data table:

> ![table](https://user-images.githubusercontent.com/124687/40841426-67c7bdd2-6578-11e8-902f-e21071693343.png)

Should both of these change, or just one?

Also, in the about page--accessed directly by clicking the "What's this?" link near the filter--there's a heading titled "What are these schedules?".  Not sure if we should change it to "What are these schedules and contract vehicles?" or something else.

**Comment by tram** [comment]
Are all schedules contract vehicles?

**Comment by hbillings** [comment]
Kelly said we can totes just call these "Contract vehicles", which will make labelling stuff easier!
