### ISSUE TITLE
Review the diversity of bulk upload data

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1933]

**Comment by ericronne** [comment]
[Sample Region 6 pricing data](https://docs.google.com/spreadsheets/d/1yfER4j5AA-FK-z5qvP3DVQWn0rMBud5wM2uRoTswYSU/edit?usp=sharing)

**Comment by KellyBailey** [comment]
**R2**- https://docs.google.com/spreadsheets/d/1gIagIG8PgNh2V4KlsVu26qzNDhZ7z7c1G78fb4vx2jg/edit?usp=sharing
**R3-** [71 IIK Awarded Pricing Tool (4-16-18) (2).xlsx](https://github.com/18F/calc/files/2017719/71.IIK.Awarded.Pricing.Tool.4-16-18.2.xlsx)
**R6-**https://docs.google.com/spreadsheets/d/1yfER4j5AA-FK-z5qvP3DVQWn0rMBud5wM2uRoTswYSU/edit?usp=sharing
**OASIS PP-**
[Oasis Prices Paid.xlsx](https://github.com/18F/calc/files/2017737/Oasis.Prices.Paid.xlsx)
**PSS TDR-** 
[PSS TDR Data Scrubbed.xlsx](https://github.com/18F/calc/files/2017746/PSS.TDR.Data.Scrubbed.xlsx)

**Comment by toolness** [comment]
Thanks Kelly!  For now I am documenting some observations about this data at this google doc:

https://docs.google.com/document/d/1VidlSon18FHcfXFCo_rD-Om7F3lX4Q5bQRBNFZv2RKM/edit#heading=h.y5mkdo3bg4jt
