### ISSUE TITLE
Identify work needed for Region 6 bulk upload

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1934]

**Comment by hbillings** [comment]
@KellyBailey to remind us where the latest R10 spreadsheet is so that we can work on the One Spreadsheet To Rule Them All.

**Comment by KellyBailey** [comment]
[R10 Bulk Upload Format.xlsx](https://github.com/18F/calc/files/2156233/R10.Bulk.Upload.Format.xlsx)

**Comment by KellyBailey** [comment]
https://docs.google.com/spreadsheets/d/1yfER4j5AA-FK-z5qvP3DVQWn0rMBud5wM2uRoTswYSU/edit?usp=sharing

**Comment by ericronne** [comment]
Blocked by research
