### ISSUE TITLE
Would it be useful to color visited links differently than un-visited ones?

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1945]
Traditionally, CALC has applied the same color to both visited and un-visited links, for a couple of reasons noted by @hbillings in [this conversation](https://github.com/18F/calc/pull/1936#discussion_r189444006).

#1944 preserves this, coloring all text links that run over white as `$color-blue` (#0770B5).

Even if we opt to keep this approach, the question might be worth researching (if only to be rock-solid in our choice to keep things as is).

Might users ever scan search results to find a contract which they've opened before? I can't think of any other instance where coloring a visited link differently might be of use. cc @tram

**Comment by hbillings** [comment]
we could also go ahead and add a rule for visited links in the results table! I can def see those being useful.

**Comment by ericronne** [comment]
I think that'd be killer. If you add the rule, i'll add the color back 🙌 

![image](https://user-images.githubusercontent.com/9259185/40333456-24e513aa-5d1e-11e8-8cac-21fe5b535729.png)

**Comment by tram** [comment]
During CALC II, we saw CO/CSs looking back at what contracts they'd visited before in the results table. Part of that _might've_ been an artifact of the observation, though likely not all of it. (We were often asking them to show us things they'd done before.) As the results table currently exists, it makes sense that we'd show them what contracts they've visited, but everywhere else, visited and unvisited links could be the same color.
