### ISSUE TITLE
Button active states are wonky

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1952]
need a hand.

![eolfad3r56](https://user-images.githubusercontent.com/9259185/40448838-4dbb1ebc-5e9c-11e8-970f-996d361ffdd3.gif)

**Comment by hbillings** [comment]
What branch is this on? I'm not seeing it on `develop`.

**Comment by hbillings** [comment]
HA, never mind, I wasn't actually on `develop`. 🤦‍♀️
