### ISSUE TITLE
Generated sentence should say "Bachelors" and "Masters" instead of BA, MA

### ISSUE THREAD

**Issue by brethauer** [18F/calc#196]

**Comment by xtine** [comment]
I might need help on this because I spent a bit of time trying to figure out how the label template generation works in d3. Not sure if this is possible but another option is not to have the generated sentence display because it doesn't work for the new experience slider either.

**Comment by theresaanna** [comment]
I think it may rely on the API response, so I will dig into this and then let you know, @xtine, what I find.

**Comment by theresaanna** [comment]
@xtine I just messaged you in Slack about this. It looks like it is a JS change. I can understand why it wasn't obvious where the labels are coming from - its pretty complicated. I sent you a proposed solution.
