### ISSUE TITLE
Colors on data explorer are all over the place

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1967]
Buttons are dark blue, graph bars are base blue, I don't even know what colors the sliders/filters panel is picking up on its controls. @ericronne, you and I should pair on this.

<img width="942" alt="screen shot 2018-05-29 at 11 47 04 am" src="https://user-images.githubusercontent.com/509309/40683718-916876aa-634c-11e8-83a3-efe1c40a81b8.png">

**Comment by ericronne** [comment]
These were all fixed! Something went funky in a merge or something something. Doubtless mea culpa. _Researching…_
