### ISSUE TITLE
Education filter is keyboard accessible, but confusing

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1982]
It receives focus when tabbed to, opens when the user hits the return key, and options can be tabbed through once it is opened … but options can't be selected without clicking.

![image](https://user-images.githubusercontent.com/9259185/40795302-407216f8-64c7-11e8-87c6-5c91f2f16259.png)

Since this design approximates a pull-down selector, we may want to make it behave like one (i.e. use down arrow to open and highlight, return to select options.

**Comment by hbillings** [comment]
We could also just redesign the filters to not use bizarro patterns like this.

**Comment by ericronne** [comment]
https://github.com/18F/calc/issues/1753

**Comment by toolness** [comment]
Er, so these actually _are_ accessible, I think... the weird thing is that checkboxes are actually activated using <kbd>Spacebar</kbd> and not <kbd>Enter</kbd>, as the [WebAIM Keyboard Testing guide](https://webaim.org/techniques/keyboard/#testing) mentions.  I find this odd and confusing but it's apparently how things work.

**Comment by ericronne** [comment]
yeah that's cumbersome and inconsistent

<kbd>tab</kbd> to focus selector, hit <kbd>enter</kbd>, <kbd>tab</kbd> to desired option, <kbd>spacebar</kbd> to choose, repeat for all desired options
