### ISSUE TITLE
Radio buttons and checkboxes have odd spacing

### ISSUE THREAD

**Issue by ericronne** [18F/calc#1994]
Abstracting this problem from PR #1988, because it's a global issue.

See the thread [started here](https://github.com/18F/calc/pull/1988#issuecomment-393691183).

**Comment by hbillings** [comment]
We can't really merge #1988 in with the radios looking wonky, tho. :-/

**Comment by ericronne** [comment]
Have you seen calc.gsa.gov? :P 

Have at it, tho! 🙌
