### ISSUE TITLE
Document Web Components & usage

### ISSUE THREAD

**Issue by hbillings** [18F/calc#1998]
I can't find documentation about our web components in what's written so far, and it's sort of confusing because I think we must be using a polyfill based on the function names, but I'm not totally sure. Even just something brief in `frontend.md` about where we use web components and if we use polyfills or any conventions would be helpful!

**Comment by toolness** [comment]
Aagh yes, this needs to be done. Sorry, I should have done this before you started work on the web components!

**Comment by toolness** [comment]
Um, I changed my mind about my previous comment (see #2006) and given the garbage fire that appears to be the state of the custom elements spec, I think there's some good reasons for staying with V0 of the spec and, most importantly, **documenting that we're using V0**.
