### ISSUE TITLE
Add contract number and vendor search to CALC API

### ISSUE THREAD

**Issue by tram** [18F/calc#2000]
Do all of the plumbing bits.

**Comment by toolness** [comment]
So I've got questions about what kind of search to provide via the API.

For labor categories, we offer the choices "contains words", "contains phrase", and "exact match".

What kind of options do we want to provide for contract number and vendor name search?

For contract number, it seems like "exact match" is fine. It's hard to imagine someone wanting to e.g. search for all contracts that start with `GS-00F` or something, though I could be wrong.  I suppose that for the newer-style contract numbers, [characters in certain parts of the sequence actually mean specific things](https://federalnewsradio.com/management/2014/10/agencies-get-2017-deadline-to-move-to-new-procurement-id-standard/), but (A) we don't currently have evidence that folks would want to actually search based on contract number substrings and (B) much of that metadata is already reflected in other aspects of our existing data (for instance, the schedule name and contract start/end date).

Vendor name is a bit trickier.  I suspect it might be easiest for us to add an _exact_ match filter to our standard search endpoint, but also add a new autocomplete endpoint that will aid users in finding the exact name of a vendor, but I'm not sure.

**Comment by ericronne** [comment]
Would this use the explorer search box?

**Comment by toolness** [comment]
Well, the intent of this issue is to decouple the API from the actual user interface, since we'd prefer to be able to proceed with some of the plumbing without having to block on the design. However, upon further reflection it does seem like some of the specifics of the plumbing will ultimately depend on the design, alas.

I guess right now this means that we can definitely do the plumbing for the contract number search, but hold off on the vendor name search until further design work is done?

**Comment by ericronne** [comment]
If we have good reason to believe that users would find it all useful, we should go for it! Perhaps we can plumb and design in parallel. I may need a hangout to better understand your vision of a slack-like search.

**Comment by tbaxter-18f** [comment]
It may be best to meet up on this and get me up to speed, but here's some things I wonder about at first look...

As I understand it, there would be one search box that a user could put contract number OR vendor OR labor category in and the back end would expect to sort it out. Is that a correct assumption?

I know this is drifting into design, but do we expect to have any controls present to indicate which thing(s) you're searching? If not, are the results just munged together, so if I search for "Monkey" I may get results for the vendor "Monkey Trainers, Inc" and "Monkey training" as a labor category. 

And if that's the case, do we want to differentiate the results and note what sort of results they are?

And does one type of search take precedence? Like "First look at vendors, then labor categories" or something?

**Comment by hbillings** [comment]
I think @ericronne has some opinions here, but my understanding is:
- The search should default to searching by labor category.
- There would likely be a mechanism to specify vendor name or contract number -- Slack's and GitHub's sort of commands came up, though those might be a little too hidden.

I suppose another option is to steal the Google approach, highlighting whatever words in whatever cell matched your search, but that seems messy and potentially unhelpful.

Also, I would like more information about these monkey trainers you speak of... I could use a little more discipline in my life...

**Comment by tbaxter-18f** [comment]
Thanks Heather. I imagine @KellyBailey may have opinions, too.

Also: http://www.careers.org/occupations/16486/monkey-trainer
