### ISSUE TITLE
Design interface for vendor and contract number search

### ISSUE THREAD

**Issue by tram** [18F/calc#2001]
Adding to research plan.
Go through sketches to find previous ideas.

**Comment by ericronne** [comment]
Here's a [concept prototype](https://gsa.invisionapp.com/share/JTN1H0T8XRF#/309519149_Multisearch-Vehicle) which makes use of the search-box selector we're testing.

Related [writing lab issue](https://github.com/18F/writing-lab/issues/366) and [google doc](https://docs.google.com/document/d/1B9QqwVutPhYejwikk8_67XCQQfFeMZdNr1_ty_dXGfE/edit#), re labeling the selector.


![image](https://user-images.githubusercontent.com/9259185/42906997-35f720f0-8aa2-11e8-82f5-b4e253598a0f.png)

![image](https://user-images.githubusercontent.com/9259185/42907010-3f7db62a-8aa2-11e8-8aeb-1b1443d165d8.png)

![image](https://user-images.githubusercontent.com/9259185/42907023-47ad99d2-8aa2-11e8-8cd9-d8f62802eb96.png)

**Comment by hbillings** [comment]
Related technical PR: https://github.com/18F/calc/pull/2069

**Comment by ericronne** [comment]
Here's a reference reflecting the revised layout we're implementing, with selector moved out of the search bar …

![image](https://user-images.githubusercontent.com/9259185/44532854-bde71a00-a6b9-11e8-8da6-d411d0236d38.png)

![image](https://user-images.githubusercontent.com/9259185/44532861-c3dcfb00-a6b9-11e8-87af-87df302eaece.png)

![image](https://user-images.githubusercontent.com/9259185/44533044-3f3eac80-a6ba-11e8-803c-cb9c6202726c.png)
