### ISSUE TITLE
Update weekly log and security event review instructions to not use Gemnasium

### ISSUE THREAD

**Issue by toolness** [18F/calc#2020]
The [Weekly Log and Security Event Reviews](https://github.com/18F/calc/wiki/Weekly-Log-and-Security-Event-Reviews) mentions to use Gemnasium for ensuring that CALC doesn't have any out-of-date packages with security vulnerabilities and such, but we don't use Gemnasium anymore.

We should update these instructions to mention whatever tool we currently use (Snyk?).

**Comment by toolness** [comment]
Also, the instructions should mention what to Tock the time to, because it's different from the CALC development work that's done.

**Comment by hbillings** [comment]
Done!
