### ISSUE TITLE
Combine the contract ID and vendor name columns in the results table

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2034]
One of the table improvements we're tackling in #2024.
_note: eric is replacing the doc icon_

![image](https://user-images.githubusercontent.com/9259185/42186261-9e6977c0-7e11-11e8-9335-d9000076c57c.png)

- [x] Merge the two columns
- [ ] ~Color the contract ID text with `$color-gray-dark`~
- [x] Reduce the ID text to `$small-font-size`

**Comment by ericronne** [comment]
Here's [an icon](https://drive.google.com/open?id=1YE2xwzP_R5x3ij8zsKgtr3ADnyjkcva8) to try. Likely will revise.

![image](https://user-images.githubusercontent.com/9259185/42233475-4ec29d2c-7eb7-11e8-94bf-3cbc2a510a2e.png)

**Comment by ericronne** [comment]
@hbillings if this will be time consuming, we can split it out from the rest of the spike things. Don't want it to hold up testing.

**Comment by abrouilette** [comment]
Needs testing
