### ISSUE TITLE
Implement restyled results graph

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2035]
![image](https://user-images.githubusercontent.com/9259185/42472106-d2379158-8385-11e8-9725-e4c22dfea84a.png)

**Comment by ericronne** [comment]
- [ ] Fill bars w-light green
- [ ] Add a dark-green, two-pixel rule to the top of each bar (for accessibility)
- [ ] Delete bottom rule
- [ ] Simplify y-axis rule to two-pixels, gray
- [ ] Remove background fill from average and proposed prices, and restyle per image
- [ ] Update typography (incl. colors)

**Comment by hbillings** [comment]
We did already: https://github.com/18F/calc/issues/2038

**Comment by ericronne** [comment]
woo
