### ISSUE TITLE
Getting 504 (GATEWAY_TIMEOUT) when hitting main page

### ISSUE THREAD

**Issue by anthonygarvan** [18F/calc#204]
I am getting 504's when hitting the main page. This is likely an infrastructure issue, not problem with the code of this project. Do you implement IsAlive checkers or have automated tools / dashboards for maintaining the performance and status of your various apps?

Here's the output from the Chrome console:

GET https://calc.gsa.gov/static/hourglass_site/images/price-callout/breifcase.png 504 (GATEWAY_TIMEOUT)
jquery.min.js:4 

GET https://api.data.gov/gsa/calc/rates/?format=json&histogram=12&sort=current_…_type=match_all&min_experience=0&max_experience=45&experience_range=0%2C45 m.ajaxTransport.send @ jquery.min.js:4m.extend.ajax @ jquery.min.js:4hourglass.API.get @ hourglass.26f37116666f.js:65submit @ index.b3d15c1f3f38.js:223popstate @ index.b3d15c1f3f38.js:183initialize @ index.b3d15c1f3f38.js:117(anonymous function) @ index.b3d15c1f3f38.js:112(anonymous function) @ index.b3d15c1f3f38.js:1118
(index):1 

XMLHttpRequest cannot load https://api.data.gov/gsa/calc/rates/?format=json&histogram=12&sort=current_…_type=match_all&min_experience=0&max_experience=45&experience_range=0%2C45. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://calc.gsa.gov' is therefore not allowed access. The response had HTTP status code 504.
index.b3d15c1f3f38.js:265 

update: undefined  index.b3d15c1f3f38.js:883 

Uncaught TypeError: Cannot read property 'results' of undefined

**Comment by brethauer** [comment]
Thanks for the heads up @anthonygarvan !  Something appears to be askew on our instance, so we switched to another while we investigate.

**Comment by anthonygarvan** [comment]
Cool! I checked it out and it seems better now. +1 for quick response!

**Comment by theresaanna** [comment]
+1 on the thanks to @anthonygarvan! It looks as though the search didn't like some characters it was receiving. Great bug find!

**Comment by anthonygarvan** [comment]
Thanks! I know this is in beta, but it's still nice to have some performance monitoring set up to alert the team to issues, if you don't have this already. For example, [https://www.serverscheck.com/monitoring_software/application-monitoring.asp](serverscheck) offers free application monitoring.
