### ISSUE TITLE
main site doesn't link to the API docs

### ISSUE THREAD

**Issue by afeld** [18F/calc#2060]
Might be something (some) users will be interested in - I had to find [the API docs](https://calc.gsa.gov/api/docs/) through Google!

**Comment by tbaxter-18f** [comment]
@afeld Is the expectation that calc.gsa.gov would link to them, or that the github repo would have a clearer, more direct link to them?

**Comment by afeld** [comment]
I was thinking the site, but both I suppose!

**Comment by afeld** [comment]
*either or both

**Comment by abrouilette** [comment]
Ready to merge but there is a conflict in the Python code. @tadhg-ohiggins, in your court.

**Comment by tadhg-ohiggins** [comment]
Addressed by #2065.
