### ISSUE TITLE
Confirm that script tags entered in URL bar do not execute

### ISSUE THREAD

**Issue by hbillings** [18F/calc#2071]
We got a set of [automated scan results](https://drive.google.com/drive/folders/1qEHmWDZ2iFo98BUTiRywvhf8u65W-FMA) (private link) that suggest that CALC's querystrings might be susceptible to XSS. I think this was addressed in [#1060](https://github.com/18F/calc/pull/1060#issuecomment-262622392), but would like to confirm.

**Comment by tbaxter-18f** [comment]
I think it was partially addressed in #1060 but may have regressed. I think it should be fully addressed with #2061 and we can test it from that branch.
