### ISSUE TITLE
Fix wonky help text and buttons on Add Schedule Metadata pg in admin

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2072]
### I believe the small text here should have the `helptext` class applied, instead of `help`
![image](https://user-images.githubusercontent.com/9259185/43468301-39dfeb64-94a9-11e8-9b31-6b99a7b9bd6b.png)

### Buttons seem to have a size override which is throwing off the vertical type alignment, investigate
![image](https://user-images.githubusercontent.com/9259185/43468394-759a4bd6-94a9-11e8-93e7-460d9f6fd8ef.png)

**Comment by hbillings** [comment]
Blergh, these are Django pages and this wonkiness is likely due to those styles inheriting their own crappy CSS.

**Comment by tbaxter-18f** [comment]
I never did get around to giving that tour of the Django admin (still could) but I remain fairly convinced a fully custom admin ain't worth the effort.
