### ISSUE TITLE
Price list analysis: process errors before serving up the analysis page

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2077]
On the [price list analysis](https://github.com/18F/calc/pull/997) spike, the error review and analysis report are combined onto a single page. This makes for an odd layout, and also prevents users from getting any reasonableness-related feedback about rows which may simply have an error-causing typo.

If there's no special reason it was built in that way, i think it would be better to split out these two functions, like we do in the data capture process.
 1. Perform the error check and let the user deal with any errors, then
 2. Display the analysis on its own page …

![image](https://user-images.githubusercontent.com/9259185/43665066-983fc96c-9734-11e8-934c-5bf18ad5385f.png)

Error page from data capture, for reference …
![image](https://user-images.githubusercontent.com/9259185/43665227-2871c01c-9735-11e8-8420-1efe7468d9ae.png)

**Comment by ericronne** [comment]
@hbillings posited the notion of removing the error-checking step from analysis altogether, and integrating the display of any errors with the analysis results table itself. 

Does that approach require less work than separating them into two pages, like we do with add data?

With that approach, would we analyze a row as long its errors weren't in the labor category, education, or experience field?

If there *were* errors in one of those three fields, would we offer the option for them to fix and re-upload the file on that page?

**Comment by abrouilette** [comment]
Just needs CircleCI to pass

**Comment by hbillings** [comment]
Closed in #2077.
