### ISSUE TITLE
Look into upgrading Django

### ISSUE THREAD

**Issue by hbillings** [18F/calc#2082]
[There's a medium-level vulnerability](https://app.snyk.io/vuln/SNYK-PYTHON-DJANGO-42178) our current version of Django. I'm not sure exactly what upgrading Django entails, but we should investigate how heavy a lift it is.

**Comment by tbaxter-18f** [comment]
I believe the current version is 1.11.11. If you're staying on the 1.x version, this should be pretty easy. If you're going to 2.x, it'll be considerably more work.
