### ISSUE TITLE
Implement contract and vendor search UI

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2084]
Acceptance criteria:
- [ ] Users can search by contract number.
- [ ] Users can search by vendor name.

These reference images should help us launch the combination contract vehicle / vendor search / contract search tool with minimal impact on the layout of the home page.

![now](https://user-images.githubusercontent.com/9259185/43802840-a7754986-9a5c-11e8-942a-3a530bfd5819.png)

![2](https://user-images.githubusercontent.com/9259185/43803151-a06316e0-9a5d-11e8-9573-e11eb24561b1.png)

![now copy 2](https://user-images.githubusercontent.com/9259185/43803035-43580fa0-9a5d-11e8-893f-66eedf2d2cf9.png)

**Comment by hbillings** [comment]
Q: Are we doing the "exact match" checkbox? I don't see that on this mock but I thought that was the general plan. Thanks!

**Comment by ericronne** [comment]
Sure that's worth a try

![image](https://user-images.githubusercontent.com/9259185/43809706-674d802c-9a79-11e8-8075-2ebc4c9ba239.png)

**Comment by hbillings** [comment]
Hm, do we also want to autocomplete vendor/contract #, like we do now for labor categories?

**Comment by hbillings** [comment]
Another thought: As the number of schedules in CALC grows, the vendor and contract search options are going to get pushed further and further down. I'm not sure what to propose to fix this, but wanted to note it somewhere.

**Comment by hbillings** [comment]
@ericronne When you get a chance, could you post the version with the dropdown expanded? thx!!

**Comment by ericronne** [comment]
New Revision (provided @tram feels it merits testing), designed to improve flow of actions. In essence:
1. Make selection from pull down, telling us what sort of thing you are searching for  
2. Enter the text of your search
3. GO

## Default
![image](https://user-images.githubusercontent.com/9259185/43977245-17b9f612-9ca9-11e8-90bd-49c126c3a13b.png)

## Expanded
![image](https://user-images.githubusercontent.com/9259185/43977370-98cf4aae-9ca9-11e8-92c7-f59be6bd4726.png)

**Comment by tbaxter-18f** [comment]
Related to @hbillings  question about autocomplete above: I think autocomplete is nifty (and probably expected) but there probably needs to be some visual mechanism to indicate where it's autocompleting from, tied back to where you're searching in. If that makes any sense at all.

**Comment by ericronne** [comment]
Makes total sense, and agreed.

To the "Design Cave"!
![image](https://user-images.githubusercontent.com/9259185/43977991-68a0e11a-9cab-11e8-8b63-ce34e251392b.png)

**Comment by abrouilette** [comment]
Need API to unblock.
