### ISSUE TITLE
Quartiles, median, etc

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#2086]
Yo...as a CALC user I would like to have some of those quartiles and if you could through in a median that would be cool too because I forget what standard deviation means...and I like hard quarters.

**Comment by ericronne** [comment]
Closing, per @KellyBailey, who adds, "I prefer the percentile column to any quartile solution. I think for consistency, sticking with average makes sense and using the term average instead of mean will be easier for users to understand."

🎉
