### ISSUE TITLE
Implement tabular price-list analysis

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2093]
Modify the price-list analysis (#997) code to generate results in this format (as determined in issue #2083) …

| Service proposed  | Min. edu. | Min. exper. | Price | Average | +/- avg | +/- std. dev. | Percentile | # of results
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| KitKat snapper  |  BA  |  2  |  $137  |  $90.68  |  +$46  |  50.73%  |  1.2  |  72  |  452

## Mockup
![image](https://user-images.githubusercontent.com/9259185/44233173-c050ed80-a168-11e8-9e27-89cb97f11982.png)

**Comment by hbillings** [comment]
<img width="954" alt="screen shot 2018-08-24 at 11 49 11 am" src="https://user-images.githubusercontent.com/509309/44599387-6321f100-a793-11e8-9db0-81c2d99616e3.png">
This is where this is sitting currently -- @ericronne, all yours.

**Comment by ericronne** [comment]
![image](https://user-images.githubusercontent.com/9259185/44600061-ba2cc380-a79d-11e8-9690-b3a82ce97628.png)

**Comment by hbillings** [comment]
I think we can close this, right, @ericronne?

**Comment by ericronne** [comment]
Yep!
