### ISSUE TITLE
Clean up arrow-document icon

### ISSUE THREAD

**Issue by ericronne** [18F/calc#2107]
The "opens in a new window"-indicator icon at the end of contract links on the explorer table is rendering poorly:
![image](https://user-images.githubusercontent.com/9259185/44749569-840e7d00-aad8-11e8-9628-b3d92d6ca398.png)

Fix.

**Comment by ericronne** [comment]
Improved arrow and simplified icon:
![image](https://user-images.githubusercontent.com/9259185/44749632-ba4bfc80-aad8-11e8-880a-07e35a33c5a1.png)

@hbillings is this implemented as raw svg code in `contract-number-column.jsx'?

**Comment by hbillings** [comment]
Yes, I believe it is!
