### ISSUE TITLE
Schedule 736 Price List Upload

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#2117]
[https://app.zenhub.com/files/26967517/123050a2-6e18-4df3-ad93-2a46d5623135/download](https://app.zenhub.com/files/26967517/123050a2-6e18-4df3-ad93-2a46d5623135/download)

**Comment by tadhg-ohiggins** [comment]
While doing this, document the process and track how long it takes, as this is supposed to be something that can be done reasonably easily by new/external developers.
