### ISSUE TITLE
New Price List Capture for Schedule 71IIK (Region 3)

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#2207]
I will add a file with the format. KB

**Comment by KellyBailey** [comment]
Create a new price list upload list this:

https://calc.gsa.gov/data-capture/tutorial

Using the 71IIK (712K) format

**Comment by KellyBailey** [comment]
[Price List Format 71IIK.xlsx](https://github.com/18F/calc/files/2587532/Price.List.Format.71IIK.xlsx)

**Comment by sidramesh2018** [comment]
1) Add Region 3 category to the existing schedule list
2) Region 3 form attributes should match Region 10
3) The columns on page 3 for Data-Capture should match the excel sheet provided
4) file upload formats should support xls and xlsx

**Comment by KellyBailey** [comment]
The first tab has the data elements that are required and what the data element column title is in CALC's data explorer. The second tab shows that sample format for the "I don't know what to upload" section.
[PriceListUploadFormatCALC.71IIK.xlsx](https://github.com/18F/calc/files/2673677/PriceListUploadFormatCALC.71IIK.xlsx)

**Comment by snakrani** [comment]
Development of this is done and deployed in dev environment for testing.

**Comment by KellyBailey** [comment]
New R3 Price List format posted on 12/17/18
[R3 Price Proposal Template - Refresh 32.xlsx](https://github.com/18F/calc/files/2728216/R3.Price.Proposal.Template.-.Refresh.32.xlsx)
