### ISSUE TITLE
Design: A way to see out-year pricing data

### ISSUE THREAD

**Issue by brethauer** [18F/calc#222]
Here's one idea I had.  Please comment/critique/upload your own sketch

![img_2673](https://cloud.githubusercontent.com/assets/7635133/8622891/c933cc96-26fb-11e5-8df6-4f3397463eb8.JPG)

**Comment by maya** [comment]
@brethauer is -2 and +2 the max range of year data we'll have to show?

**Comment by KellyBailey** [comment]
Yes it is.

**Comment by brethauer** [comment]
Another idea to handle this would be a slider with "notches" living just above the histogram - see sketch
![img_2676](https://cloud.githubusercontent.com/assets/7635133/8628464/492f3ad2-2721-11e5-8e10-fad063894ff3.JPG)

**Comment by KellyBailey** [comment]
I am not sure that we would need previous years data. Maybe we should exclude the -1 and -2 because people could accidentally be looking at old data. I can't think of reasons they would be looking backwards.

**Comment by theresaanna** [comment]
Here is a little bit of a clunky, but maybe worth considering, solution.

The idea is that you'd click the button next to the price to slide down an expanded view with year-related data.

![img_20150710_143022](https://cloud.githubusercontent.com/assets/126935/8629500/b3557e6e-2710-11e5-9919-b868a6acb7c4.jpg)

**Comment by maya** [comment]
This is meant to be a filter in the right filter sidebar.

This shows the -2 and +2 years:

![fullsizerender](https://cloud.githubusercontent.com/assets/5249443/8663143/6e6102e2-297c-11e5-98a2-ad494e42cbf1.jpg)

This shows the current and year-out for 2 years:

![fullsizerender 1](https://cloud.githubusercontent.com/assets/5249443/8663140/6abc5916-297c-11e5-83b3-bf7eae309733.jpg)

**Comment by theresaanna** [comment]
How would the table change as this filter changed?

**Comment by brethauer** [comment]
@theresaanna My thinking is that when you select a different year, the table would need to update w/ the new prices (and potentially other updates?).  Perhaps certain rows would even drop out if you were already looking at year 5 for that particular contract.

**Comment by theresaanna** [comment]
:+1: Would the table header need to change or would we need to do something else to indicate that the prices are not current year prices? Also, should we add a column to the table to show the current contract year?

**Comment by brethauer** [comment]
Extra labeling (or otherwise somehow showing) that the price year is changed is up for debate I think.  @maya points out that we don't show the other filter statuses (statii?) elsewhere (other than the dynamic sentence, which would need updating).

I could go either way - I could see not doing any extra labeling, but it's also a pretty important piece of info that would totally change how you are looking at the results.  (e.g. work I want to do now vs work I want to estimate for the future)

**Comment by brethauer** [comment]
@maya what if we replace "0" with "Current"?

**Comment by maya** [comment]
@brethauer I think that text change could work

**Comment by maya** [comment]
What about...

- Current year
- Next year
- Next two years

?

**Comment by brethauer** [comment]
I'd love to get @KellyBailey 's thoughts on this.
Another idea:

Contract Year:
| Current | 1 Year out | 2 Years out |

**Comment by KellyBailey** [comment]
After talking to a CO- We need to show current year (and the year it is..ie. Year 3/current year) and previous (there may be some value) and future years. I like Maya's sketches. I would feel more comfortable with future year and previous years being separate so users are clear that previous year are "past".

**Comment by brethauer** [comment]
@KellyBailey Didn't we determine that we could let folks see more info about the year once they downloaded the data?  I'm thinking about the user mindset as "I'm estimating for work to be done soon/this year" or "I'm estimating for work to be done down the road / next year / the year after" 

If we have time, let's chat about this in (or just after) standup today

**Comment by brethauer** [comment]
Ok, Kelly, Maya and I chatted, and we determined a couple things:
1) Let's focus on positive out-years for now, since more folks have asked for them (current, +1, +2)
2) Let's prioritize helping users make out-year estimates using the overall results returned (rather than digging in to specific results)
3) Let's go with this + Maya's sketch above (and we'll need to work with the language a bit) :
Contract Year:
| Current | 1 Year out | 2 Years out |
4) We will need to add this filter to dynamic sentence, we will need to update data in the table whenever a year is changed, and we will need to add the dynamic sentence to the histogram... we can take these back-end tasks on this sprint if we choose, but we can also punt until next.

**Comment by theresaanna** [comment]
So, if I select +1, the data updates with the relevant records displaying the +1 year rate. The table will not change from what we have now, with the exception of the rate being updated. Is that correct?

@KellyBailey, given that, per your email, some of the rates beyond year one are empty, what should we do if there is no rate for the selected contract year? Should they not be shown?

**Comment by brethauer** [comment]
@theresaanna Correct, if you select +1, the table won't change except to update the rate, AND to your second question, dropping the row if there is no rate for that newly selected year.
