### ISSUE TITLE
High Severity- calc:requirements.txt 

### ISSUE THREAD

**Issue by KellyBailey** [18F/calc#2229]
Cut & paste from Snyk-

Information Exposure
Vulnerable module: requests
Introduced through: coreapi@2.3.3, cg-django-uaa@1.3.0 and others
Detailed paths
Introduced through: project@0.0.0 › coreapi@2.3.3 › requests@2.13.0
Introduced through: project@0.0.0 › cg-django-uaa@1.3.0 › requests@2.13.0
Introduced through: project@0.0.0 › requests@2.13.0
Overview
Requests is a Non-GMO HTTP library for Python

Affected versions of this package are vulnerable to Information Exposure. Upon receiving a same-hostname https-to-http redirect, it sends the HTTP Authorization header to an http URI. This makes it easier for remote attackers to discover credentials by sniffing the network.

https://app.snyk.io/vuln/SNYK-PYTHON-REQUESTS-72435

**Comment by snakrani** [comment]
Fixed. Ready for testing in Development environment.
