### ISSUE TITLE
Commas causing errors

### ISSUE THREAD

**Issue by maya** [18F/calc#233]
After I enter a search term and click enter commas are inserted and cause internal server errors.

**Comment by theresaanna** [comment]
The search technically works now, but there is the issue of user experience around the commas. @maya do you want to document that here?

**Comment by maya** [comment]
Sometimes after I hit "enter", new commas appear: 

<img width="662" alt="screen shot 2015-07-22 at 8 13 57 am" src="https://cloud.githubusercontent.com/assets/5249443/8828932/6d6f941a-3049-11e5-9136-9e9813809a12.png">
