### ISSUE TITLE
Load Schedule 70 data into CALC. >>> Current bid: 1 <<<

### ISSUE THREAD

**Issue by vzvenyach** [18F/calc#255]
As [previously explained](https://18f.gsa.gov/2015/10/13/open-source-micropurchasing/), this issue has been tagged as a "micro-purchase" issue. The opening "bid" for this issue is $3,499, and vendors may offer lower bids. The vendor with the lowest bid at closing time will have 10 working days to provide code that satisfies the requirements and acceptance criteria below. Upon successful completion, the vendor will be paid. If the vendor fails to complete the requirements and satisfy the acceptance criteria within the 10 working day period, then the vendor with the next lowest bid shall have 10 working days to provide the code. If the acceptance criteria are not satisfied, vendors shall not receive payment pursuant to this competition.

## Description of issue

Currently, CALC uses a [management command to load data](https://github.com/18F/calc/blob/master/contracts/management/commands/load_data.py) from 7 different schedules. We want to load the Schedule 70 data provided into CALC (note, the data will likely need to be reformatted). The data is available here: https://github.com/18F/calc/tree/s70/contracts/docs/s70

## Acceptance criteria

1. Either a new Django management command or modification to https://github.com/18F/calc/blob/master/contracts/management/commands/load_data.py to load the Schedule 70 as Contract objects in the database.
2. Whether a new command or a modification to the existing command, the rating from https://codeclimate.com/github/18F/calc for the file must be at a B or better rating, and test coverage for the command at 90% or better upon completion. 
3. Front-end changes to ensure the ability to filter results by schedule type (e.g. Schedule 70 data or others) and easily see the schedule source for each row in the results.

## Bid submission deadline

Bids for this issue close at 12 p.m. EST on Thursday, Oct. 29, 2015. To bid on the issue, click here: https://docs.google.com/a/gsa.gov/forms/d/1eRFX0hSTTXMc2FulK6kPP2P02ZApQqlYZL7oVDghJJo/viewform

**Comment by vzvenyach** [comment]
QUESTION: How many times is a company allowed to submit a bid on this form?
ANSWER: Multiple bids are permissible.

**Comment by pavellishin** [comment]
> QUESTION: How many times is a company allowed to submit a bid on this form?
> ANSWER: Multiple bids are permissible.

So wouldn't it make sense for a company to enter three low bids, varying by a penny, and thus get 30 working days to get a fix in?

**Comment by Connery-LCSolutions** [comment]
I would assume they mean a company can underbid bid another as many times as possible. The instructions clearly indicate that the lowest bidder will have 10 days for completion only. The scenario you described would only make sense if that company was the only bidder.

V/r

Daniel Connery

**Comment by vzvenyach** [comment]
QUESTION: Please confirm whether we are allowed to submit a second bid if we are undercut by another bidder.
ANSWER: Confirmed.

**Comment by saulshanabrook** [comment]
> 3. Front-end changes to ensure the ability to filter results by schedule type (e.g. Schedule 70 data or others) and easily see the schedule source for each row in the results.


Do you mean adding `70` as a schedule option, so that it would appear in the dropdown (in red) and as the "Schedule" for any appropriate rows (in green)?
![screenshot 2015-10-26 20 47 57](https://cloud.githubusercontent.com/assets/1186124/10746613/1a0e6316-7c23-11e5-98b9-448bdf348818.png)

**Comment by siruguri** [comment]
It appears that `load_data.py` is currently a C on codeclimate. If we were to modify it, does that mean we have to bring existing code up to a B? In other words, should we explicitly create a separate file for the new command, so that our ability meet the AC is not impacted by existing code?

**Comment by borromeotlhs** [comment]
You mention '7 other schedules'.  Can you all provide the example dataset you currently operate on with load_data.py to reveal the formatting of _that_ dataset?

It would help clarify the issue to those of us who don't understand that "schedule 70" is a type of "schedule".  More background info about what a " schedule" is would help as well, perhaps via pointed to a user manual to familiarize ourselves with CALC's DSL and features.

**Comment by vzvenyach** [comment]
@borromeotlhs Thanks for the comment! I'll let @theresaanna correct me if I have this wrong, but I'm pretty sure that the current data is pulled from here: https://github.com/18F/calc/blob/master/contracts/docs/hourly_prices.csv

A schedule (http://www.gsa.gov/portal/category/100615) is basically a contract vehicle that makes it easier for companies to contract with the government. Schedule 70 is for IT contracts. Within Calc right now, there's an explanation here https://calc.gsa.gov/about/#schedules that lists the schedules that are currently loaded.

Does that help clarify?

**Comment by vzvenyach** [comment]
@siruguri That's correct. Ultimately, as Code Climate [currently shows for the load_data command](https://codeclimate.com/github/18F/calc/contracts/management/commands/load_data.py), the `handle` method is already unwieldy. For this issue, I wanted to make sure that the new feature did not simultaneously increase the level of technical debt in the `load_data` command. Does that clarify?

**Comment by brethauer** [comment]
@saulshanabrook Yes - correct!

**Comment by thoughtobj** [comment]
> [...] and test coverage for the command at 90% or better upon completion

Q1: How will test coverage be measured?
Q2: Should the tests be added to the same file where tests for the current [`load_data` command] (https://github.com/18F/calc/blob/master/contracts/tests.py) are?

**Comment by brethauer** [comment]
***Question:***
In the hourglass/local_settings.py file... What does the SECRET_KEY refer to?
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'hourglass',
        'USER': '',
        'PASSWORD': '',
    }
}

SECRET_KEY = ''
```

***Answer:***
SECRET_KEY is a value that Django requires. You can read more about it here: https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-SECRET_KEY

I'd recommend setting the key in a local_settings.py in the same directory as settings.py. This way it cannot accidentally make it out of the environment.

**Comment by Connery-LCSolutions** [comment]
All,
     While I'm certainly happy that 18F is going to get a great value on this work, a word of caution on how you're bidding. There is no need to drop $500 per bid, when $50 increments would work just as well. After taxes (and assuming no overhead), you're already bidding at an entry level coder's hourly rate. Given the very limited understanding of the code and requirements expressed in these questions, I think someone is in for a very rude awakening when they realize that they've essentially paid to do work. Good luck to you all and I'm eager to see further "micro-purchase" work available based on this success.

Very Respectfully,

Daniel Connery
214-934-3025

**Comment by patrickmcconnell** [comment]
It is not possible to determine whether a bid that I submitted is the leading bid.

**Comment by vzvenyach** [comment]
Thanks, @Connery-LCSolutions! While we definitely appreciate your interest, we respectfully would ask that vendors refrain from discussing bidding/pricing strategies in github. thank you for understanding!

**Comment by vzvenyach** [comment]
@patrickmcconnell we've noticed that sometimes the google apps script trigger is not automatically updating. When I get an email, I've been re-running the script and updating. I have been trying to debug, but it works _some_ of the time, but not predictably.

**Comment by patrickmcconnell** [comment]
I mean I saw an update very close to when I submitted a bid but it seems like it may have happened about 15 seconds before I submitted the bit.  Therefore, I cannot tell whether it was my bid or someone else bid the same amount as me but slightly earlier.

**Comment by vzvenyach** [comment]
@thoughtobj 

Q1: How will test coverage be measured?
A1: We typically use [coverage](https://coverage.readthedocs.org/en/coverage-4.0.1/) to measure.

Q2: Should the tests be added to the same file where tests for the current load_data command are?
A2: Yes. If the new code is part of the `load_data` command, then the tests should be in the same place as the current `load_data` tests.

Q3: Are the tests just for the new command that loads schedule 70 data or also for api/tests.py
A3: If changes to the API are necessary (I'm checking with the team to see whether that'd be so, but my impression was not), the changes should be reflected in `api/tests.py`.

Let me know if that helps.

**Comment by borromeotlhs** [comment]
Is there a way to use the code climate tool without exposing your solution
and without having to pay for premium github private repos?

**Comment by thoughtobj** [comment]
+1 @borromeotlhs I have the same question.

**Comment by siruguri** [comment]
. What code branch should we consider ourselves to be working off of?
. While the links provided appear to sufficiently document the requirements (thanks!), there's always the possibility of needing help with business specifics. Will there be a designated point of contact available in the 10-working-day period to answer questions in a timely manner, after contract award?

**Comment by vzvenyach** [comment]
@borromeotlhs I'm not sure I understand your question. There is no need to begin work or proposing a solution while the bid period is still open. Only after the bid period has closed and a vendor is determined must the vendor start work and propose potential solutions. At that point, work would need to be submitted in the open, so at that point you can use the free tier of Code Climate.

**Comment by vzvenyach** [comment]
@siruguri Use the master branch as the base branch. 

During the 10-day period, you can feel free to open issues/comments in the repo or email micropurchase@gsa.gov.

**Comment by vzvenyach** [comment]
QUESTION: I wanted to know if the goal of the schedule 70 import task is just to get the data in once, or to restructure the import process so it will be easier to extend again in the future. The other part of that question is where you get the data for the 7 other schedules. Do you have to spend a lot of time massaging it into acceptable form for import?
ANSWER: The 7 other schedules come in a single file and is essentially formatted as you see it in the repo. The Schedule 70 data comes separately. We'll likely need to import additional schedule 70 data in the future, but it's a fair assumption that it will look like the data provided. As for the ability to extend, that's definitely a very legit approach. But we also haven't required it. Does that make sense?

**Comment by patricknowlan** [comment]
What happens if there is a last minute bidding war... Will companies be able to submit a "lowest bid", will the bidding continue until there is only one bidder left, or will bidding be cut off?

**Comment by borromeotlhs** [comment]
The concern is that if you do work after winning a bid, that other
companies could benefit from what you've done without you getting paid
should you not hit the mark.  Alternatively, no one could get to the
acceptance criteria, yet you all now have access to multiple approaches
that will allow you to implement it yourselves without having to pay anyone.

I'm just pointing out that acceptance criteria should be able to be tested
by us without giving up the proprietary nature of our solutions until it is
accepted and paid for.

**Comment by patricknowlan** [comment]
I am having a permissions error when trying to submit a bid on the Google form. My teammate is also not able to access it.

Here is a screenshot:
<img width="518" alt="screen shot 2015-10-28 at 10 22 35 am" src="https://cloud.githubusercontent.com/assets/6303436/10791276/fb7a7638-7d5d-11e5-80a6-03894ce8ac43.png">

**Comment by vzvenyach** [comment]
@patricknowlan Try now? Sorry... that is weird.

**Comment by patricknowlan** [comment]
Working now! Thank you.

**Comment by vzvenyach** [comment]
QUESTION: Unlike hourly_prices.csv currently being used by calc, the s70.csv provided for the micropurchase does not have hourly rate for 5 years. It only has rate for one year. Would it be acceptable to take the rate from s70.csv and put it in hourly_rate_year1 and have hourly_rate_year[2..5] empty? Or is the expectation something else..?

ANSWER: That's acceptable.

**Comment by vzvenyach** [comment]
@patricknowlan We discussed this internally. Because we originally stated that the lowest bid will win, I'm not sure we're in a place to change that expectation at this point. But it's definitely a good idea, and something we will want to consider for the next go around. And, for what it's worth, we'll be manually watching the bids between 11:30 and 12 to make sure we keep everything up-to-date within seconds of a bid.

**Comment by thoughtobj** [comment]
How would `next_year_price` and `second_year_price` be handled for the Schedule 70 data since it only has price for one year? Further, how will this affect the control for these two fields on the UI as shown by the below screenshot. Reason for asking this question is to ensure the scope of the feature doesn't deviate a lot from what is mentioned in the original post. 

![screen shot 2015-10-29 at 12 48 31 am](https://cloud.githubusercontent.com/assets/14097154/10810436/55a7dde8-7dd7-11e5-99f6-ad40bc2eec49.png)

**Comment by thoughtobj** [comment]
@vzvenyach Keeping the current lowest bid of $1 in mind, would this even be considered legal at this point? since the hourly rate comes out to be way below the minimum federal wage limit...

**Comment by thoughtobj** [comment]
Additionally, the bidding form does not accept floating point numbers and hence the current bid can't be beat.

**Comment by jvettraino** [comment]
A suggestion for the future is to allow/accept bids greater than the lowest amount to be entered in.  That way if the company with the lowest bid doesn't meet the acceptance criteria, it opens up the pool more to whatever companies reasonably bid, instead of whoever was just next in line at the time of the lowest bid.  For example since the bid is $1 now, and if we feel we could do it at $500 it would be nice to allow us to enter in that bid and be in the running to get a chance if the $1 bid doesn't successfully complete it.

**Comment by cwarden** [comment]
With no change to the bidding process, there will be two bids from colluding bidders next time, the first at $3499 and the second at $1.

**Comment by AustinDizzy** [comment]
@thoughtobj Of course this is still legal as payment would be contractual from a vendor, not hourly from an individual. The law doesn't prevent a vendor from taking a loss from contract work, it only prevents a company from undercutting a non-salaried individual's hourly pay. An example would be when Larry Page was CEO at Google taking a $1/yr salary. The federal minimum wage plays no part here.

**Comment by borromeotlhs** [comment]
This whole setup will fail.  bidding on things when the whole idea was to
get away from the slow moving buracracy of actual government
contracts/bidding process by breaking the work into smaller 'bounty-able'
chunks.  No large company should take this job at a loss, as there is no
reason (underlying contract work you could win) to justify it.  Now that
this view has been shared, I don't even feel good about further devaluing
tech talent.  Ironically, as we are about to be enlisted to help set up the
tool that will be used to aid in that devaluation.

Fix the process for deciding who does what, stick to 3500 flat fees, break
out the coding work to definable and self contained tasks, allow for
testing without revealing solutions.

Fix all of that, and you might actually end up finding a contractor who
knows what this work is worth and can provide code at the level you ask (
which, BTW, is requiring that the contractor actually _improve_ the hackjob
that is the reading in of data)

OUT

**Comment by thoughtobj** [comment]
@AustinDizzy This might still be legal because of "micro-purchase". I raised this concern while wondering if they had thought about this scenario. FWIW, I don't agree with the parallel you are drawing with Google/Larry Page. Neither of them are being paid by the federal govt. 

@vzvenyach et al. I'd like to commend 18F for trying out this bold experiment. There are a few key takeaways from this experiment that can be planned better for the next time. I think a model that provokes a bidding war isn't in the best interest of 18f or the vendors. Perhaps a more conventional route of taking one time bids from vendors and then making an informed decision based on the price and value provided by the vendor would be best. The key broken thing in conventional govt. contracting isn't the process of how bids are taken, but the lack of an engineering team that has the know-how to decide whether a specific vendor has the capability to do perform the required work. I hope 18f continues to improve on the micro-purchase model and open more issues to attract the vendors. 

To the bidder who won this bid, I hope you provide great value to this so that we continue to see more stuff like this in the future! Get in touch if you need some help!

**Comment by saulshanabrook** [comment]
To add on to @thoughtobj, I am impressed by the willingness of 18F to continue trying out non conventional strategies for federal contracting. Keep up the great work, whatever the outcome of this specific micro-purchase is!

**Comment by patrickmcconnell** [comment]
@thoughtobj , there is precedence in this type of bidding for federal government goods and services using reverse auctions.

I would like to see a more structured mechanism to bid and determine whether your bid is leading.

I would like to see a larger effort broken into micropurchases and see whether the final solution can be integrated.

I would like to see better specifications of the work requirement, though I was able to determine what was required with about 45 minutes of digging into the git repository and source code.

Another alternative is for 18F to write the test harness to run code against.  This would be within the principles of TDD.

@vzvenyach, what was the winning bid and who won it?

**Comment by SJLC** [comment]
@patrickmcconnell 
The winning bid this morning was $1, which stopped bidding being the lowest allowed bid.

I could see where this was headed yesterday - some company is signing up  for the equivalent of an unpaid internship in exchange for documented experience of this type of work.

**Comment by patricknowlan** [comment]
I would be interesting to run another micro-purchase experiment using a model similar to how [Upwork / oDesk](https://www.upwork.com) handles fixed price contract work.  This somewhat aligns with what @thoughtobj said:

> a more conventional route of taking one time bids from vendors and then making an informed decision based on the price and value provided by the vendor

Each approach has its pros and cons. Here's my 2 cents.

The bidding approach works great for shipping code, driving down costs, and providing 18F an opportunity to network with new companies who they might not reach through traditional contracting channels. This is awesome and opens up more work for startups / small businesses / freelancers! The question is... does bidding down the price, bid down the quality? In this experiment variable `quality` will be an output to the process.  

The one time bid approach removes the notion of driving down price and additionally includes the concept of `quality` as an input to the decision making process. This might ultimately cost more but should lower risk for the micro-purchase. But we're not talking about million dollar contracts, so how important is risk?

If I am hiring someone to mow my lawn, I would want to put the top/highest reviewed companies in a room and then have them bid against each other for the work. Less risk for me, higher probability of quality work. 

There is so much to be learned from this exercise and I hope there are more to come. I assume one of the goals of the micro-purchase is to disrupt. This has been accomplished :+1: Looking forward to a blog post on your findings!

**Comment by borromeotlhs** [comment]
This completely ignores the fact that, as open source, this should already
have been resolved by the entities using this software.  Were it up to me,
I'd think it'd have been more valuable to call upon the folks who may have
some coding experience in those government offices that utilize calc to
improve upon it.

Cost: $0
Risk: low
quality: high ( you eat your own dog food)

In any case, I look forward to laughing at the person who ends up doing any
work for a dollar. :P

**Comment by oli5679** [comment]
Your bidding rules encourage participants to behave strategically by bidding more than their reservation price, frequently rebidding and waiting until just before the auction ends to place bids.

Here's a suggested bidding format that would avoid these problems:

(1) Everyone bids the lowest price that they would be willing to accept for completing the task

(2) If the lowest bid is unique, the task is assigned to the lowest bidder and they are offered the rate offered by the next lowest bidder

(3) If many people bid the same price, one is randomly chosen and they are offered the rate that they bid.

(4) If they fail to complete the task according the requirements, the next lowest bidder is offered a quote according to the criteria above.

This is just standard auction design theory.

**Comment by MaerF0x0** [comment]
Also malicious actors can just add FUD to the whole process.  Suggestion: Accepted RFP must put up $3500 USD in escrow.  Failure to deliver results in loss of deposit.

**Comment by brianru** [comment]
Serious question: is this a problem? Should we (as a society) be discouraging people from donating their time and expertise to our government in exchange for publicly documented experience?

(assuming the bid was placed in good faith)

**Comment by jvettraino** [comment]
I think it is fantastic, and I am excited to see how it pans out.  I also think this experiment is a great one.  People donate their time on open source all of the time, so why not here.

**Comment by MaerF0x0** [comment]
```
Serious question: is this a problem? Should we (as a society) be discouraging people from donating their time and expertise to our government in exchange for publicly documented experience?
```

I agree good faith bids/efforts are kind gestures. Unclear how we prove those though.

**Comment by wadestuart** [comment]
The thing I find a little funny is that given the bidder gets 10 days to submit the code,  and assuming that extreme low ball bids will probably be from folks unable to perform the work -- the code could be delivered in 10 * 3,499 days in the assuming the worst case is the highest bidder is the only one able to perform the work.   Can't wait to see the results in good old 2111.

**Comment by SJLC** [comment]
@oli5679 there could be esssentially the same outcome with single-bid rules -- why do we assume there is exactly one bidder willing to do this for reputation rather than pay? Multiple of these experience-seekers could easily bid $1 in the sealed bid. If there is a pool of bidders interested in the documented experience rather than the pay, someone from that pool will always win if job goes to lowest bidder, whether it's sequential or simultaneous bid mechanics. 

Other mechanics could be considered however, if it is deemed useful to keep participation of companies interested in actually getting paid for their time. 

For instance, the hourly rate for the contract could be locked to some standard salary for software developers, plus some fixed fee. The bidding could be in terms of number of hours to pass the acceptance criteria, as a countdown from the maximum number of hours affordable with the budget constraint. The bid winner would be the one confident of getting it done in the smallest number of hours, and they would have to complete in that amount of time to fulfill the contract. Anybody who bids something ridiculous, like 1 hour, would quickly time out and fail, leaving the contract to the low-but-realistic bidder who bid low because they really *are* experts who could do the given task in their sleep.

That's just an example of changing the rules to reward experts, and not necessarily advisable without some tweaking (for instance, it could give the advantage to companies able and willing to make their software engineers work a burst of super-overtime to meet a really tight schedule). My main point is that there would need to be a big change in the rules to make the contract amount meaningful... or else might as well just give up and officially award reputation rather than money.

**Comment by oli5679** [comment]
@SJLC I don't completely understand your point. Im arguing that a 2nd price auction would lead to an improvement relative to current rules. It could be that (1) sometimes both systems would lead to the same results. (2) some complex inclusion of reputation/time could be even better. Your ideas could be intetesting, but they should be implemented as part of a 2nd price auction rather than traditional highest (lowest) bidder because of points I made earlier. If you don't understand then I can clarify.

**Comment by SJLC** [comment]
@oli5679 I wasn't arguing your suggestion with 2nd price and simultaneous bids isn't  in the *general* case better auction design, just that tweaking the price-based competition under this specific unusual condition (some competitors only interested in a totally *non-money-based* payoff) seemed unlikely to have much effect. Except in the case of exactly one bidder who wants only the rep, there would be multiple very low bids, so price number 2 still ends up no more than a token payment. 

On the other hand, combining the 2nd price auction idea *with* a suitably-thought-out substitute for straight money bid seems promising!

**Comment by geoffharcourt** [comment]
@wadestuart you do need SAM certification to be eligible to bid, so that presumably limits the pool of people/orgs who can bid on the work.

**Comment by Connery-LCSolutions** [comment]
All,
     As much as we are "arguing with the client" here, it is us vendors that are disappointing. I sent out a message last Tuesday suggesting that everyone be mindful of their bids, and not to "buy work". Ironically, if we had all used the Calc tool, we wouldn't have this problem. 

I, like many of us, was hopeful that this experiment would lead to a streamlined business process that could be adopted industry wide. At my current client site, we have 3 managers for every 1 actual developer. This top heavy, artificial barrier to entry will not change to a small business friendly environment until we learn to implement ethical business practices ourselves. Granted the defense industry is now an over-saturated market and this is a systemic issue, but the concept of ethics in bidding remains the same. Good luck to you all.

Very Respectfully,

Dan Connery

**Comment by borromeotlhs** [comment]
I disagree that this has anything to do with ethics on the bidders part.  Simple economics determine incentives.  Money for work being the biggest.  At this point, whether or not work is done is irrelevant, as acceptance criteria is an easy criteria by which to weasel out of work at no cost.  With no disincentive to penalize failure to perform, all bids are just talk.  Furthermore, time of the developers being the one resource exhausted without compensation (by just waiting for bids out discussing the merits of micro purchases), the government agency is again benefitting from unpaid labor as we as developers do 'thought work'.

But I guess that's what experiments are for.  Though I'd hope we would have spent time testing a more reasoned approach.  Did anyone consult an economist on this?

**Comment by fulldecent** [comment]
I am subscribing to this thread and hoping that if further opportunities are available under the micropayments strategy that they will be announced here. (An email signup would be nice.) That will allow me to be notified of them rather than me having to remember to look for them.

**Comment by vzvenyach** [comment]
Blog post with final details about first iteration of the experiment just went live: https://18f.gsa.gov/2015/11/06/micro-purchase-lessons/ 

Thank you *everyone* for you interest in this first iteration. If you want to participate/keep track of future iterations, please let us know here: https://docs.google.com/forms/d/17l9hEd-rsZZrcYWGDtyfhAf2xgzZw0DHAIJ_v_CboSg/viewform
