### ISSUE TITLE
Sorting CSVs on unindexed columns times out

### ISSUE THREAD

**Issue by jmcarp** [18F/calc#257]
The `/rates/csv` endpoint allows sorting on arbitrary combinations of columns in the `Contract` model. Since some of those columns aren't indexed, and since this endpoint attempts to load all matching rows in the table, some queries take a long time or time out, throwing a 504. If enough slow queries hit the database at once, other parts of the site might slow down as well.

<img width="1332" alt="screen shot 2015-11-10 at 10 31 51 pm" src="https://cloud.githubusercontent.com/assets/1633460/11083840/fae9b4aa-8801-11e5-9d0d-f938662711ed.png">

Also, attempting to sort on a string that isn't a column throws a 500: https://api.data.gov/gsa/calc/rates/csv/?sort=vendor_name. The expected response code would probably be a 400 or 422.

Recommendations:
- [ ] Index all columns that should support sorting
- [ ] Disallow sorting on any non-indexed columns
- [ ] Disallow sorting on strings that aren't columns

**Comment by toolness** [comment]
Barring actually indexing every possible column, I think that at the very least we might want to white-list the sorting columns by the ones used by the front-end, so that it's not possible to accidentally (or intentionally) DoS CALC.
