### ISSUE TITLE
DRF CSS not served

### ISSUE THREAD

**Issue by jmcarp** [18F/calc#258]
The calc API endpoints seem to use the content negotiation and browsable API, but the associated static files aren't being served at the expected URLs.

<img width="1423" alt="screen shot 2015-11-10 at 11 43 39 pm" src="https://cloud.githubusercontent.com/assets/1633460/11084091/e913f40e-8804-11e5-84d7-84cfe4c05952.png">

**Comment by toolness** [comment]
This bug appears to have been fixed at some point, possibly by 28469341f58f2616b139a1216935281f67b92a79 or 01a312e107c448c19f9d4ce43bcbb965036a8206.

Regardless, the page appears to look fine in production at https://calc.gsa.gov/api/rates/, as well as locally in my development environment, so I'm closing this issue!
