### ISSUE TITLE
Add CIO-SP3 Rates

### ISSUE THREAD

**Issue by bengm** [18F/calc#263]
Although not a GSA vehicle, rates from CIO-SP3 would be quite valuable to be included in this (already valuable) tool. The data is available publicly as PDFs that would have to be converted, but NITAAC may have original excel versions that would be easier to parse automatically.

(I suppose this would be an enhancement tag, but perhaps not - really just adding more data.)

**Comment by KellyBailey** [comment]
Hello Bengm,

I am the product owner for CALC so I will look into this. I just looked up the contract on GSA's Acquisition Gateway, and I am impressed with what I see so far. I will add it to my product backlog and talk to stakeholders / users about including that pricing. I met with some NIH employees a couple of months back about how NIH might use a tool like CALC.

Thanks for the suggestion,

Kelly
