### ISSUE TITLE
Table and chart break with filter set to Schedule 70 and Contract Year = +1 or +2

### ISSUE THREAD

**Issue by jseppi** [18F/calc#289]
Wanted to log this before I forgot about it. Following these steps, I get a JS error that causes the table and chart to break on the main page of CALC:

1. Set Schedule to "IT Schedule 70"
1. Select "+1" or "+2" for Contract Year
1. Open your browser's developer console, where you will see:

<img width="383" alt="screen shot 2016-06-16 at 5 28 34 pm" src="https://cloud.githubusercontent.com/assets/697848/16135253/d756df62-33e7-11e6-9c36-14aa058bd60e.png">

**Comment by toolness** [comment]
Nice catch!

I think this might actually be a specific case of #244, as the same error (from the same line number) appears to be logged if searching with a query that produces no results, e.g. https://calc.gsa.gov/?q=waegaweg.
