### ISSUE TITLE
Improve UI when filters produce no matching data

### ISSUE THREAD

**Issue by jseppi** [18F/calc#295]
Instead of an empty chart and table, there should perhaps be a message indicating that no matching data was found given the currently selected filters.

ref: #294 

![image](https://cloud.githubusercontent.com/assets/697848/16154115/065a3c8c-346f-11e6-86b6-83f7435f7a52.png)

**Comment by toolness** [comment]
There's currently a slick d3 transition that occurs on the graph when the search criteria changes; while we should definitely make the empty results view more user-friendly, it'd also be nice to take into account the transition between the zero-results view and the one-or-more-results view, to ensure that it stays nice and smooth!

**Comment by jseppi** [comment]
We should verify whether this is in scope of our current work before making any changes here.
