### ISSUE TITLE
Document WHITELISTED_IPS environment variable

### ISSUE THREAD

**Issue by toolness** [18F/calc#302]
`settings.py` seems to pull the `WHITELISTED_IPS` setting from the environment, defaulting it to `False`.  Looks like it's being passed to `REST_FRAMEWORK['WHITELIST']`.

[Here's a search for `WHITELIST` on the repo's codebase.](https://github.com/18F/calc/search?utf8=%E2%9C%93&q=WHITELIST)

**Comment by jseppi** [comment]
Closing in favor of #301 since they are related.
