### ISSUE TITLE
On cloud.gov, link to database service instead of to RDS through an env variable

### ISSUE THREAD

**Issue by jseppi** [18F/calc#325]
Currently the `DATABASE_URL` is specified as an environment variable pointing to RDS instances. I can't tell exactly how these are setup or managed, but I think it would be preferable to use a database service and grab its `uri` from the associated `VCAP_SERVICES` entry. For an example, see this section in Checklistomania: https://github.com/18F/checklistomania/blob/master/scripts/addEstimatedDueDate.js#L6

**Comment by jseppi** [comment]
According to conversation with @cmc333333 and confirmed with my sandbox deployment, the python buildpack will automatically set the `DATABASE_URL` environment variable when a linked database service is found, so we won't need to set it explicitly if we are using a Cloud Foundry database service.

**Comment by jseppi** [comment]
We need to find out who "owns" the current RDS instances and determine if they should/can be shut down once we connect to CF-managed database services.

**Comment by toolness** [comment]
Is this a duplicate of #607?

**Comment by jseppi** [comment]
Yes, closing in favor of #607.
