### ISSUE TITLE
PhantomJS-based Selenium tests randomly fail on CircleCI

### ISSUE THREAD

**Issue by toolness** [18F/calc#330]
I'm not sure when this started. For a while, after #267, we had no problems. Then we had to do #309. About a week ago we seem to be getting [random failures like this](https://travis-ci.org/18F/calc/builds/140786815#L2392), where, as far as I can tell, the following happens:
1. Some number of selenium tests actually succeed.
2. At some point in a selenium test, `http.client` raises a `http.client.BadStatusLine` error with an empty string as the content. The module's code indicates that "Presumably, the server closed the connection before sending a valid response."
3. All future tests fail with a `urllib.error.URLError` of `Connection refused`.
4. The final test errors while trying to take a screenshot via webdriver, with the same exception as above.

The particularly frustrating thing about this is that, unlike previous selenium problems, I'm unable to reproduce this on my local system.

Probably the best thing to do for now is to just not run selenium tests on Travis. 😞

**Comment by jseppi** [comment]
Good to close, @toolness?

**Comment by toolness** [comment]
Hmm, I feel a bit weird closing it because #331 was more of a workaround than an actual fix... Maybe we should rename it to "Selenium tests fail on travis when enabled" or something?

**Comment by toolness** [comment]
Ok, so in #841 we added support for Travis to run selenium tests via Sauce Labs for *trusted* PRs--however, for *untrusted* ones we can't have our Sauce Labs key in the Travis environment, and therefore there's still a need for falling back on PhantomJS. So we're leaving this issue open!

**Comment by toolness** [comment]
Ok, we're closing this because (A) we're not on Travis anymore and (B) the selenium tests seem to work on Circle.  But if (B) changes we'll re-open this ticket and rename it to mention Circle.

**Comment by toolness** [comment]
well we moved from phantomjs to headless chrome in #1767 so i'm closing this.
