### ISSUE TITLE
Travis automatic deployments are not working

### ISSUE THREAD

**Issue by jseppi** [18F/calc#338]
Automatic staging (`calc-dev` space) deployments on pushes to `develop` branch are failing.

ref: https://travis-ci.org/18F/calc/builds/141140583

<img width="906" alt="screen shot 2016-06-29 at 2 46 31 pm" src="https://cloud.githubusercontent.com/assets/697848/16466359/6f434f20-3e08-11e6-8ac1-414a7ed1d41e.png">

**Comment by jseppi** [comment]
Apparently still not fixed o_O

Ref https://travis-ci.org/18F/calc/builds/141222145#L418

<img width="556" alt="screen shot 2016-06-29 at 7 21 53 pm" src="https://cloud.githubusercontent.com/assets/697848/16472964/d4a4a2da-3e2e-11e6-93db-7e5365ab16a4.png">

**Comment by toolness** [comment]
It's possible that the secure credentials you've encrypted in `travis.yml` aren't [escaped in the extremely weird way that travis expects them to be](https://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols)--I ran into this last month with a different project.
