### ISSUE TITLE
Staging Deployment TODOs

### ISSUE THREAD

**Issue by jseppi** [18F/calc#344]
- [x] deploy on change to `develop` branch
- [x] update domain to `apps.cloud.gov`
- [x] use User Provided Service for config environment vars
- [x] add New Relic monitoring. It looks like this used to be in there, but now doesn't exist in our NR account.
- [x] move database to Cloud Foundry-based postgres service and link to staging environment. 
- [x] figure out what the deal is with `API_HOST` and `WHITELISTED_IPS` (ref #301)

**Comment by jseppi** [comment]
Actually we might not want to use a database service if we continue with Blue-Green deploys because there could be discrepancies between the two databases. ref: http://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html

**Comment by toolness** [comment]
Cool! I'm not sure if it makes a difference, but for a different project I was advised to use a newer (I think?) plugin for cloudfoundry called [autopilot](https://github.com/concourse/autopilot).  Not sure if that remedies the DB problem, but we could potentially switch to it if we want.

**Comment by jseppi** [comment]
Oh yeah, I recall seeing autopilot mentioned in Slack. Will look into it!

**Comment by jseppi** [comment]
Staging instance is now back on the API Umbrella instance and is proxying requests through it.

**Comment by jseppi** [comment]
New Relic is monitoring staging instance now. All done!
