### ISSUE TITLE
Parse error on XSS Protection header

### ISSUE THREAD

**Issue by jseppi** [18F/calc#363]
<img width="290" alt="screen shot 2016-07-06 at 1 26 16 pm" src="https://cloud.githubusercontent.com/assets/697848/16629862/44f0b850-437d-11e6-8ea6-af1a89a2403a.png">

Looks like there is a problem with the XSS protection header, as shown in Chrome console screencap above. This is on staging instance.

Probably related to changes from #360

**Comment by jseppi** [comment]
Looks like we have two XSS headers coming through on `/`, as shown in `curl` output below. I bet this is the problem.

<img width="382" alt="screen shot 2016-07-06 at 1 42 28 pm" src="https://cloud.githubusercontent.com/assets/697848/16630335/9311e05c-437f-11e6-9e31-3873f8ac6fa1.png">

**Comment by jseppi** [comment]
Only one XSS header is coming through on the 404 response though:

<img width="434" alt="screen shot 2016-07-06 at 1 50 37 pm" src="https://cloud.githubusercontent.com/assets/697848/16630609/b0f5d06e-4380-11e6-93f2-e24aed5d9f17.png">

**Comment by jseppi** [comment]
After some local testing, I think it is actually cloud.gov adding the `X-XSS-Protection` (all caps) header. It seems strange that it does add it to the `200` responses but not to the `404` responses.

**Comment by toolness** [comment]
Yeah, that is definitely odd--maybe we should file a bug for cloud.gov?  Or multiple bugs:

* If a server is already delivering a `X-Xss-Protection` header, don't append stuff to it.
* If you do add an `X-Xss-Protection` header, add it to all requests, not just 404's.

**Comment by jseppi** [comment]
Asked in #cloud-gov-support

**Comment by jseppi** [comment]
Here is where cloud.gov is adding it https://github.com/18F/cg-secureproxy-boshrelease/blob/master/jobs/secureproxy/templates/config/nginx.conf.erb#L107

It looks like the only way around the double header are for us to only add X-XSS-Protection to 4xx responses (which the cloud.gov proxy isn't doing).

**Comment by jseppi** [comment]
`X-Content-Type-Options` is also duplicated on `200` responses. It is also not duplicated on `40X`.

<img width="443" alt="screen shot 2016-07-12 at 8 08 42 am" src="https://cloud.githubusercontent.com/assets/697848/16768021/f4999428-4807-11e6-8e6e-6280a1a12b66.png">
