### ISSUE TITLE
As a Cloud Foundry user, I would like to leverage the fake UAA

### ISSUE THREAD

**Issue by afeld** [18F/calc#368]
https://github.com/18F/calc/pull/317 is awesome, and I think it would be fairly reusable for other teams running Cloud Foundry UAA. Not urgent, but it would be great to have that broken out into a standalone repository.

**Comment by mogul** [comment]
If/when this happens, please make the resulting proxy-OID-provider a standalone thing so it's useful for people making apps involving something other then Django.

**Comment by toolness** [comment]
I'm wondering if we should just re-write the fake UAA in node when making it standalone. Reasons:

* Regardless of their primary implementation language, a lot of projects already use node for building their static assets--we're moving to it in #367--so node is most likely available.
* Python's packaging story *sucks*. If the standalone version has *any* dependencies, non-python projects seeking to reuse the fake UAA would have to set up a virtualenv, which is a pain. And if there are any version conflicts between the dependencies of the fake UAA and the existing project that uses it, that's a pain too.
* On the other hand, Node's packaging story is *awesome*.  Just `npm install` does everything you need. No virtual environment hassles, no dependency hell.

The fake UAA is a very small bit of code so it won't be hard to rewrite in JS too.

Thoughts?

**Comment by afeld** [comment]
If we were going to re-write it in anything, Go would probably make the most sense, since the binaries can be distributed directly, and that's most popular in the Cloud Foundry community. That being said, this issue is intended to be minimal possible effort...I was just assuming that the code would be fairly standalone already, and thus could be moved out with very little tweaking.

**Comment by toolness** [comment]
Oh, that's perfect actually--I've always wanted an excuse to actually do something with Go (I've read a few tutorials so I have some cursory familiarity with the language, but never had a reason to go further).

Just found this introductory [Writing Web Applications](https://golang.org/doc/articles/wiki/) tutorial on their wiki and it looks right up my alley.

Will let you know when I've got something going!

**Comment by toolness** [comment]
Ok, here's what I've got:

https://github.com/18F/fake-cloud.gov

It's my first Go program so there are probably tons of things I'm doing wrong. Feedback is welcome + encouraged!

I'll close this issue now, feel free to [file an issue in the new repo](https://github.com/18F/fake-cloud.gov/issues) if you like.
