### ISSUE TITLE
Manual ZAP scans are required for ATO

### ISSUE THREAD

**Issue by jseppi** [18F/calc#369]
Because we are adding authentication and Compliance Viewer does not currently support scanning pages behind any time of auth, we are going to have to manually scan and upload ZAP results, as mentioned here: https://github.com/18F/before-you-ship/blob/2ba2a1328389001c9e60765d9d1d7a321f5e6ad6/_pages/security/dynamic-scanning.md#caveats

Related: https://github.com/18F/Infrastructure/issues/649

**Comment by toolness** [comment]
Aw ok. There's no way we could add a ... uh ... back door that exists only on staging or something, I assume?  That wouldn't be very production-like, I suppose.

😁

**Comment by afeld** [comment]
> Compliance Viewer does not currently support scanning pages behind any time of auth

/cc https://github.com/18F/concourse-compliance-testing/issues/98

> add a ... uh ... back door

I would avoid this, but be very, _very_ careful if you do anything close to it.

**Comment by jseppi** [comment]
We're not. I've got ZAP running locally to test the stuff behind the auth-wall.

**Comment by toolness** [comment]
Yep, no back doors!

**Comment by jseppi** [comment]
Scan has been run and results uploaded to CALC 2.0 folder in ATOs > Work in progress.
