### ISSUE TITLE
Make a "slim" version of the site header

### ISSUE THREAD

**Issue by toolness** [18F/calc#383]
I realized when adding the style guide in #378 that our site's header is kind of tall:

> <img width="977" alt="screen shot 2016-07-13 at 11 30 05 am" src="https://cloud.githubusercontent.com/assets/124687/16809169/40463ad0-48ed-11e6-9f03-eac7823c7558.png">

Should that header be shown in its entirety on every single page on the site, or should we show a slimmed-down one (perhaps one that just contains "CALC" and the "About this tool button") on pages other than the index/homepage?

Thoughts @hbillings ?

**Comment by hbillings** [comment]
I think a slim one (like the mocks) is the way to go! I can knock that out.
