### ISSUE TITLE
Compliance - Cookie no HttpOnly Flag

### ISSUE THREAD

**Issue by jseppi** [18F/calc#384]
Caught during ZAP scan after manual seeding through login, admin screens, and logout.

> A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.

This is happening on the csrf cookie and the session cookie, but only on the session cookie when it is reset by logout. According to this stackoverflow [answer](http://stackoverflow.com/questions/33786736/session-cookie-httponly-flag-not-set-on-response-from-logout-django), that should be safe (meaning we should be able to mark it as a False Positive). We can set the csrf cookie to have the flag via https://docs.djangoproject.com/en/1.8/ref/settings/#csrf-cookie-httponly

Here is what they look like in the ZAP scan:
* session cookie on logout: `Set-Cookie: sessionid=; expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/`
* CSRF cookie: `Set-Cookie: csrftoken=<token>; expires=Wed, 12-Jul-2017 17:13:07 GMT; Max-Age=31449600; Path=/; Secure`

**Comment by toolness** [comment]
Noice!  Yeah, I much prefer plopping the CSRF token in a `<meta name="csrf-token" content="blarg">` tag than doing the weird parsing of the cookie.

**Comment by toolness** [comment]
I suppose for settings like these, where there's not really any forseeable situation where the setting would ever be *disabled*, it might be nice to have a unit test to verify, but it'd just be a nice bonus.

**Comment by jseppi** [comment]
Hrm, I tried a little and couldn't figure out how to get the `csrftoken` cookie in a test case :\

**Comment by jseppi** [comment]
FYI, looks good on staging. Note the checkboxes in the "HTTP" column in the screenshot below.

<img width="496" alt="screen shot 2016-07-14 at 2 02 29 pm" src="https://cloud.githubusercontent.com/assets/697848/16851988/a826edbe-49cb-11e6-91a0-e4accea19e37.png">
