### ISSUE TITLE
Investigate manifest inheritance

### ISSUE THREAD

**Issue by jseppi** [18F/calc#396]
Manifest inheritance was brought up during the "Intermediate/Advanced Cloud.gov" 18F class.

**Comment by toolness** [comment]
Neat! Makes me think of the way that docker-compose files can be inherited (which we use now as of #343).

**Comment by jseppi** [comment]
Docs are at https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests

**Comment by jseppi** [comment]
Our manifests are so simple right now that I don't think this will be worth it.
