### ISSUE TITLE
Consider more contrast or a border highlight in upload dragover state

### ISSUE THREAD

**Issue by jseppi** [18F/calc#397]
I'm finding it a little hard to notice the transition of background color from gray to white in the upload widget's `.dragged-over` class. Perhaps a border color change or more contrast in the two colors would work a little better.

**Comment by toolness** [comment]
Agreed! I didn't want to be too garish or flashy (or violate WCAG contrast ratio guidelines) when adding the drag-over state so I opted for being too subtle, but it would be great if it could be more noticeable.
