### ISSUE TITLE
ATO - Setup Gemnasium

### ISSUE THREAD

**Issue by jseppi** [18F/calc#404]
Looks like we might need to integrate Gemnasium for dependency analysis. It appears to be the only supported static analysis tool that does dependency analysis: https://pages.18f.gov/before-you-ship/security/static-analysis/

Related to https://github.com/18F/Infrastructure/issues/649

**Comment by toolness** [comment]
Huh, I had assumed from the name "gemnasium" that it was solely a ruby thing.

**Comment by toolness** [comment]
Isn't this taken care of now, at least as of #448?

https://gemnasium.com/github.com/18F/calc

**Comment by jseppi** [comment]
Yup, this is done!
