### ISSUE TITLE
Implement price list alert component

### ISSUE THREAD

**Issue by toolness** [18F/calc#414]
From the mockups:

> <img width="500" alt="screen shot 2016-07-19 at 4 22 27 pm" src="https://cloud.githubusercontent.com/assets/124687/16965196/15422e40-4dcd-11e6-871e-8f55a498b190.png">

Trammell mentioned that we might want to consider starting the alert component out as expanded instead of collapsed. If that's the case, we could potentially avoid implementing the collapse/expand interaction (and associated aria attributes, manual screen reader testing, automated unit testing, etc).

**Comment by hbillings** [comment]
There are some styles for alerts here: https://standards.usa.gov/alerts/

**Comment by jseppi** [comment]
@hbillings: Should we indepently pull styles we want to use, or should we instead integrate the entire USWDS?

**Comment by jseppi** [comment]
As discussed in Slack, I'll be implementing this with expand/collapse functionality and the capability to specify a "default" state so that we can have it start expanded or collapsed.

**Comment by jseppi** [comment]
Closed by https://github.com/18F/calc/pull/435
