### ISSUE TITLE
Create help widget

### ISSUE THREAD

**Issue by toolness** [18F/calc#416]
The mockups have this:

> <img width="350" alt="screen shot 2016-07-19 at 4 43 00 pm" src="https://cloud.githubusercontent.com/assets/124687/16965960/71e9df14-4dd0-11e6-83a4-a28d77ed1393.png">

I'm not sure what the interaction model is there but we gotta do it!

That said, we should also keep in mind the "Don't hide basic helper text" advice from [Design Better Forms](https://uxdesign.cc/design-better-forms-96fadca0f49c#.3uh59u4y6). I assume the reason @hbillings used the widget here is because the definition of "small business" might not qualify as "basic helper text".

**Comment by hbillings** [comment]
I wasn't entirely sure what the definition of a small business was, heh. Maybe it's short enough to qualify as basic helper text! I'm also not sure if there are other items on this page that need explanation to the average bear.

As far as interaction, I was just thinking of using the tooltip that's already part of CALC. Thoughts?

**Comment by toolness** [comment]
Good point, I had forgotten about our use of tooltipster!  I think that's fine, though we might want to make the tooltips keyboard-accessible too (just filed #421 about this).

**Comment by toolness** [comment]
In #436 I just used `form.as_p()` to display the relevant form here. We'll probably need to change it (or make a custom django form widget) to display this tooltip/widget thingy.

**Comment by toolness** [comment]
It looks like we're going to try *not* having tooltips like this if at all possible, so I'm going to close this issue for now... we can re-open it later if needed.
