### ISSUE TITLE
Decide if we need new table styling

### ISSUE THREAD

**Issue by toolness** [18F/calc#417]
I'm not sure if we can/should reuse the data explorer's table styling or not, but this is how tables appear in the mockups for the capture tool:

> <img width="603" alt="screen shot 2016-07-19 at 4 52 34 pm" src="https://cloud.githubusercontent.com/assets/124687/16966201/77cc12ac-4dd1-11e6-9dcc-aa89a1f162e2.png">

**Comment by toolness** [comment]
Also determine whether we want the tables to be sortable.

**Comment by toolness** [comment]
Also consider documenting how to use/style the table in the style guide.

**Comment by jseppi** [comment]
http://joequery.github.io/Stupid-Table-Plugin/

**Comment by hbillings** [comment]
There's a lot going on in the data explorer table scss that I don't really want to mess with. I'm going to see if I can abstract out the common styles, and then leave some of the messier stuff in a `_data_explorer_tables` file.
