### ISSUE TITLE
Setup SCSS Lint in ultratest and in gulp

### ISSUE THREAD

**Issue by jseppi** [18F/calc#426]
~~We are using csslint in CodeClimate~~ We should have SCSS Lint in CodeClimate, and it would be good to have local runners for it. I haven't looked into yet, but it should be fairly easy to add to both gulp and ultratest.

**Comment by jseppi** [comment]
Ew, `scss-lint` requires ruby and the scss-lint gem. If we want local sass linting, then [sass-lint](https://github.com/sasstools/sass-lint) seems like the way to go.
Unfortunately, CodeClimate only has support for scss-lint, so we'd potentially be a bit out of sync with those two.

**Comment by jseppi** [comment]
@hbillings is sass linting something you'd be interested in having? I don't actually know how useful it is.

**Comment by hbillings** [comment]
Sass linting is nice, but requiring Ruby just to run it...not worth it, IMO.

**Comment by jseppi** [comment]
@hbillings: FYI, I turned on scss-lint in CodeClimate's in https://github.com/18F/calc/pull/451 as an experiment. It is using their default lint config (https://github.com/brigade/scss-lint/blob/master/config/default.yml), and it found 498 issues: https://codeclimate.com/github/18F/calc/pull/451

**Comment by toolness** [comment]
hey it's all good we've got DOCKER!  extra languages, no problemo!

are there any linters written in fortran?  we could use some fortran.

**Comment by jseppi** [comment]
There's also stylelint, for which we have an 18F-specific setup: https://github.com/18F/stylelint-rules

I tried real quick to get get it running, but it never seemed to report any issues. Also, it is unsupported on CodeClimate.
