### ISSUE TITLE
Prefix SASS component and base file names with underscore

### ISSUE THREAD

**Issue by jseppi** [18F/calc#433]
Not really a pressing issue, but SASS partials/components/whatever you want to call them, should have their filenames prefixed with `_`.

Example: instead of `components/footer.scss`, it should be `components/_footer.scss`.

The reason to do this is that any SASS files that are prefixed with `_` won't be written as output files when they are compiled.

Right now our SASS build outputs all kinds of files that won't actually be used (see screenshot):

<img width="227" alt="screen shot 2016-07-21 at 1 45 43 pm" src="https://cloud.githubusercontent.com/assets/697848/17034741/9c2cd4fa-4f49-11e6-8fbd-aaa14d90f6d6.png">

**Comment by jseppi** [comment]
That was weird. I didn't mean to assign you, Aaron. I had assigned Heather, but accidentally hit the back button. When I came back to the page it showed no assignees, but then when I created the issue it assigned Aaron. o_O

**Comment by hbillings** [comment]
...how did I even. I swear these were underscored at one point. Thanks for catching -- will fix! Unless Aaron gets to it first. ;-)
