### ISSUE TITLE
Multiple "rebundling" messages from gulp slow down JS bundling

### ISSUE THREAD

**Issue by toolness** [18F/calc#437]
While working on #436 I noticed that i was starting to receive lots of `Rebundling <filename>` messages from gulp, and gulp was getting slower and slower at rebundling my files (my hunch is that it's rebundling the same content multiple times in parallel but I'm not sure).

The following output only shows gulp repeating the rebundling message only 4 times, but it seems to add another every time I make a change to one of `index.js`'s dependencies and save it. Once I've been working for an hour or two, the bundle takes several seconds to fully regenerate.

<details>
<summary>Gulp output</summary>
```
gulp_1  | [22:25:08] Starting 'lint'...
gulp_1  | [22:25:08] Starting 'js:data-capture'...
gulp_1  | [22:25:08] Finished 'js:data-capture' after 2.36 ms
gulp_1  | [22:25:08] Starting 'js:data-explorer:index'...
gulp_1  | [22:25:08] Starting 'js:common:base'...
gulp_1  | [22:25:08] -> Rebundling hourglass_site/static_source/js/data-capture/index.js
gulp_1  | [22:25:08] -> Rebundling hourglass_site/static_source/js/data-capture/index.js
gulp_1  | [22:25:09] -> Rebundling hourglass_site/static_source/js/data-capture/index.js
gulp_1  | [22:25:09] -> Rebundling hourglass_site/static_source/js/data-capture/index.js
gulp_1  | [22:25:09] Finished 'js:common:base' after 478 ms
gulp_1  | [22:25:09] Finished 'js:data-explorer:index' after 487 ms
gulp_1  | [22:25:09] Starting 'js:legacy'...
gulp_1  | [22:25:09] Finished 'js:legacy' after 13 μs
gulp_1  | [22:25:10] 
gulp_1  | /calc/hourglass_site/static_source/js/data-capture/step_1.js
gulp_1  |   64:11  warning  Unexpected alert  no-alert
gulp_1  |   70:9   warning  Unexpected alert  no-alert
gulp_1  | 
gulp_1  | ✖ 2 problems (0 errors, 2 warnings)
gulp_1  | 
gulp_1  | [22:25:10] Finished 'lint' after 1.69 s
gulp_1  | [22:25:10] Starting 'js'...
gulp_1  | [22:25:10] Finished 'js' after 12 μs
```
</summary>

**Comment by jseppi** [comment]
Very strange...

Does that multiple rebundling only happen after many saves, or does it happen as soon as you start the gulp build?

**Comment by toolness** [comment]
It starts out with none, and then the number of rebundles increases by 1 every time I save.
