### ISSUE TITLE
Figure out what to do with eslint in dockerized gulp

### ISSUE THREAD

**Issue by jseppi** [18F/calc#441]
Ref https://github.com/18F/calc/pull/429#issuecomment-234620198

I think these are the options:

1. Disable that check in our `.eslintrc`. I like that check but it seems to be creating problems with the dockerized version.
1. Figure out a way to turn off the import rule just in docker. We're already doing that for `ultratest` but not for `gulp`. I think we could make a new gulp task (maybe `docker-watch`) that is just like the current `watch` task, but that disables the import rule.
1. Anyone using the dockerized version could just ignore those eslint errors from the gulp container.

**Comment by jseppi** [comment]
Oh, actually we could check env for `DDM_IS_RUNNING_IN_DOCKER` (we'd have to add that to docker-compose.local.yml), and then use its presence to decide to set that rule via an option to gulp-eslint: https://github.com/adametry/gulp-eslint#optionsrules.

I can get this done real quick.

**Comment by jseppi** [comment]
The env var flag actually needed to go into the Dockerfile so that it is present during the image build, not just when running a container. I made one called `IS_IN_DOCKER` and check for it in the `gulpfile.js`.

**Comment by toolness** [comment]
Thanks for looking into this!

Actually, I think it's ok for us to just make `DDM_IS_RUNNING_IN_DOCKER` be defined in the `Dockerfile`, rather than in one of the compose YAMLs.  Want to just move it there and reuse it, so we don't have to define multiple "are we running in docker" env vars?
