### ISSUE TITLE
Have pyflakes ignore line lengths in auto-generated migrations

### ISSUE THREAD

**Issue by toolness** [18F/calc#443]
When working on #407, I noticed that running `autopep8 -i -r .` on our codebase didn't fix the line length on our migrations, so I had to fix them up manually in a [separate commit](https://github.com/18F/calc/pull/407/commits/9667a78f095f28b8c46fc9a782474503af2e3842#diff-f6a4dadc9ef277df9da3d9708cfee7c8). This was a bit annoying.

Now, in working on #436, I'm noticing that the migrations auto-generated by `manage.py makemigrations` aren't being auto line-wrapped either, and there are about a dozen `E501 line too long` violations.

Does anyone mind if I either disable pep8 testing for `migrations` directories, or (if it's possible) disable rule `E501` on them?

**Comment by jseppi** [comment]
I don't mind
