### ISSUE TITLE
Character encoding issue in data table

### ISSUE THREAD

**Issue by jseppi** [18F/calc#449]
![screen shot 2016-07-26 at 3 26 22 pm](https://cloud.githubusercontent.com/assets/697848/17154181/849491c0-5345-11e6-927d-7cc810a4be5e.png)

**Comment by jseppi** [comment]
The encoding issue occurred somewhere along the translation from the original XLSX file to the CSV that CALC imported.

Original Excel file:
![screen shot 2016-10-04 at 2 25 22 pm](https://cloud.githubusercontent.com/assets/697848/19089100/8065cff8-8a3e-11e6-93b1-99728b4a8c90.png)

CSV version of original Excel file:
![screen shot 2016-10-04 at 2 23 09 pm](https://cloud.githubusercontent.com/assets/697848/19089016/2ee75002-8a3e-11e6-9e8b-076e84d5c93c.png)

**Comment by jseppi** [comment]
I just confirmed that with the Region 10 Bulk Upload flow, the characters are handled correctly 🎉 

![screen shot 2016-10-04 at 2 30 30 pm](https://cloud.githubusercontent.com/assets/697848/19089246/22182f26-8a3f-11e6-9e47-5613b1437987.png)

**Comment by toolness** [comment]
Oh, awesome!!! 🎉
