### ISSUE TITLE
First column of data explorer table can be too wide, causing the table to have horizontal scroll

### ISSUE THREAD

**Issue by jseppi** [18F/calc#450]
![screen shot 2016-07-26 at 3 28 39 pm](https://cloud.githubusercontent.com/assets/697848/17154270/e449e980-5345-11e6-939b-75fa84ea7642.png)

**Comment by hbillings** [comment]
We could potentially set a `max-width` on the `th.column-labor_category` rule. That would look something like this: 
![screen shot 2016-07-28 at 2 26 32 pm](https://cloud.githubusercontent.com/assets/509309/17226478/52c0f1f8-54cf-11e6-848c-924b9128eacb.png)

Or we could just make the table look scrollable, perhaps by adding a more obvious scrollbar.

**Comment by jseppi** [comment]
I think setting that `max-width` would be good.

**Comment by jseppi** [comment]
This is fixed, correct, @hbillings?
