### ISSUE TITLE
Consider moving data-capture JS into the data-capture app

### ISSUE THREAD

**Issue by toolness** [18F/calc#455]
In #436 I added the JS to `hourglass_site/static_source/js/data-capture` because that's the folder that already existed, but it feels a bit weird to have the app's front-end JS not actually live in the `data_capture` app folder.

@jseppi should we move it to `data_capture/static_source/js` and change the gulpfile to build from there instead?

**Comment by toolness** [comment]
This issue is also a bit similar to #393 so it might be useful to tackle them both in one PR, if they're both deemed to be good ideas.

**Comment by jseppi** [comment]
Moving the data capture JS to the `data_capture` app sounds like a good idea to me.

**Comment by jseppi** [comment]
Closing in favor of #489
