### ISSUE TITLE
Remove the "Tell us you'd like your schedule added to CALC" link for now

### ISSUE THREAD

**Issue by toolness** [18F/calc#457]
In #436 I added this link because it was in the mockups, but I didn't know what the link was supposed to do, so I just had it pop up an alert that says "TODO IMPLEMENT THIS". We should make it actually do something useful, or remove the call to action entirely.

**Comment by jseppi** [comment]
This is probably out of scope for this sprint, no? We're only going to be user testing against a group for which we have their schedule, and we don't have an email or contact to send this to.

**Comment by toolness** [comment]
Yeah, that's true, we could move it to the tech debt cleanup milestone if we want.

**Comment by hbillings** [comment]
Yeah, I'm not sure how this should work, given that addition of new schedules might mean more tech work is necessary to parse them. Maybe ultimately it just goes to a Google Form or the like where interest can be registered over time.

**Comment by jseppi** [comment]
@toolness: perhaps best to remove it now and add a card to the trello backlog? It's not really a technical debt thing in my opinion, but a separate feature.

**Comment by toolness** [comment]
Oh yeah, good idea! Will bust out a PR to remove it.

**Comment by toolness** [comment]
Um, I also just realized that because even viewing step 1 requires login, there's actually no way for a CO whose schedule is unsupported by CALC to even view this page, as it would've meant that Kelly (or some other admin) would've had to create an account for them first, in which case the need for the new schedule would've already been known.

So it's a good thing we didn't implement anything here.

Anyways, replacing the CTA with [this trello card](https://trello.com/c/njr9gJ2m/84-as-a-co-whose-schedule-isn-t-yet-supported-by-calc-i-would-like-a-way-to-contact-the-calc-team-so-they-can-add-support-for-my-sc).

**Comment by jseppi** [comment]
Ha, that's true! Good realization!

**Comment by toolness** [comment]
Props to the agile process: I didn't actually have the realization until I wrote the user story for it in the trello card 😁
