### ISSUE TITLE
Multi-word autocomplete doesn't behave as expected

### ISSUE THREAD

**Issue by toolness** [18F/calc#458]
In the data explorer (i.e. CALC 1.0), with the main search field set to its default setting of **Contains words**, @tram discovered that typing "interpretation" yields the following results:

> ![interpretation-query](https://cloud.githubusercontent.com/assets/124687/17174948/f3d1b026-53d2-11e6-99be-3a75d79aa397.png)

However, attempting to make the query more specific by searching for "interpretation services" yields the following:

> ![interpretation-services-query](https://cloud.githubusercontent.com/assets/124687/17174978/0f0e6884-53d3-11e6-8bae-3792b856b3a7.png)

This is unexpected; one would think that the second result set would be a strict subset of the first. Instead, the results in the second don't even seem to have anything to do with the word "interpretation" at all.

The behavior doesn't seem to change at all if we switch the second search to **Exact match**.  Changing it to **Contains phrase** yields a different result set that is somewhat similar to the first result set, but not quite (it's still not a strict subset).

**Comment by jseppi** [comment]
At quick glance, it looks like the actual results (those that are shown in the table) do respond as expected to the different radio button selections. It seems to just be the auto-complete search results that are incorrect.
