### ISSUE TITLE
Make failed form submission in data capture app more obvious

### ISSUE THREAD

**Issue by toolness** [18F/calc#459]
In #436 I didn't add any kind of alert to tell the user that their form submission was invalid; instead, the form is just re-displayed with errors on it.  We might want to display a big alert near the top of the page that says something along the lines of "Your form submission was invalid" so that users have a better context about why they're still looking at the same form they just filled out.

We could potentially do this by:

* Using Django's [messages framework](https://docs.djangoproject.com/en/1.9/ref/contrib/messages/) in our base template to display any queued messages for the user to see.  This might be tricky to integrate with the ajax form submission in step 1, though, since we don't actually do a full-page refresh there.

* Just hard-coding some logic in the form templates that contains an `{% if form.errors %}` that conditionally displays a custom alert.

**Comment by jseppi** [comment]
Happy to take this one on if cool with you, @toolness.
