### ISSUE TITLE
Implement schedule 70 importer for data capture app

### ISSUE THREAD

**Issue by toolness** [18F/calc#460]
In #436 I added an architecture for supporting gleaning data from multiple schedules' price lists, and a stubbed-out a schedule 70 gleaner, but it just raises a `ValidationError` with a TODO in it right now.

We should pull out the XLS scraping logic from #275 and use it as the basis for the real thing.  After that we can finally close #275, since it won't be needed anymore.

One question I have about this one is in regards to whether we can make the [IT Schedule 70 PPL with one Labor Category Row filled out](https://docs.google.com/spreadsheets/d/1q8XTOpbWz3e56DOiWAUU0-GbzrvxlwCc5pzoWRGChTA/edit#gid=1245479766) public by adding it to the repository for use by the test suite. I'm hoping we can, because it doesn't actually contain any proprietary information... I guess if needed we could remove all the content from the other worksheets we don't use.

**Comment by jseppi** [comment]
Based on clarification from Kelly, we can add the spreadsheet to the repo as long as it does not have real data in it.
