### ISSUE TITLE
Verify the valid values for Contract.business_size

### ISSUE THREAD

**Issue by toolness** [18F/calc#462]
In #436 I intuited, by looking at the schedule 70 CSV, the valid values for `Contract.business_size`, and encoded them in `SubmittedPriceList.get_business_size_string()`:

```py
    def get_business_size_string(self):
        # TODO: Based on contracts/docs/s70/s70_data.csv, it seems
        # business size is either 'S' or 'O'. Assuming here that
        # 'S' means 'Small Business' and 'O' means 'Other'
        # but WE REALLY, REALLY NEED TO VERIFY THIS.

        if self.is_small_business:
            return 'S'
        return 'O'
```

However, we need to be 100% sure of this, so I'm filing this issue to make sure we do that.

**Comment by jseppi** [comment]
Those two options are also corroborated by all the tests from CALC 1 and `api/views.py`, though they are lowercased in those places.

**Comment by jseppi** [comment]
Kelly responded today in stand-up that they are the only values he knows of for Sched 70 and Region 10, but that he will double-check.

**Comment by toolness** [comment]
Cool! I also just noticed in `contracts/models.py`:

```py
    def get_readable_business_size(self):
        if 's' in self.business_size.lower():
            return 'small business'
        else:
            return 'other than small business'
```

So it looks like we're following the assumptions of the CALC 1.0, at the very least.

**Comment by jseppi** [comment]
As per today's discussion with Kelly in stand-up, we're good to go with this assumption for now. We can open a new issue later if another schedule introduces different requirements.
