### ISSUE TITLE
Figure out whether/how to deal with non-field errors in uploaded price list rows

### ISSUE THREAD

**Issue by toolness** [18F/calc#463]
In #436 we use Django's form engine to validate individual rows from uploaded price lists--we don't actually *render* these as forms, but we do use the underlying framework for validation.

One of the properties of this form framework is that it has a concept of [non-field errors](https://docs.djangoproject.com/en/1.9/ref/forms/api/#django.forms.Form.non_field_errors), which are errors with a form (or in this case, a row in a price list) that aren't associated with a particular field.

I'm not sure if this concept applies to any of the schedules we're importing; it could be the case that any validation errors we encounter are *always* associated with a particular field.

In any case, we're not currently rendering non-field errors, and there's a TODO in the code to figure out if we need to.

If it's determined that we need to, we'll need to come up with styling for it, and implement it.

If it's determined that we don't need to, we should remove the TODO.  We might also want to add some validation logic in the `BasePriceList` class, or somewhere else, that verifies that the invalid rows from a price list gleaning don't contain any non-field errors.

**Comment by jseppi** [comment]
The `TODO` comment mentioned in this issue appears to be gone, and it looks like we have `{{ form.non_field_errors }}` in all the templates that would need them. Is this good to close, @toolness?

**Comment by toolness** [comment]
Sure, that sounds good to me!
