### ISSUE TITLE
Ultratest - add coverage report

### ISSUE THREAD

**Issue by jseppi** [18F/calc#469]
I think it would be nice to output the coverage report table that `py.test --cov` generates as part of ultratest.

**Comment by toolness** [comment]
That would be cool!

I think ideally it'd be nice if the non-verbose mode just printed the percentage coverage of all the code, while `-v 2` would display more stats on coverage of each individual file, but I'm not sure how hard that'd be.

**Comment by jseppi** [comment]
Cool, I think that would be pretty easy.
