### ISSUE TITLE
Investigate better XLS gleaning criteria for Schedule 70

### ISSUE THREAD

**Issue by toolness** [18F/calc#474]
In #467 we added a scraper that consumes the following Excel spreadsheet starting at row 4 and continuing until a **SIN(s) PROPOSED** column is found to be blank:

<img width="786" alt="screen shot 2016-07-29 at 6 41 36 am" src="https://cloud.githubusercontent.com/assets/124687/17246029/8cb28c9a-5557-11e6-87ec-aeb90e6cf315.png">

However, in https://github.com/18F/calc/pull/467#discussion_r72653609, @jseppi brought up some fragilities with this approach:

> I wonder if we can make this more robust. I'm worried about just checking the first cell of each row especially since I could easily see a spreadsheet coming in where the price list 'table' runs all the way down to the `Most Favored Customer’s Discount or Discount Range (MFC) __________.` cell.
>
> Something also fragile, though maybe less so, could be to check across the entire width of the table for values being present?

@jseppi implemented this approach in #473, to which I responded in https://github.com/18F/calc/pull/473#issuecomment-236086582 with the trade-offs I perceived.

Not sure what to do now--whether we wait for more samples of filled-out forms to come in, or attempt to pro-actively add more resilience to the scraping.

**Comment by jseppi** [comment]
related: #683

**Comment by jseppi** [comment]
I think we can close this now. We can open separate, targeted issues based on observations of actual usage problems.
