### ISSUE TITLE
Hover styling on invalid rows table is grody

### ISSUE THREAD

**Issue by toolness** [18F/calc#483]
I'm pretty sure this is well-known and going to be fixed soon, but I just wanted to make sure it was catalogued:

![screen shot 2016-07-29 at 2 57 13 pm](https://cloud.githubusercontent.com/assets/124687/17260595/58fa758c-559f-11e6-8fc5-d2b84dca8ad3.png)

In the above screenshot, my mouse is hovered over the yellow row--it looks fine when I'm not hovering over it.

**Comment by jseppi** [comment]
This appears to be taken care of by #452

**Comment by toolness** [comment]
Yeah, woot!
