### ISSUE TITLE
Move static_source to top-level folder

### ISSUE THREAD

**Issue by jseppi** [18F/calc#489]
For better organization, and ease of development (especially for newcomers), we're going to move all of the static "source" files (ES6 files, SCSS) into a top-level directory (and out of hourglass_site).

**Comment by jseppi** [comment]
Related: #393

**Comment by jseppi** [comment]
Should hold on this until #452 is merged since there are a fair amount of structural changes in that PR.

**Comment by toolness** [comment]
Sounds good!  Also would be nice, I think, to mention the location in our README so newcomers who want to go straight for the front-end know where to look.
