### ISSUE TITLE
Address typography

### ISSUE THREAD

**Issue by hbillings** [18F/calc#490]
Typography needs to be declared more specifically -- right now it's cobbled together from what was there before and what the standards declare for a completely different font.

Examples:
- Raleway is getting picked up in weird places

- Line height's not right on some dropdowns:
![screen shot 2016-08-02 at 10 19 00 am](https://cloud.githubusercontent.com/assets/509309/17334116/a061cfb2-589a-11e6-8392-8c30f6a1cc2d.png)

- How many heading sizes do we need?? (actually this is an h5, a legend label, and a fieldset legend, respectively)
![screen shot 2016-08-01 at 5 32 09 pm](https://cloud.githubusercontent.com/assets/509309/17311043/ed37a574-580d-11e6-94af-5edff919738a.png)

- this leading is ugh:
![screen shot 2016-08-01 at 5 32 37 pm](https://cloud.githubusercontent.com/assets/509309/17311061/0d2b4d5e-580e-11e6-9b7d-abcda52bab83.png)

**Comment by jseppi** [comment]
I also noticed yesterday that the "Typography" section of the styleguide is empty currently, so it might be good to fill that out once things have been addressed.

Ref: https://github.com/18F/calc/blob/develop/styleguide/templates/styleguide.html#L25
