### ISSUE TITLE
Header rows on tables should not have a hover style

### ISSUE THREAD

**Issue by hbillings** [18F/calc#493]
Noticed in the sprint demo that the header row on tables was picking up a highlight style. That shouldn't happen.

**Comment by jseppi** [comment]
Actually I think that is a markup bug in the valid rows table in `step_2.html`. It doesn't have `<thead>` and `<tbody>` sections.

Ref: https://github.com/18F/calc/blob/develop/data_capture/templates/data_capture/step_2.html#L75

**Comment by hbillings** [comment]
Well then that's easy! ^_^
