### ISSUE TITLE
Format "Price Offered" column in Step 2 valid rows table as currency

### ISSUE THREAD

**Issue by jseppi** [18F/calc#495]
<img width="231" alt="screen shot 2016-08-01 at 11 23 35 am" src="https://cloud.githubusercontent.com/assets/697848/17300988/79e03c04-57da-11e6-9188-3af4497eac84.png">

**Comment by jseppi** [comment]
Actually, what do we think here @toolness? Should we format, or should we present those values as "raw data?"

I think at the very least it we should make each value have at least the hundredths place decimal so that we don't get values like `1.2`.

**Comment by jseppi** [comment]
Also it might be good to right-align the text in that column so that the numbers line up in a way that is easier to visually compare.

**Comment by toolness** [comment]
Hmm, I like the idea of formatting it properly--it's what's most relevant to the user, and @hbillings' original mockups *did* format them properly, I was just lazy when implementing, sorry. 😣

**Comment by jseppi** [comment]
I took a quick look at this, and was expecting to find that Django fields would have some kind of method for specifying how to stringify them, but couldn't find anything like that in the documentation.

Then I realized perhaps the best thing to do for the `price_including_iff` might be to have a custom cleaner for it that ensures it has a precision of 2.

**Comment by jseppi** [comment]
Closed by https://github.com/18F/calc/pull/660
