### ISSUE TITLE
Make contract year and start/end date required in data capture?

### ISSUE THREAD

**Issue by toolness** [18F/calc#498]
Yup.

**Comment by toolness** [comment]
Did a quick hack for this in https://github.com/18F/calc/pull/503.

**Comment by toolness** [comment]
Note that a user research interview yesterday indicated that perhaps start/end date shouldn't be required, but we need to verify this.

**Comment by jseppi** [comment]
Do we have a definitive answer on this whether start and end date should be required? cc @tram

**Comment by tram** [comment]
IIRC, we saw in a session that we thought we wouldn't need it, but then Kelly said we should force it to be added. Will double check during standup.

**Comment by jseppi** [comment]
This is a "yes" unless I hear otherwise.

**Comment by tram** [comment]
Oops! This is a "yes".
