### ISSUE TITLE
Make "is small business" a radio button

### ISSUE THREAD

**Issue by toolness** [18F/calc#499]
I guess the options in the radio button should be something like:

* This is a small business.
* This is something other than a small business.

... or something?  Thoughts on the wording @jseppi @hbillings ?  I guess we could ask on `#g-content` or the writing lab too.

**Comment by jseppi** [comment]
Maybe just keep it simple like:

**Business Size**
- [ ] Small business
- [ ] Not a small business

**Comment by hbillings** [comment]
Or even, "this is a small business: y/n"

**Comment by toolness** [comment]
Cool.

Did a quick fix for this in https://github.com/18F/calc/pull/503, which requires the user to make an explicit choice (I think this is what Kelly wanted?):

![screen shot 2016-08-02 at 7 34 15 am](https://cloud.githubusercontent.com/assets/124687/17327076/8c4b4f74-5883-11e6-903e-218c6921a494.png)

Technically it's not a radio button, but the default styling for the radios looked totally janky. We can revisit though!

**Comment by toolness** [comment]
Also I think according to Alice Bartlett's [Burn Your Select Tags](https://www.youtube.com/watch?v=CUkMCQR4TpY) talk, we might want to convert not only this one to radio buttons, but the other "Contractor Site" one too...

**Comment by hbillings** [comment]
Yeah, I'm a big fan of not using selects unless the list is huge or space
is tight. I noticed the odd radio button styling yesterday; will look into
it today.
>
>

-- 
Heather Battaglia
Innovation Specialist, 18F
Chicago, IL
