### ISSUE TITLE
Burdened donkey row looks a bit wonky on narrower screens

### ISSUE THREAD

**Issue by toolness** [18F/calc#512]
At slightly narrower screens, it seems like the padding between the row and the end of the header's blue region is increased a lot, and the word "Wages" appears flush up against the burdened donkey's feet:

> ![screen shot 2016-08-02 at 3 39 02 pm](https://cloud.githubusercontent.com/assets/124687/17345460/304a1b14-58d4-11e6-886f-85f4932f3c83.png)

On much narrower screens, things get more disjointed:

> ![screen shot 2016-08-02 at 5 11 02 pm](https://cloud.githubusercontent.com/assets/124687/17345474/370bf17a-58d4-11e6-9886-43fa352f264d.png)

I guess we could classify this under "make the whole site responsive" but I figured I'd document it.

**Comment by hbillings** [comment]
Linked to https://trello.com/c/xue8KGLC/42-add-more-breakpoints-to-responsive-design

**Comment by toolness** [comment]
Also, from the screenshot in #535, it seems IE11 sometimes displays the icons below where they're supposed to be.  I don't think this is a *huge* deal b/c it doesn't impact functionality and most users will hopefully be using chrome, but if it's easy, it would be nice to fix.
