### ISSUE TITLE
Upload widget fails on IE11

### ISSUE THREAD

**Issue by toolness** [18F/calc#520]
Unfortunately, today's user test participant was on IE 11 (11.0.9600.18376 to be precise) and after dropping their file into the widget and clicking "next", nothing happened.  I ended up having to add a `data-force-degradation` to the widget and re-deploy for the interview to proceed. 😭 

When I originally wrote the upload widget, I did test on IE11, but I was less vigilant about testing some of the improvements we've made since then... Need to either fix this ASAP or add the `data-force-degradation` to #503 so it sticks for now.

**Comment by toolness** [comment]
Ok, trying it out on IE11 gives me:

```
Object doesn't support property or method 'delete'
```

So it looks like `FormData.prototype.delete()` may not be a method on IE11, even though `FormData` itself exists. BLEGH.

**Comment by jseppi** [comment]
Looks like instead of using delete to remove the file, we could construct the the formdata a little differently. Like by looping through the form fields and appending everything.
