### ISSUE TITLE
Optional filters look a bit wonky now

### ISSUE THREAD

**Issue by toolness** [18F/calc#521]
Hmm, at some point the "optional filters" section of the data explorer got a bit wonky.

This is how they looked before (and currently, on calc.gsa.gov):

<img width="240" alt="screen shot 2016-08-04 at 11 44 43 am" src="https://cloud.githubusercontent.com/assets/124687/17408367/f3f512b6-5a38-11e6-9871-6359481d82fe.png">

Now they look like this:

![screen shot 2016-08-04 at 11 06 17 am](https://cloud.githubusercontent.com/assets/124687/17408377/fbfe3fbe-5a38-11e6-8bd4-129a9d995c5b.png)

The font change is intentional, I believe, but the size of the labels is odd.

Also, the "Education level" drop-down is supposed to look like this:

<img width="202" alt="screen shot 2016-08-04 at 11 46 31 am" src="https://cloud.githubusercontent.com/assets/124687/17408421/220b6484-5a39-11e6-86b8-9030343e34a5.png">

But now it looks like this:

![screen shot 2016-08-04 at 11 06 31 am](https://cloud.githubusercontent.com/assets/124687/17408425/28df51e4-5a39-11e6-9a5c-988dada9b0f7.png)

**Comment by jseppi** [comment]
Looks like all the headings are now using Raleway instead of Lato. Also I think the `_reset.scss` partial is not being imported in `main.scss` any more.

<img width="742" alt="screen shot 2016-08-05 at 12 16 03 pm" src="https://cloud.githubusercontent.com/assets/697848/17447991/98e381fe-5b06-11e6-809c-0f639e0ec364.png">

**Comment by hbillings** [comment]
The headings bit should be addressed by #490. The education dropdown bug is weird! I'll check on that and the `reset` import.

**Comment by toolness** [comment]
Fixed by #558!
