### ISSUE TITLE
Log client-side JS errors

### ISSUE THREAD

**Issue by toolness** [18F/calc#522]
When we were doing the user research interview today and the upload widget failed (filed as #520), I realized there's no way we would've known about it if we hadn't been directly observing the user.

I know New Relic does support front-end monitoring for this sort of thing, but I'm not sure if we have it enabled, or if we even have access to that part of their suite.  But we need something!

**Comment by jseppi** [comment]
Hrm, looks like we do have new relic's javascript thingy enabled. Here's a screenshot from my dev console on calc-dev.apps.cloud.gov:

<img width="178" alt="screen shot 2016-09-01 at 3 37 01 pm" src="https://cloud.githubusercontent.com/assets/697848/18183466/23cf47d6-705a-11e6-8100-ca4e08b4d82b.png">

**Comment by jseppi** [comment]
But we don't have the advanced features enabled. I've asked about enabling them in Slack.

<img width="444" alt="screen shot 2016-09-01 at 3 40 08 pm" src="https://cloud.githubusercontent.com/assets/697848/18183865/f0503f58-705b-11e6-99fa-b335bec3b99a.png">

**Comment by jseppi** [comment]
New Relic Browser's advanced features have been enabled.
