### ISSUE TITLE
Fake cloud.gov doesn't work with some versions of IE

### ISSUE THREAD

**Issue by toolness** [18F/calc#524]
When conducting a user research interview, one of our participants got stuck in a loop in fake cloud.gov login whereby entering their email address sent them right back to the login screen, with the email field blank.  It looked like it wasn't adding the email field to the querystring when submitting the form or something.

Unfortunately, we weren't able to figure out what version of IE they were using, but it definitely looked like IE (not Edge or some other browser).

That said, another participant earlier today had no problem logging in via fake cloud.gov on IE 11.

**Comment by jseppi** [comment]
Maybe cookies were disabled or something?

**Comment by jseppi** [comment]
@toolness: I am going to close this as `wontfix` or `cantreproduce`. It can be re-opened if it comes up again.
