### ISSUE TITLE
Sticky footer messes up page on IE11

### ISSUE THREAD

**Issue by toolness** [18F/calc#535]
Blugh, apparently [IE11 has tons of flexbox bugs](http://caniuse.com/#search=flexbox) and makes the sticky footer added in #513 look like this:

<img width="996" alt="screen shot 2016-08-08 at 4 27 31 pm" src="https://cloud.githubusercontent.com/assets/124687/17495045/6a4475b6-5d85-11e6-8d8d-7ca3dd7bf566.png">

Will need to either revert it or add all the weird workarounds that make it not look horrible.

**Comment by toolness** [comment]
Ok, I've reverted it for now on our user testing branch in 1191aff426bb3592d8af2453ddd87fdbc6e86624, since it's almost COB and we're user testing early tomorrow.

I'd like to spend a little while seeing if it's easy to fix on IE11, but if it's not, I guess we can revert it on `develop` too.

**Comment by jseppi** [comment]
Classic IE

**Comment by toolness** [comment]
Yeah, browsers with flexbox bugs are particularly annoying because the page actually looks fine on browsers that don't support flexbox at all (the footer just isn't sticky on them). :(
