### ISSUE TITLE
proposed-price-block margin is too big

### ISSUE THREAD

**Issue by jseppi** [18F/calc#560]
![image](https://cloud.githubusercontent.com/assets/697848/17686207/3ddc1e88-6330-11e6-9a44-a84e07f5cc16.png)

The block only shows up when you enter a Proposed Price in the box at the upper right of the bar chart. Probably needs to be added to the rules like in https://github.com/18F/calc/pull/558/commits/4809d65aae220e73273288422abdbbc6cef08954
Though maybe a single class for all three of the blocks would be easier to manage...

**Comment by hbillings** [comment]
👍  to the single class.
