### ISSUE TITLE
Improve docker node_modules

### ISSUE THREAD

**Issue by jseppi** [18F/calc#569]
Per article at http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
as discussed/used in Checklistomania: https://github.com/18F/checklistomania/pull/100#issuecomment-240492439

**Comment by toolness** [comment]
Hmm, so I just realized that the lines of our `Dockerfile` that make it possible to deploy our container to the cloud contain the following:

```
COPY . /calc/
```

that means that if the user has `node_modules` at the time that they build the container, it could overwrite `/calc/node_modules` in the container, which could lead to unpredictable results... Blergh.

**Comment by toolness** [comment]
Ack, ignore my last comment--I completely forgot about `.dockerignore` and the fact that ours has `node_modules` in it. Woot!
