### ISSUE TITLE
ajaxform component doesn't work w/ radio inputs

### ISSUE THREAD

**Issue by toolness** [18F/calc#570]
Because of the way radio buttons work, and the way our ajaxform component needs to manually populate a `FormData` instance (see #520), our ajaxform doesn't set the correct value for a radio input.  Instead, it will submit form data such that it always looks like the very last radio button in a group has been selected (I think).

This isn't a problem _for now_ because we don't have radios in our one ajaxform.  But we might want to at least detect the radio situation and throw an exception if it looks like there's a radio in the ajaxform or something (though obviously, even better would be to just support radios).

**Comment by toolness** [comment]
Also, there may be other funky types of inputs that our ajaxform doesn't work with, I'm not sure. Blegh.

**Comment by jseppi** [comment]
Oh geez :\ Are there any other ajax-form like components in the wild we can use or see how they deal with other form inputs?

Here's one I just found real quick: https://github.com/rnicholus/ajax-form
and here's how it deals with radios: https://github.com/rnicholus/ajax-form/blob/master/ajax-form.js#L239
