### ISSUE TITLE
Consider converting data-capture widgets into Web Components

### ISSUE THREAD

**Issue by toolness** [18F/calc#581]
Ok, I've watched Thomas Wilburn's [Custom Elements in Production](http://2016.cascadiafest.org/speakers/thomas-wilburn/) talk that @jseppi recommended and I've played around with making some trivial components using the [webcomponents.js](https://github.com/WebComponents/webcomponentsjs) polyfill.

Overall, I think that this is a pretty straightforward tool that can potentially make our code cleaner, more predictable, and better encapsulated.

Advantages:

* The biggest advantage I see over our current jQuery-driven markup API approach is that web components are automatically discovered and "upgraded" by the browser. This means, for example, that if we load some new content in via Ajax, we can count on our custom elements being automatically upgraded, rather than having to manually upgrade them ourselves (which is currently the case). This is really nice!

* Another bonus of auto-upgrading is that it makes it easier to document our components. No more "oh, and if you load in content via ajax, make sure you call this one function" in our docs.

* Our code is *probably* going to be less jQuery spaghetti-ish, but I'm not sure.

* Depending on how we do things, our code might be less error-prone and progressively enhance better, but I'm not sure.

Disadvantages/Concerns:

* According to Wilburn's talk, Web Component polyfills can reliably work in IE10+... I'm not sure how many of our users will be using something older than that.  Based on the user interviews we've done so far, it *seems* like none of them will, but we should make sure of that.  Fortunately our progressive enhancement strategy should help us here, since all our widgets already work fine on browsers without JS enabled.

* It looks like `webcomponents-lite.js`, which is the only one we *really* need, is about 40k minified, and around 15k gzipped, which isn't bad.  Granted, that also includes HTML imports (which we probably don't need), and I think it might even include Weak Map support (which should already be provided by our babel polyfill) so we can probably slim that down even more if needed. I think that Wilburn doesn't even use this particular polyfill--he uses [document-register-element](https://github.com/WebReflection/document-register-element).

* I'm a bit concerned about the whole "upgrade timing" thing, but it *seems* as though elements are upgraded if we wait for `DOMContentLoaded` or `load`?  I guess we should read up on this and make sure that our code won't explode on some browsers due to upgrade timing issues... Or at least that, if upgrade timing issues do occur, the core "gracefully degraded" functionality of our widgets still works.

* We'll have to think carefully about how we want to reconcile our Web Components with progressive enhancement. For instance, I could imagine our upgrade widget looking like this, maybe:

  ```html
  <input type="file" is="upload-widget" extra-instructions=".XLS files only, please" ...>
  ```

  That could be nice because it'd just work out-of-the-box on non-JS browsers, but we could upgrade it... Although I'm not sure if we could upgrade that without shadow DOM support, since we'd actually want the upgraded `<input>` to be wrapped in a `<div class="upload">` and stuff... Hrmmm, I guess an alternative might be:

  ```html
  <upload-widget extra-instructions=".XLS files only, please.">
    <input type="file" ...>
  </upload-widget>
  ```

  That would gracefully degrade while still allowing us to upgrade in a predictable way. I guess there are markup API analogs to all these things anyhow, so it shouldn't be too hard to think through.

  **Update:** See #582 for the latest thinking/prototyping of this.

**Comment by jseppi** [comment]
@toolness implemented this!
