### ISSUE TITLE
R10 Upload - Add XLS screenshot to Step 1

### ISSUE THREAD

**Issue by jseppi** [18F/calc#588]
In the R10 bulk upload flow, add a screenshot and/or descriptive text about the file we need for the Region 10 Bulk Upload.

**Comment by toolness** [comment]
I'm kinda wondering if it makes sense for these "excel screenshots" to "fake" a screenshot e.g. by just using a `<table>` that we style to look like an excel one.

Among other things, it'd make the "screenshots" accessible...

**Comment by jseppi** [comment]
That does make sense, they'd be easier to make small changes to that way. Though those spreadsheets are pretty wide and the S70 price list one is in a fairly complicated sheet, so styling could be a somewhat big lift.

**Comment by toolness** [comment]
Hmm, I'm curious if copying the cells in excel (on either Windows or OS X) sets an HTML type on the clipboard.  If it does, just retrieving its content might actually give us something that looks decent, but it's kind of a wild guess.
