### ISSUE TITLE
R10 Upload - Properly direct non-is_staff users to error page when attempt to access R10 upload flow

### ISSUE THREAD

**Issue by jseppi** [18F/calc#594]
Right now non-`is_staff` users just get redirected back to the auth flow when they attempt to access the R10 flow. They should instead get a `403` error page.

**Comment by toolness** [comment]
Oh wait, I didn't realize this was the problem you were showing me on screenhero--I thought you were logging in as a `is_staff=True` user when it was redirecting you to the auth flow!

Sadly, this is a built-in feature of that decorator you used, which is silly.

I think it's not that big a deal though so long as we don't show the bulk upload link to anyone who's not staff?

**Comment by jseppi** [comment]
Is there a better decorator?

Or maybe we could write our own simple one that checks for `is_staff` and redirects to the 403 page on `False`, and put it after `@login_required`?

**Comment by jseppi** [comment]
Fixed in https://github.com/18F/calc/pull/662
