### ISSUE TITLE
Just use Procfile instead of custom bash script

### ISSUE THREAD

**Issue by jseppi** [18F/calc#609]
Since we are going to to stop loading data on deploy, we could get rid of the `cf.sh` script all together (and the `command:` in the manifest files), and instead just use a `Profile`. 
I think the `Procfile` contents we would need are simply: 
`web: newrelic-admin run-program gunicorn hourglass.wsgi:application`

Currently `cf.sh` also runs database migrations `python manage.py migrate --noinput`, but we probably don't want to automatically do that on deploy to production since we'll be using a shared database service, and a migration could break the currently live app instance. I'm not actually sure how to best handle migrations with blue-green or continuous deployments. Thoughts @toolness or @cmc333333 ?

**Comment by jseppi** [comment]
Also, CloudFoundry is showing this warning on deploy/restage now that we removed the `Procfile` in https://github.com/18F/calc/pull/604 (though the deploys still work):

```
 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
 !     Learn more: https://devcenter.heroku.com/articles/procfile
```

**Comment by jseppi** [comment]
Actually, @cmc333333 advised against using a Profile and _for_ using manifests (with multiple apps defined in them), so I will close this because we're already using the manifest-driven approach.

**Comment by toolness** [comment]
Um, that is kind of hilarious that cloud.gov/CloudFoundry is mentioning Heroku by name in its warning logs.
