### ISSUE TITLE
Investigate LOG/HINTs from database during R10 load

### ISSUE THREAD

**Issue by jseppi** [18F/calc#618]
Not sure if this is a problem or not, so we should investigate, but I see a number of these messages during processing large R10 files:

```
db_1         | LOG:  checkpoints are occurring too frequently (10 seconds apart)
db_1         | HINT:  Consider increasing the configuration parameter "checkpoint_segments".
```

**Comment by toolness** [comment]
Oh hey, I actually kind of know what those are after having seen most of this [Postgres Proficiency for Python People](https://us.pycon.org/2016/schedule/presentation/1690/) talk/workshop thing.

However, I still do not know enough to determine whether this is a big deal or not.

**Comment by jseppi** [comment]
Hrm, this is probably not an issue with our local or docker databases. I also kinda doubt we could change the `checkpoint_segments` in the cloud.gov postgres service instance (nor do I know if it is a problem there -- it might be high enough already).

I am going to close this and we can re-open if it is a problem on staging or prod.
