### ISSUE TITLE
Redis/Queue monitoring?

### ISSUE THREAD

**Issue by jseppi** [18F/calc#625]
We have New Relic to monitor the main application, but not really a way of monitoring that the queue is up and running. I'm not sure the best way to go about doing this type of monitoring.

Maybe helpful: https://github.com/ducu/rq-dashboard

**Comment by toolness** [comment]
Hmm, at my last job we added a `/heathcheck` endpoint to all our apps, which was supposed to return a 200 if all an app's dependent services were up.  I think Amazon CloudWatch or something was responsible for pinging this endpoint on a regular basis to make sure everything was OK.

So, if we were using that system, we'd just add some kind of check to make sure we were connected to the `rq` server to the `/healthcheck` endpoint... But I'm not sure what to do here... Does Newrelic support anything like health check endpoints?

**Comment by jseppi** [comment]
Ah, cool! Yeah we can ping individual endpoints in New Relic.

**Comment by toolness** [comment]
Oh, it also appears that `django-rq`, which we're already using, actually has a queue statistics dashboard built-in:

https://github.com/ui/django-rq#queue-statistics

So we could enable that in addition to the health check!
