### ISSUE TITLE
Add flake8 to travis build

### ISSUE THREAD

**Issue by jseppi** [18F/calc#636]
Because we are no longer using QuantifiedCode.

Probably via `ultratest --lintonly`, though as @toolness pointed out, this will make our eslint run twice, once by CodeClimate and once by `ultratest`.

**Comment by toolness** [comment]
Another option, if we really want, is to get rid of `--lintonly` and instead allow `ultratest` to accept any number of positional arguments that specify the "slug" of the test to run.  For example:

* `manage.py ultratest flake8` would run only flake8.
* `manage.py ultratest flake8 py.test` would run flake8 and py.test.

And so on.

**Comment by jseppi** [comment]
Oooo, that's pretty cool!
