### ISSUE TITLE
"manage.py ultratest --help" isn't very helpful

### ISSUE THREAD

**Issue by toolness** [18F/calc#649]
```
$ python manage.py ultratest --help
Connection to database established.
Usage: manage.py ultratest [OPTIONS] [TESTTYPE]...

  Management command to test and lint everything
```

It would be nice if we documented exactly what `TESTTYPE` meant and its possible values!

**Comment by jseppi** [comment]
Hrm, so while working on `bulkcreateusers`, I couldn't find a way to add help text to a `@click.argument` (though you can add help text to `@click.option` via the `help` kwarg). Can docstrings be generated dynamically?

**Comment by toolness** [comment]
Yeah, I think you can assign the `__doc__` attribute to change the docstring dynamically, e.g.:

```py
def boop(): pass

boop.__doc__ = "halloo"

help(boop)
```

**Comment by jseppi** [comment]
Hrm, modifying `__doc__` didn't work for django-click (probably because it dynamically generates the command class based on the decorated function definition, so modifying the function's internals has no effect after the decorator does its thing). But I figured out another way...
