### ISSUE TITLE
Form Button Row - Swap cancel for next button

### ISSUE THREAD

**Issue by hbillings** [18F/calc#651]
Cancel is too prominent and Next is too easy to miss.
Consider:
- Put Next where Cancel is currently
- Put label for Next on right side
- Bold Next
- Try `primary-alt-blue`
- Turn Cancel into a link and place it somewhere with less prominence

**Comment by jseppi** [comment]
I assume this is in regards to the Form Button Row buttons?

**Comment by hbillings** [comment]
@seppi yeah, I coulda been clearer about that, sorry!

**Comment by jseppi** [comment]
> Turn Cancel into a link and place it somewhere with less prominence

It doesn't appear the WDS have a "link-style" button class _à la_ `.btn-link` in Bootstrap (ref: http://v4-alpha.getbootstrap.com/components/buttons/#button-tags). We have to use a `<button>` element for cancel since it issues a `POST` request to clear session.

**Comment by toolness** [comment]
Fixed by #740!
