### ISSUE TITLE
Submission success page tweaks

### ISSUE THREAD

**Issue by hbillings** [18F/calc#653]
Add success status to last page. Use the alerts https://standards.usa.gov/alerts/
Add information about next steps. (I think this should be something that says you'll receive an email when your data is approved -- is that right?)

**Comment by jseppi** [comment]
Yep, the user will receive an email when a CALC admin approves the price list.

**Comment by jseppi** [comment]
Update to my previous comment: emails will not be sent out now in the first release because of an ATO SNAFU.
