### ISSUE TITLE
Remove "change password" from Admin site header

### ISSUE THREAD

**Issue by jseppi** [18F/calc#666]
We don't use (local) passwords so it doesn't make sense for it to be displayed so prominently.

<img width="517" alt="screen shot 2016-09-06 at 10 03 39 am" src="https://cloud.githubusercontent.com/assets/697848/18278888/4d570e6e-7419-11e6-8230-9846084071e4.png">

**Comment by jseppi** [comment]
Hrm, actually the "Change password" link should only show up if `user.has_usable_password()` is true (ref https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/django/contrib/admin/templates/admin/base.html#L43)
Basically, we just need to make sure to NOT set any user passwords when creating our administrative users.

**Comment by toolness** [comment]
Hmm, I thought that setting a password is required when using `manage.py createsuperuser` though?  Is there a way to run it w/o setting a password?

**Comment by jseppi** [comment]
There is, actually, with the `--noinput` flag:

```sh
python manage.py createsuperuser --noinput --username testsuper --email test@localhost
```

**Comment by toolness** [comment]
Oh nice!  We should mention that when telling users to run `createsuperuser` in the README.

**Comment by toolness** [comment]
Actually, #675 touches that bit of text, so I could update the instructions in that PR if you want me to.  Or we could do it separately.

**Comment by jseppi** [comment]
Ooh yeah, go for it in #675!

**Comment by toolness** [comment]
Ok, done!
