### ISSUE TITLE
Refactor tables to be easier to style

### ISSUE THREAD

**Issue by toolness** [18F/calc#672]
As @hbillings mentioned in https://github.com/18F/calc/pull/644#issuecomment-244183345:

> - We should create a `hoverable` class for tables that should use highlighting.
> - The `table` CSS isn't really in line with the way WDS does it -- it's all kind of all over the place. We should default to WDS table styles and namespace the rest, like you suggested. Maybe an easy way to start on this would be to add a `prices` or somesuch class to the existing table styles.

**Comment by hbillings** [comment]
This has been done somewhere along the way.
