### ISSUE TITLE
Split testing dependencies into a separate requirements file, do not include in prod/staging

### ISSUE THREAD

**Issue by jseppi** [18F/calc#678]
Per ATO discussion (https://github.com/18F/Infrastructure/issues/649#issuecomment-245316653) we should split out all testing dependencies into another requirements file (such as `requirements-test.txt`). `requirements.txt` should then only contain packages necessary for production.

We'll need to modify our Travis build to install both from `requirements.txt` and `requirements-test.txt` (so that it can run tests) and we'll need to ensure that the cloud.gov deploys only install from `requirements.txt`.

**Comment by toolness** [comment]
I guess we'll also need to update the `README.md` to tell devs to install the other one, and the `Dockerfile`?

Oh, another option might be to just call it `requirements.dev.txt` and have it include the following line at the top:

```
-r requirements.txt
```

That way it inherits everything from `requirements.txt` and devs won't need to install two requirements files (nor will travis).

**Comment by toolness** [comment]
Oh lol, it looks like you figured out that exact thing for #681, so nevermind :)

**Comment by jseppi** [comment]
Haha, beat you to it!
