### ISSUE TITLE
Adding additional non-data rows to top of S70 price list break gleaner

### ISSUE THREAD

**Issue by toolness** [18F/calc#683]
The official template positions the first row of actual price list data at row 3, and our algorithm currently proceeds until it finds the first row that either has no **SIN** or no **Price (including IFF)**.

However, here a vendor has added rows to the top of the sheet (it looks like they've been copy/pasted from somewhere else?) such that the first row of data is on row 10 (I've left out the actual data from the screenshot so it can be publicly posted here):

![screen shot 2016-09-07 at 4 07 41 pm](https://cloud.githubusercontent.com/assets/124687/18326765/6f7f97fc-7515-11e6-8823-77a6c3d43337.png)

So our algorithm is likely starting at row 3 and stopping at row 4 because it's blank. 😞

**Comment by jseppi** [comment]
Oh geez.

I suppose we change the start row determination code to instead check for the row of expected headers?

**Comment by jseppi** [comment]
Heh, actually, given the content of rows 5-7, I would think the change was made by a CO or some other employee rather than a vendor.

**Comment by toolness** [comment]
Yeah, that's what I thought too, but kelly said that the vendor added it... maybe he was referring to something else though.

Anyhow, another option might actually be to implement a UI that presents the spreadsheet to the user and actually allows them to specify (e.g. through dragging a rectangle) where the data is... Then if the columns have been mixed around or anything, we could even have them point out which column contains what data, as I think kelly suggested back in August.  But that's obviously a heavy lift!

**Comment by toolness** [comment]
Oh, another thing we might want to do is keep the uploaded XLS around so that we can look at it later, as devs, and figure out what made the price list not glean anything. Possibly in concert w/ a user opt-in, e.g. via a button labeled **This is totally a valid price list, your data capture tool sucks**.

**Comment by toolness** [comment]
So I've been brainstorming a bit about other approaches to this conundrum:

* Provide "advanced options" like "number of rows to skip" and "SIN Column", that the user can fill out.  Definitely a lighter lift than providing a GUI allowing them to point at the columns, but also a much worse UX.  That said, it could potentially be the baseline UX that a drag-and-drop UI progressively enhances over.

* Allow the user to *manually* enter the price list rows. This might actually be feasible for really short price lists. It'd be super simple to implement as it'd just be a good ol' [Django formset](https://docs.djangoproject.com/en/1.10/topics/forms/formsets/) (the same underlying tech is used in Tock when we report our hours).

* This one is really "out there", but we could potentially provide a [Blockly UI](https://developers.google.com/blockly/) that allows users to specify custom logic to sanitize/massage cell values. Or if some COs happen to be Excel wizards, we could even implement some subset of [Excel VBA](https://en.wikipedia.org/wiki/Visual_Basic_for_Applications) that they could use.

**Comment by jseppi** [comment]
#765 is a simple fix for this one

**Comment by toolness** [comment]
Cool! Sorry, my last comment was more of a "how to solve the variance of spreadsheets in general" kind of thing rather than this issue in particular--wasn't really sure where else to put it...

**Comment by jseppi** [comment]
Closed by #765
