### ISSUE TITLE
Steps bar spacing isn't even

### ISSUE THREAD

**Issue by hbillings** [18F/calc#714]
Some labels are longer than others, which means flexbox gives those steps more room. We should probably have a label max-width.
<img width="897" alt="screen shot 2016-09-09 at 9 42 16 am" src="https://cloud.githubusercontent.com/assets/509309/18390974/f856707a-7671-11e6-9ee6-3d9d945c07fa.png">

**Comment by jseppi** [comment]
Looks fixed as of https://github.com/18F/calc/commit/b84c74c8cca7dea71f8e13c8f960c57c523f9ef3!
