### ISSUE TITLE
Adding '--cov' to pytest.ini breaks ability to run individual tests

### ISSUE THREAD

**Issue by toolness** [18F/calc#728]
I just noticed that I can no longer run `py.test [file_or_dir]` to test individual files--py.test *always* collects every single test in the project and runs them all.

Removing `--cov` from the `addopts` entry in `pytest.ini` (i.e. reverting a43a49ac1807883560e4f5fe78923912a5e05519, which was part of #708) fixes this.

**Comment by jseppi** [comment]
I just noticed that also. barf. sorry!

**Comment by toolness** [comment]
S'all good, do you want to issue a PR to fix this or should I?

**Comment by jseppi** [comment]
on it
