### ISSUE TITLE
Make a "CALC is undergoing maintenance" cloudfoundry app

### ISSUE THREAD

**Issue by toolness** [18F/calc#733]
Basically what we want is [Heroku maintenance mode](https://devcenter.heroku.com/articles/maintenance-mode) but for Cloud Foundry/cloud.gov.

@jseppi suggested just creating a separate app that is a static site with a single page on it. (Though I guess it should serve that same page on all routes...)

Anyhow, if we create this, we can more easily do deploys that require downtime (e.g. involving database migrations and stuff).  We can just tell cloudfoundry to map `calc.gsa.gov` to this app while we're doing maintenance stuff.  

I've heard there are ways to do rolling migrations but this seems like a nice solution for now, especially since it *seems* like it's OK for CALC to be down for maintenance for a few/several minutes every once in a while (but correct me if I'm wrong).

**Comment by jseppi** [comment]
I guess this simple static page should be in another repository?

**Comment by toolness** [comment]
Hmmmmmmm good question--since cloudfoundry isn't bound to git like heroku is, I wonder if we should just put it in this repo for convenience?  That way we could maybe even use styles and stuff from it, if we really wanted?  Then we could just have a README in the directory of the static page that explained stuff...

**Comment by jseppi** [comment]
Yeah, that _should_ work. I think `cf push` pushes everything from the current directory (excepting the stuff in `.cfignore`) so we should be able to deploy from the maintenance app subdirectory.
