### ISSUE TITLE
Display chosen schedule, contract # and vendor name on step 2

### ISSUE THREAD

**Issue by hbillings** [18F/calc#737]

**Comment by toolness** [comment]
You'll probably want to "resurrect" the actual `Step1Form` here and pull from its `cleaned_data` for displaying that data... Um... I think I will also change `Step1Form`'s `cleaned_data` to actually convert the schedule into a `BasePriceList` subclass (the raw `POST` data actually refers to the dotted Python class naming a `BasePriceList` subclass)...

**Comment by toolness** [comment]
Ok, as of #742 you can now rez `Step1Form` and grab its `cleaned_data['schedule_class']` to get the actual `BasePriceList` subclass associated with the preferred schedule (just grab its `title` property to get the human-friendly schedule name).

**Comment by toolness** [comment]
Er, might want to actually wait until #748 lands before starting this, as it adds a new `get_step_form_from_session()` helper function that can make this particularly easy.
