### ISSUE TITLE
Use defusedxml to guard against XML vulnerabilities in XLSX uploads

### ISSUE THREAD

**Issue by jseppi** [18F/calc#749]
Ref and example usage of `defusedxml`: http://xlrd.readthedocs.io/en/latest/vulnerabilities.html

**Comment by toolness** [comment]
Whoa, good catch!!  I didn't realize there were security implications here at all.

**Comment by jseppi** [comment]
yeah, luckily I was reading through `xlrd` docs to figure out why it is so screwy and saw that page
