### ISSUE TITLE
For schedule 70, offer a download link to the PPL template

### ISSUE THREAD

**Issue by toolness** [18F/calc#753]
@tram mentioned we should do this. We currently do have a PPL template with one row filled out for purely testing purposes--I think this download would basically be that file, but without the one row filled out.

**Comment by toolness** [comment]
I think a good place to put this would be under the "I don't know what to upload" expander content for schedule 70, which is being added in #754.

**Comment by toolness** [comment]
This isn't hard to add--what should the copy say, though?  Something below the "I don't know what to upload" screenshot like:

> If you're not using a spreadsheet like this, please download the [Schedule 70 Price List Template](#).

?

**Comment by jseppi** [comment]
maybe 
> ... please download and fill out ...
?

**Comment by toolness** [comment]
Radical!

Is there a newer XLSX file available than the one Kelly gave us at the beginning of this project?  If not, I guess I'll just take our "PPL with one row added", remove the row, and use that as the template...

**Comment by jseppi** [comment]
I don't _think_ so. Maybe @tram would know.

**Comment by tram** [comment]
Nope! Still the same one.
