### ISSUE TITLE
Make test fixtures directory and use git-lfs for storage

### ISSUE THREAD

**Issue by jseppi** [18F/calc#755]
We should create a directory of test fixtures for our price list parsing, especially as we start adding more complex coercions. Unfortunately XLSX files are binary, so they are not great to store in a git repo. Instead we should also use and (document in our README) [Git Large File Storage](https://git-lfs.github.com/), as suggested by @toolness in https://github.com/18F/calc/pull/750#issuecomment-247346391

**Comment by jseppi** [comment]
Bah, looks like Travis does not support git-lfs out of the box

**Comment by toolness** [comment]
Oh shoot--sorry, that was my bad, I thought it did :(

**Comment by toolness** [comment]
Blerg.

**Comment by jseppi** [comment]
Closing this because doesn't look like Travis is ready for git-lfs, and @toolness made a handy `FakeWorkbook` class to help us mock worksheets for tests.
