### ISSUE TITLE
Make scrollable Excel example look scrollable

### ISSUE THREAD

**Issue by hbillings** [18F/calc#780]
This is likely different for every browser, but in Chrome there's no indication that you can scroll:
<img width="1059" alt="screen shot 2016-09-21 at 10 24 32 am" src="https://cloud.githubusercontent.com/assets/509309/18717555/e4aed15c-7fe5-11e6-9e5e-fa85fa8de847.png">

**Comment by jseppi** [comment]
I think the OS also has a lot to do with scroll bars :\

**Comment by toolness** [comment]
Yeah, blerg.

Oh it looks like this question has been asked on StackOverflow and one solution is to [style `::-webkit-scrollbar` and `::-webkit-scrollbar-thumb`](http://stackoverflow.com/a/10100209).

**Comment by jseppi** [comment]
Fortunately most (probably all) of our users will be on Windows which I believe shows scrollbars.

**Comment by hbillings** [comment]
This also appears to have changed in recent versions of Chrome.
