### ISSUE TITLE
Fix radio buttons on data explorer

### ISSUE THREAD

**Issue by hbillings** [18F/calc#783]
The new USWDS radio button styles hide the default input, which breaks the data explorer search select.

<img width="836" alt="screen shot 2016-09-21 at 11 20 24 am" src="https://cloud.githubusercontent.com/assets/509309/18719581/91d18dd2-7fed-11e6-8d27-b2015383311f.png">

**Comment by jseppi** [comment]
>.<

**Comment by toolness** [comment]
Oh, this was fixed in #814!
