### ISSUE TITLE
Remove Contract Year and adjust Contract Start/End labels

### ISSUE THREAD

**Issue by jseppi** [18F/calc#790]
I think every single interviewee has had questions about what that field is and why it is needed.

**Comment by hbillings** [comment]
I know we've had some discussion about this, but documenting here... is contract year necessary? Can we extrapolate from the start/end date + escalation rate what the current and out year pricing would be?

**Comment by jseppi** [comment]
Per today's discussion:

* Remove the Contract Year radios
* Change "Contract start" to "Contract or current option period start"
* Change "Contract end" to "Contract or current option period end"

Does this sound correct @hbillings @tram @toolness?

**Comment by jseppi** [comment]
Done in #794
