### ISSUE TITLE
Bottom of text in Data Explorer dropdown filters is cut-off

### ISSUE THREAD

**Issue by jseppi** [18F/calc#806]
<img width="195" alt="screen shot 2016-09-26 at 10 41 48 am" src="https://cloud.githubusercontent.com/assets/697848/18843449/4bf1a562-83d6-11e6-9da9-33344bb19c70.png">

**Comment by artificialconstruct** [comment]
What platform is it relevant to? 
Is not reproduced on chrome.

**Comment by jseppi** [comment]
This happens on Chrome 53.0.2785.116 and Firefox 48.0.2 on Mac OSX 10.11.6. Note that this bug is in the `develop` branch of the code.

**Comment by toolness** [comment]
Hmm, I'm actually unable to reproduce this on develop as of 38a2e2b93fb12600298b0210d272b9b9f09f642b... On Chrome 53.0.2785.116 OSX 10.11.6 I am getting this:

<img width="202" alt="screen shot 2016-09-27 at 1 19 14 pm" src="https://cloud.githubusercontent.com/assets/124687/18884368/23501e2e-84b5-11e6-9c9c-ca3d287759a7.png">

The schedule *is* running into the down-caret of the dropdown but that's about it...

**Comment by jseppi** [comment]
Looks like the text cut-off is evident in the descenders of the `g`s and `y` in `87405 - Legacy Logistics` in that screenshot.

**Comment by toolness** [comment]
Oh, that's true I guess--it's just not nearly as severe as it was in the original screenshot.  Is there a way to guarantee that it doesn't appear cut off on anyone's screen, regardless of font choice?  Is it a matter of defining `line-height` in terms of `em` or something?
