### ISSUE TITLE
Revise copy for uploading new labor price data

### ISSUE THREAD

**Issue by tram** [18F/calc#811]
Recommendations from 18F Writing Lab in [18F/writing-lab/issues/199](https://github.com/18F/writing-lab/issues/199)

# Global changes
- Header: 18F style discourages capitalization of Government — in all instances of U.S. government, please use the lowercase.
- Headings and titles: Our style guide also recommends sentence case for headings and titles. Throughout, please update headings, titles, and form-field descriptions to sentence case.

# Calc home click login at bottom
- I’d update the short description to the following: “CALC lets you conduct market research on professional service labor categories quickly and easily, helping you make better informed decisions.”
- In the header, I’d add a period after “Help us improve.”
- Under Worldwide rates, I’d change the description to “Globally applicable rate” (to parallel the construction of the other descriptions).
- Instructions above the search bar: I’d update to “Enter your search terms below, separated by commas.” (Stronger call to action.)
- Under Optional filters, please lowercase the y in “Contract year.”
- Footer: I love the tone of the “Get in touch” section — very friendly and welcoming!

# Fake cloud gov login
- Remove the “Just” from “Just enter your email address below…” (“Just” is one of our “Words to avoid” in the style guide.)
- I was a bit confused by the content in the note — will users already have received information on how to have their email addresses registered in the CALC database? If not, it might be useful to update the note to say something like, “You’ll need to have registered your email address in the CALC database to log in here. Visit our README for registration details.”

# Click add price data
(No notes that aren’t already captured in the other categories)

# Add company and contract information
In the short description, I’d combine the first two sentences as follows: “Your price lists help make CALC a more robust tool, and sharing them is easy…”

# Add contract details
Question: Will users know how to differentiate small from regular businesses? If not, additional instructions here might be warranted.

# Upload price data
(No comments here — looks good!)

# This xlsx doesn’t have the proper sheet
(No comments here — looks good!)

# Sheet error
I might recommend a few small tweaks to the error message: “Oops! Please correct the following error.” 

# Upload correct xlsx
(No comments here — looks good!)

# One row has an error
Please update “double-check” to “double check.”

# Success!
So, our style guide favors active over passive voice (it’s easier for folks to read). In light of this, I might recommend that you update the success message to “You’ve submitted your data for review — it should be available soon!” (I also think it’s OK to remove the bit about the CALC admin, as you’ve already clarified who will be doing the reviewing.)

**Comment by toolness** [comment]
Cool!

The **Fake cloud.gov login** is only used in development, so I'm not sure if we need to change the copy there, though it's fine if we do.  I guess we *have* been using it in our user testing, so perhaps it's actually a good idea to polish it.

**Comment by tram** [comment]
I'm not gonna sweat the **Fake cloud.gov** login stuff. :-)

**Comment by jseppi** [comment]
Is this finished now that https://github.com/18F/calc/pull/812 has been merged?

**Comment by jseppi** [comment]
^^ @tram

**Comment by tram** [comment]
It is! Thanks!
