### ISSUE TITLE
Checkboxes aren't visible on Django Debug Toolbar

### ISSUE THREAD

**Issue by toolness** [18F/calc#821]
This might have something to do with the USWDS checkbox styling making the actual `<input type="checkbox">`s invisible?  Not sure.

<img width="203" alt="screen shot 2016-09-28 at 4 47 42 pm" src="https://cloud.githubusercontent.com/assets/124687/18931753/7b1c488a-859b-11e6-815b-1a4ee3c79af6.png">

(Most/all of the above sections should have a checkbox next to them allowing the user to disable them if they want, but the checkboxes no longer appear.)

**Comment by hbillings** [comment]
sigh. yep. USWDS.
