### ISSUE TITLE
Style selected SIN/Schedule value so that the name is fully visible

### ISSUE THREAD

**Issue by hbillings** [18F/calc#838]
From [#823](https://github.com/18F/calc/pull/823#issuecomment-250505173)

<img width="197" alt="screen shot 2017-01-25 at 11 04 36 am" src="https://cloud.githubusercontent.com/assets/697848/22300758/16bb0f88-e2ee-11e6-96c5-7af6981a9c48.png">

**Comment by jseppi** [comment]
(made clarifying edits to title and root comment)

**Comment by hbillings** [comment]
New design for selector obviates the need for this.
