### ISSUE TITLE
Create user stories for website analytics

### ISSUE THREAD

**Issue by toolness** [18F/calc#839]
So right now we have Google Analytics and [DAP](https://www.digitalgov.gov/services/dap/) enabled, but we don't have a strategy for how we want to use them.

Over the past few months @tram has brought up some use cases, such as:
- As a researcher, I should be able to analyze information about people who somehow "fell off" the Price List Upload flow without completing it. I should be able to see what step they reached, and I should be able to follow-up with them individually if needed.
- As a developer or researcher, I should be able to analyze information about users who opted-in to safe mode. I should be able to see what percentage of users who were presented with the opt-in actually opted-in, and I should be able to see what page the opt-in was displayed on. If necessary, I should be able to follow-up with the user who was presented with the opt-in (if they were logged-in).

Depending on stories like these, we can figure out what kinds of [custom dimensions & metrics](https://support.google.com/analytics/answer/2709828?hl=en) and [events](https://support.google.com/analytics/answer/1033068?hl=en) we need to set up in GA.

I'm not very familiar with DAP and how its capabilities differ from GA, so we might want to do some research on that.

**Comment by toolness** [comment]
I started watching the [DAP 201 Virtual Training](https://www.youtube.com/watch?v=rPo3zFbhXnk) and it looks like there definitely *are* some things that DAP provides which our 18F Google Analytics account doesn't. A specific one is the ability to create [custom funnel reports](https://support.google.com/analytics/answer/6180923?hl=en), which is part of DAP but *not* part of 18F GA.

I suspect custom funnel reports in particular will be useful for us, since the whole multi-step price list upload process constitutes a "funnel" of sorts.

**Comment by toolness** [comment]
**Update:** We're currently using the [HEART framework](https://library.gv.com/how-to-choose-the-right-ux-metrics-for-your-product-5f46359ab5be#.gdiihef7n) to identify these user stories in the [HEART x GSM metrics exercise](https://docs.google.com/spreadsheets/d/1EnlEaRs6iKsgGsJtZqvnq1lEYKhTMnQ-zAdHUOXKX9o/edit#gid=0) google doc.

**Comment by jseppi** [comment]
Good to close this? Or is there additional action needed here, @toolness?

**Comment by toolness** [comment]
Yep good to close!
