### ISSUE TITLE
Review and/or remove updating_data.md

### ISSUE THREAD

**Issue by jseppi** [18F/calc#840]
Since Data Capture will now be part of the application, bulk updates of data should no longer be necessary. We want to avoid document rot, so we should review, and potentially remove, `updating_data.md`.

Related:
- remove old data files from `contracts/docs/`
- review/remove `load_data` and `load_s70` management commands

**Comment by toolness** [comment]
I agree!  It looks like there's also one reference to `updating_data.md` in `README.md`, so if we get rid of it, we should be sure to remove it from the readme too.

**Comment by jseppi** [comment]
Closed by #1774
