### ISSUE TITLE
Remove headline and use progress bar to indicate current step

### ISSUE THREAD

**Issue by hbillings** [18F/calc#844]
This reduces redundancy and will help compress the top of the page. The downside to this is that I don't think the steps widget is currently being read by screenreaders, so getting rid of the headline will also get rid of the accessible title of the page. I need to think about how to address that.

Idea:
<img width="1172" alt="screen shot 2016-09-30 at 3 23 44 pm" src="https://cloud.githubusercontent.com/assets/509309/19005919/b4dd8dee-8722-11e6-9e72-6649361357ce.png">

**Comment by toolness** [comment]
YASSS 🎉
