### ISSUE TITLE
Configure custom dimensions for Google Analytics in GA admin

### ISSUE THREAD

**Issue by toolness** [18F/calc#860]
As mentioned in https://github.com/18F/calc/issues/847#issuecomment-251158140:

> Um, we should also make sure we configure the admin UI in our current GA config. Not really a github issue per se but I figured I'd mention it here, since we haven't yet configured it.

Adding this to the pre-prod launch milestone.

**Comment by toolness** [comment]
Hmm, weird--when I go to CALC's **Custom Definitions -> Custom Dimensions** admin panel on GA, I'm not seeing the **New Custom Dimension** button that the instructions say I should click.  Going to ask for help on `#g-analytics` in Slack.

**Comment by jseppi** [comment]
How's this looking, @toolness?

**Comment by jseppi** [comment]
@toolness does this need to be done now that we've launched our new code to prod?

**Comment by toolness** [comment]
Oh shoot! Yea I will bust it up, thanks for the reminder!

**Comment by toolness** [comment]
Ok, I finally configured this:

<img width="831" alt="screen shot 2018-04-04 at 2 24 59 pm" src="https://user-images.githubusercontent.com/124687/38326535-08dbabda-3814-11e8-8e63-7e9f7e0e4f9e.png">

Note that we no longer track the user ID as a custom dimension, as of #869, so it's just the safe mode one.
