### ISSUE TITLE
Document compatibility mode in style guide and/or README

### ISSUE THREAD

**Issue by toolness** [18F/calc#863]
We haven't actually documented compatibility mode (formerly known as safe mode) in any way, or made it evident to new contributors that it's something that exists, so we might want to do that.

If we do this in the style guide we could also add a button that allows users to trigger the opt-in UI, so that they can voluntarily opt-in to the mode without having to go to their JS console and manually call `showEnableSafeModeUI()`.

**Comment by toolness** [comment]
While we're at it, it'd probably be a good idea to outline the progressive enhancement strategy of the data capture part of the site, since maintaining it going forward is required for compatibility mode to function properly.

**Comment by jseppi** [comment]
I wonder if we should start a data_capture.md as a place to put all kinds of data-capture-specific information (like which schedules are supported, which which bulk uploads are supported, etc.).

**Comment by toolness** [comment]
We could do that, or we could put it in the "About this tool" page or similar so that it's easily discoverable by visitors to CALC who might also be interested?

**Comment by toolness** [comment]
Oh, this was all added to the style guide in #937 and #955. Closing!
