### ISSUE TITLE
Discussion - Data Administrators must be is_staff 

### ISSUE THREAD

**Issue by jseppi** [18F/calc#864]
Moving comments from PR #856 to this issue for visibility.

From @toolness:
>One of the things that I find a bit funky about our current permissions and roles is the fact that a Data Administrator must also be Staff, i.e. a non-Staff Data Administrator simply doesn't make much sense. I suspect that one day, a Data Administrator (or superuser) will make a new Data Administrator but forget to also mark them as staff and then become confused.

From me:
> Yeah, this is weird. Just to be clear the is_staff is necessary to access the Django Admin, right? Is that easily changed? In hourglass/urls.py we are using our own staff_login_required function to wrap admin.site.login. I wonder if we could just change that decorator to also allow users with the BULK_UPLOAD_PERMISSION (or some new permission)?

**Comment by toolness** [comment]
Oh, yup, `is_staff` is indeed required to access Django Admin--in fact, it is literally the [definition of `is_staff`](https://docs.djangoproject.com/en/1.10/ref/contrib/auth/#django.contrib.auth.models.User.is_staff):

> Boolean. Designates whether this user can access the admin site.

So really `is_staff` might as well be called `can_access_admin_site`.

**Comment by jseppi** [comment]
Question answered - closing.
