### ISSUE TITLE
Error on duplicate Contract Number in Step 1 Data Capture?

### ISSUE THREAD

**Issue by jseppi** [18F/calc#865]
Since modifications are not yet implemented, should we show an error message when a duplicate Contract Number is entered in Step 1?

The error message could even say that the modification feature is coming soon.

@tram: thoughts?

**Comment by tram** [comment]
Great idea! If we see this error getting thrown a lot, we could also add something like "if this is not a modification and you think a Contract Number has been added incorrectly, please contact [name and email address of data administrator]."

**Comment by jseppi** [comment]
Closed by #985
