### ISSUE TITLE
table-sorting JS/classes are unused

### ISSUE THREAD

**Issue by jseppi** [18F/calc#871]
We have `tablesort.js` and are including it in the data-capture bundle, but we do not have any tables with the hook class (`.table-sortable`), except in the Style Guide.

I believe the original intent of having this code was to make the price list tables (in the Price List Upload Flow) sortable, but I'm kinda unsure. Should we make those tables sortable? Should we also make the error tables sortable? (error table sorting would be a little weird, especially when there are type mis-matches, like a non-numeric value in the price column.)

For reference, the table sorting code was originally added in #452, which closed https://github.com/18F/calc/issues/417

cc @hbillings @toolness

**Comment by hbillings** [comment]
We've decided not to do this.
