### ISSUE TITLE
Failing S70 Price List Uploads when missing non-necessary columns

### ISSUE THREAD

**Issue by jseppi** [18F/calc#876]
The S70 price list table has a whole bunch of columns, many of which are not used at all during the data-capture process (like `'COMMERCIAL LIST PRICE (CPL) OR MARKET PRICES'` and `'PRICE OFFERED TO GSA (excluding IFF)'`). However, the uploaded file will not be accepted if any of even these non-necessary columns are missing. 

Should we "soften" our validation logic to not care about those fields? Pretty sure it would be as simple as removing them from `DEFAULT_FIELD_TITLE_MAP` in `s70.py`.

![screen shot 2016-10-05 at 5 22 49 pm](https://cloud.githubusercontent.com/assets/697848/19133892/634a7120-8b20-11e6-87b2-e61da2f04ce8.png)

cc @toolness @tram

**Comment by tram** [comment]
That sounds good! I think we'd just want to make sure of two things: that not having it doesn't hurt us down the road and that not uploading the price list as we're asking for it would cause people to slip farther and farther from the template. I'm not _too_ worried about the latter, but maybe should ask Kelly about the former during standup?

**Comment by jseppi** [comment]
From stand-up discussion today, it sounds like we likely won't have a strong need for any of the currently non-necessary columns in the future. Or, if we do discover a need, it won't be an issue that some uploaded price lists are missing it because they'd just be used for doing some aggregate statistics.

**Comment by jseppi** [comment]
Closed in #893
