### ISSUE TITLE
Hyperlink "try uploading it again" to embedded upload form in step 3 errors

### ISSUE THREAD

**Issue by toolness** [18F/calc#880]
In #862 we embedded the upload form in step 3 errors rather than redirecting the user to step 3.

However, the "try uploading it again" copy at the top of the page no longer hyperlinks to anything. As @hbillings [pointed out](https://github.com/18F/calc/issues/804#issuecomment-251137034), the list of errors could potentially be pretty long, so the user might not even realize there is an upload form down near the bottom, so we might want to re-hyperlink the text to the bottom of the page.

**Comment by jseppi** [comment]
@toolness - want to take this one now that #884 is merged?

**Comment by toolness** [comment]
Sure!
