### ISSUE TITLE
Add test to ensure cloud foundry manifests for "prod a" and "prod b" are equal

### ISSUE THREAD

**Issue by toolness** [18F/calc#881]
This would involve adding a yaml parser and ensuring that all relevant fields are equal.

We could use this same kind of strategy to verify other things about our repository that we can't DRY-ify, e.g.:

* Ensuring that the same python version is specified in `runtime.txt` (used by cloud foundry, I think) and our `Dockerfile`,
* Ensuring that a common subset of files are included across `.cfignore`, `.dockerignore`, and/or `.gitignore`.

**Comment by toolness** [comment]
@jseppi I guess this is no longer needed since you're moving stuff to use autopilot?

**Comment by jseppi** [comment]
I believe so!
