### ISSUE TITLE
Validate "UNIT OF ISSUE" is "Hour" for every row in Price List upload

### ISSUE THREAD

**Issue by jseppi** [18F/calc#886]
While the "UNIT OF ISSUE" is not strictly necessary when we construct `Contract` models from an uploaded price list, we could easily ensure that the Unit of Issue value in each price row is "hour". This would help avoid getting non-hourly rate data in CALC, which is already a problem with some rows of the Region 10 bulk data (see screenshot).

Think this is worth doing @tram?

related: #876 

<img width="589" alt="screen shot 2016-10-06 at 12 53 32 pm" src="https://cloud.githubusercontent.com/assets/697848/19164023/f01859fc-8bc3-11e6-8419-aa9c715ddeaf.png">

**Comment by jseppi** [comment]
Note that in order to give meaningful feedback to the user, the Unit of Issue column would also need to be shown in our price list tables in Step 3/Step 3 Errors. cc @hbillings

**Comment by tram** [comment]
Was just thinking about this yesterday. Totally makes sense to me!
