### ISSUE TITLE
Use Google Analytics' "User ID" feature instead of a custom dimension

### ISSUE THREAD

**Issue by toolness** [18F/calc#897]
I just found out that GA has a [User ID](https://support.google.com/analytics/answer/3123662?hl=en) feature, which is way more useful than the custom dimension added in #842 (and subsequently removed in #869). I'm [asking in `#g-analytics`](https://gsa-tts.slack.com/archives/g-analytics/p1475842944000102) if this is OK.

This issue is also relevant to #847 and #860.

**Comment by hbillings** [comment]
Still relevant?

**Comment by toolness** [comment]
I think we should ditch this because (A) it's unclear whether there are potential privacy implications and (B) not many users will be logged in on multiple devices anyways, so the benefit won't be that great. So I'll close but we can re-open later if we really want.
