### ISSUE TITLE
Clean up navigation

### ISSUE THREAD

**Issue by hbillings** [18F/calc#900]
Design critique suggested the header needs some tweaks to make things clearer. Suggestions included:
- Remove the dark blue box grouping the login + site links
- Move login to the top so that users intuitively know what part of the page has changed after they log in
- Make the action links buttons in all caps
- Make action links become tabs on their selected pages so that we can remove "Add price data to CALC" altogether

**Comment by hbillings** [comment]
Done in #851

**Comment by jseppi** [comment]
@hbillings: closing because you said it was done but maybe forgot to click the button :) Please re-open if not the case.
