### ISSUE TITLE
New Relic not reporting on Staging :(

### ISSUE THREAD

**Issue by jseppi** [18F/calc#902]
I misspoke at stand-up today. New Relic is _not_ working on staging due to my overlooking how autopilot works.

Basically, we can't use `cf set-env` to set environment variables because autopilot won't know about them. The only thing we are using `set-env` for is `NEW_RELIC_LICENSE_KEY`, as documented in `deploy.md`.

So I need to figure out another way to get our private NR key into cloud.gov.

**Comment by toolness** [comment]
Errr... CUPS won't work?

**Comment by jseppi** [comment]
I don't think so. Our UPS is parsed by our app, but the New Relic monitor is launched before the app (actually I think it itself launches gunicorn), so it doesn't have access to those parsed values: https://github.com/18F/calc/blob/develop/cf.sh#L9

**Comment by toolness** [comment]
Oh, it looks like it's possible to [init newrelic via manual integration with code](https://docs.newrelic.com/docs/agents/python-agent/installation-configuration/python-agent-integration#manual-integration):

```py
import newrelic.agent
newrelic.agent.initialize()
```

Maybe if we call that in `setup.py` or one of our apps' ready events, after we've injected CUPS vars into the environment, it'll work?

**Comment by jseppi** [comment]
woot! I was hoping there would be something like that, just hadn't had a chance to look over stuff yet :)

**Comment by jseppi** [comment]
This was not as easy as I had hoped because it was a pain to test it :\
