### ISSUE TITLE
Remove DAP from data capture pages that require login

### ISSUE THREAD

**Issue by toolness** [18F/calc#903]
Was just [chatting with Tim Lowden on `#g-analytics`](https://gsa-tts.slack.com/archives/g-analytics/p1475853162000117) and it looks like DAP is only intended for public-facing sites; because the data capture part of the site is specifically only for federal employees, we should probably remove it from those views.

**Comment by hbillings** [comment]
@toolness Is this a transition sprint task?

**Comment by toolness** [comment]
Just checked w/ Tim Lowden on Slack and he confirmed this is one of the reasons for advising DAP only be on public pages.  He mentioned the other reason is that if the DAP JS script is ever compromised, it potentially limits the maximum amount of damage that can be done to external sites. 

So I will go ahead and put this on the milestone.
