### ISSUE TITLE
Escalation rate more big

### ISSUE THREAD

**Issue by jseppi** [18F/calc#911]
Whoops, looks like the escalation rate input needs to be slightly bigger because rates like "1.5" won't quite fit in there. Sorry, I should noticed this before merging #908.

<img width="167" alt="screen shot 2016-10-11 at 2 30 49 pm" src="https://cloud.githubusercontent.com/assets/697848/19285388/63fbc3b4-8fbf-11e6-976d-69cf54352603.png">

**Comment by hbillings** [comment]
MOAR BIGGAR
