### ISSUE TITLE
PDF downloads aren't being tracked

### ISSUE THREAD

**Issue by toolness** [18F/calc#914]
As mentioned in #869:

> Looking at the [DAP source code](https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js#L684-L685) it seems DAP will trigger an event with category `Download` on every click of an anchor that ends with a variety of [common extension types](https://github.com/digital-analytics-program/gov-wide-code/blob/master/Universal-Federated-Analytics.js#L50) (including XLS, XLSX, CSV, and PDF). That said, **it's iterating through all the anchors on the page on load**, so anchors injected via Ajax (like the ones in the table on the data explorer) probably won't get caught.

**Comment by toolness** [comment]
Note that we should probably verify that the downloads aren't being tracked.

If they aren't, then we could solve this either on our end, or by changing the DAP code.

**Comment by jseppi** [comment]
This is referring to the contract PDFs from GSA Advantage, correct?

**Comment by toolness** [comment]
Just verified that this is actually happening, though I was wrong about the links being to PDFs--they're actually links to URLs that end with `.htm` and immediately redirect to a PDF.  That said, the behavior is similar: DAP treats them as "outbound links" and adds event handlers to each one when the DAP script is loaded, so any outbound links created *after* DAP is loaded aren't tracked.

This actually causes a race condition in CALC's case, because we started loading DAP asynchronously in #887.  In a few situations, DAP may happen to load after the first result set is loaded, which means its outbound links will be tracked. But if DAP loads first, or if the user performs a query, then the result set's outbound links won't be tracked.

**Comment by toolness** [comment]
Filed this on the DAP-side as https://github.com/digital-analytics-program/gov-wide-code/issues/45.
