### ISSUE TITLE
Treat common, data-explorer bundles just like data-capture

### ISSUE THREAD

**Issue by toolness** [18F/calc#917]
Currently the data-capture bundle supports ES6 because we're running it through Babel, and we're also doing all kinds of linting on it to ensure the style is awesome.

However, we're not  doing this with any of our legacy code--the common and data-explorer bundles--because, well, it's legacy.

But as we're starting to transition into actually working on those parts of the codebase, it'd be nice to take advantage of all the features of our data-capture toolchain.

So perhaps we should treat the legacy bundles the same as data-capture, but wrap all their files in `/* eslint-disable */` / `/* eslint-enable */` chunks to make the linter chill. Then we can add new modules and stuff that are compliant with our new standards (and possibly even migrate the legacy code to the new standards snippet by snippet).

**Comment by toolness** [comment]
Hmm, I hadn't realized that the common and data-explorer bundles also concatenate third-party libraries (d3, jQuery, various jQuery plugins, etc).  That complicates matters a bit.

I'm nervous about converting all those third-party libraries into imported modules that browserify brings in via `require`/`import`.  And combining concatenated files with browserified files in a single bundle seems challenging based on a quick web search...

I wonder if it might be easiest to just make a `common/vendor.min.js` that has all the concatenated dependencies, and then a `common/index.min.js` bundle that's all our first-party code (and any other third-party dependencies we decide to add later via npm)... That means we'd have two script tags for common instead of one, which wouldn't be super awesome, but it might be easier to add to our build pipeline. We could then do the same for the data-explorer bundle.

Blerg.

Suggestions @jseppi?

**Comment by jseppi** [comment]
I would be ok with your suggestion to have mutliple bundles, especially with the goal of eventually/hopefully phasing them out.
