### ISSUE TITLE
Should non-interactive focus targets have an outline?

### ISSUE THREAD

**Issue by toolness** [18F/calc#925]
This was brought up in https://github.com/18F/calc/pull/918#issuecomment-253658609.

Normally, focus indication is really important, as argued in [outlinenone.com](http://www.outlinenone.com/).

However, there are a number of instances where our focus target is a *non-interactive* element, for a few reasons:

* To ensure that screen readers announce the content of the target element, because it's very important, as in the case of our `<alerts-widget>` (see #635)

* To set up sequential focus navigation so that the next time the user presses <kbd>Tab</kbd>, an element relevant (or "localized") to said content is focused.

Because the focus target is non-interactive, I'm not sure whether there should be a focus target around it.

## Arguments for focus styling

The main advantage I see in using focus styling for non-interactive elements is so sighted keyboard users have some idea of *where* they are in the sequential tab navigation ordering, i.e. what might go into focus when they press <kbd>Tab</kbd> or <kbd>Shift</kbd> + <kbd>Tab</kbd>.

## Arguments against focus styling

However, I'm also concerned that putting the focus outline around a non-interactive element might be *confusing* for keyboard users. To some extent it seems focus styling is an affordance that tells people "hey, this element is interactive", and as such, it may lead them to believe that pressing <kbd>Enter</kbd> or <kbd>Spacebar</kbd> will actually do something useful, which is not actually the case.

Some precedent for *not* styling the focus of non-interactive elements comes from the way browsers handle internal links. As Heydon Pickering notes in <a href="https://www.smashingmagazine.com/inclusive-design-patterns/">Inclusive Design Patterns</a>:

> The links within a table of contents point to element ids representing targets within the page, such as `#services`, which update the document’s URL with the corresponding hash cipher.
>
> ```html
> <h2 id="services">Services</h2>
> ```
>
> Despite these targets (usually `<section>`s or headings) not typically being focusable elements, browsers employ *sequential focus navigation* whereby the first focusable element within or after the target is made the next focusable element in sequence. The upshot is that users navigating by keyboard can follow a link in a table of contents and be transported to that section safe in the knowledge that keyboard functionality will be localized to the section.

The way we're using focus is similar; we want to ensure that non-sighted users know what's going on, which focusing the non-interactive element allows us to do reliably, and we also  want to ensure that keyboard functionality will be localized to a particular section.

## Outcomes

If we decide to leave out styling for focused non-interactive elements, we should probably change the focus styling for `<alerts-widget>` added in #635, as we're currently keeping the focus outline there.

On the other hand, if we decide to keep styling for focused non-interactive elements, we should change our modal in #918 so that it has focus styling.

**Comment by jseppi** [comment]
Should this be cross-posted in https://github.com/18F/accessibility?

**Comment by toolness** [comment]
Woot, [conversation on #g-accessibility](https://gsa-tts.slack.com/archives/g-accessibility/p1476460887000411) argues that non-interactive elements that aren't ordinarily in the tab order (i.e. have `tabindex="-1"`) don't need a focus outline!
