### ISSUE TITLE
Move all scripts to bottom of <body>?

### ISSUE THREAD

**Issue by toolness** [18F/calc#930]
@jseppi asked in https://github.com/18F/calc/pull/920#discussion_r83235338:

> huh, why are we including the bundle in the `<head>`? Should we move it down to the `before_body_close` block, or am I forgetting something?

It's largely due to legacy CALC behavior: the old CALC put all the scripts in the `<head>` and provided an empty-by-default `{% block head %}` for template subclasses to add more scripts, so that's what data capture is using.

We might want to consider moving all scripts down to the bottom of `<body>` to improve page loading though.

That said, I can think of one reason to keep scripts at the top: because we're following Aaron Gustafson's three maxims for progressive enhancement with JS (see #923), we are "applying no style before its time", which means that our pages can _potentially_ suffer from a "flicker" effect whereby the non-progressively-enhanced styling is visible for a split-second before it's enhanced (see https://github.com/18F/web-design-standards/issues/1465 for an example).

I'm not certain, but I _think_ that it may be our placing of the script in the `<head>` that is preventing this from occurring in CALC data capture.  Because all our analytics-related script tags in the `<body>` load asynchronously, the `<body>` doesn't contain anything that blocks `DOMContentLoaded`, which means that event fires as soon as page content is loaded, allowing our scripts to progressively enhance the page before the first paint occurs, preventing flicker. Moving the script to the bottom _might_ result in flicker, at least when the cache is cold, as the non-progressively-enhanced content would be visible while the browser loads the JS.

I suspect that the advantages of moving the JS to the bottom of the page will ultimately outweigh this, and there are probably some things we can do to reduce or eliminate flicker even when the script is at the bottom--the discussion at https://github.com/18F/web-design-standards/issues/1465 might give us some guidance--but I figured it's worth mentioning.

**Comment by tbaxter-18f** [comment]
+1 on this. I think there's a noticeable performance gain to be made by moving these down. We may want to go a step further and move any non-critical CSS out too. Maybe.
