### ISSUE TITLE
Number of results seems off

### ISSUE THREAD

**Issue by hbillings** [18F/calc#947]
In the search dropdown, what does the number next to the title represent? It seems super inaccurate.
Search for an electrical engineer -- oh, cool.
<img width="494" alt="screen shot 2016-10-19 at 9 14 08 am" src="https://cloud.githubusercontent.com/assets/509309/19522404/b448bc3c-95dc-11e6-9768-ef0421c5f094.png">

Adding a senior electrical engineer.
<img width="487" alt="screen shot 2016-10-19 at 9 14 37 am" src="https://cloud.githubusercontent.com/assets/509309/19522403/b447ea50-95dc-11e6-9002-d177ac8c6bae.png">

...wait, how many?!
<img width="783" alt="screen shot 2016-10-19 at 9 14 49 am" src="https://cloud.githubusercontent.com/assets/509309/19522405/b44c1ea4-95dc-11e6-999d-82e7c34397a6.png">

**Comment by toolness** [comment]
I wonder if this is related to #209?  It says that the number of search results in the dropdown is actually the number of "exact matches", but because the default search is set to "contains words", the ultimate number of results is bigger...

**Comment by jseppi** [comment]
I think it would be fun to re-do the search functionality!

**Comment by hbillings** [comment]
@toolness I bet it is!
@jseppi I feel like given what we know now, there's quite a bit we could do to make the whole experience better (especially if we get the visual design help on board!)

**Comment by jseppi** [comment]
The number definitely refers to the number of exact matches for that term.

I am going to close this since the question is answered, and the larger issue of the Data Explorer's UX is not really going to fit in a single GH issue :)
