### ISSUE TITLE
Graph updates differently depending on how search term is entered

### ISSUE THREAD

**Issue by hbillings** [18F/calc#949]
If I type "Electric" and select "Electrical Engineer" by clicking it from the autocomplete dropdown, I get 200 of 343results with an average of $86.
<img width="747" alt="screen shot 2016-10-19 at 9 38 13 am" src="https://cloud.githubusercontent.com/assets/509309/19523414/0b76ed6e-95e0-11e6-97bd-013a2f132917.png">

If I then click "Search," I get 167 results with an average of $112.
<img width="732" alt="screen shot 2016-10-19 at 9 38 23 am" src="https://cloud.githubusercontent.com/assets/509309/19523436/1fe118ce-95e0-11e6-8b3d-e5276ebaee04.png">

**Comment by jseppi** [comment]
This is fixed, most likely by #1075!
