### ISSUE TITLE
Excluded rows may not persist across price list updates

### ISSUE THREAD

**Issue by toolness** [18F/calc#958]
I just realized that the "exclude rows" feature of the data explorer _seems_ to use primary key IDs. Because we made the price list upload feature with the assumption that primary key IDs for contracts weren't used anywhere, we create/destroy contract objects whenever price lists are approved/unapproved.

Since updating a price list currently works by unapproving the old version and approving the new one, this means that identical rows in the two lists won't have the same primary keys when created as contract objects. Also, simply approving, unapproving, and then re-approving a single price list will cause the two sets of created contract objects to have completely different primary keys.

While this likely won't mean much for a single CALC session--e.g. someone doing quick market research over the span of several minutes to an hour--it may cause problems if users expect permalinks to report results to truly be "permanent". (Then again, since contracts are also going out of date and being expunged from the database anyways, perhaps there's no stopping this.)

**Comment by jseppi** [comment]
I think if the data change, then we wouldn't want the excluded rows to be persisted because perhaps the reason the data were originally excluded had been mitigated.
