### ISSUE TITLE
Commas in search terms may be ambiguous

### ISSUE THREAD

**Issue by toolness** [18F/calc#960]
It occurred to me when analyzing the logs that some search terms returned by the autocomplete functionality have commas in them, e.g. `Estimator/Scheduler, Jr` and `Truck Driver, Heavy Truck`.  When these queries are passed to the API, the API treats their commas as search term delimiters rather than part of the actual search terms.

For example:
1. Type `truck` into the search field.
2. One of the entries in the autocomplete list should be `Truck Driver, Heavy Truck`. Select this and press <kbd>Enter</kbd>.
3. This triggers a [search for `Truck Driver, Heavy Truck`](https://calc.gsa.gov/?sort=current_price&q=Truck+Driver%2C+Heavy+Truck%2C+&query_type=match_all&min_experience=0&max_experience=45&contract-year=current&experience_range=0%2C45). This means CALC is searching for entries containing `Truck Driver` _or_ `Heavy Truck`, and as a result it's including entries labeled `Truck Driver, Light Truck` in the results.

One way around this might be to remove commas from autocomplete results, or perhaps strip out the commas when the user presses <kbd>Enter</kbd> to add the autocomplete result to the search terms.

**Comment by jseppi** [comment]
The culprit, in (api/views.py)[https://github.com/18F/calc/blob/develop/api/views.py#L76]: 
`qs = [s for s in query.split(',') if s.strip()]`

**Comment by jseppi** [comment]
Kinda seems like we should use a different separator character (like `|` maybe), or we could quote individual terms.

A different separator character would break links unfortunately.

**Comment by toolness** [comment]
I don't suppose there's a consistent way to normalize labor categories (via the normalization in #1378) so that they don't include commas?  For instance, if it's always in the format "X, Y" then we could normalize it to "Y X" so that "Engineer, Junior" becomes "Junior Engineer".  I dunno.

**Comment by jseppi** [comment]
yeah, or even "Engineer (Junior)"

**Comment by jseppi** [comment]
Something else that we could use to "version" the URLs would be to still support the legacy `q` param, but change the app to make all new URLs with something else, like `query` or `terms`. Then we could keep the old behavior when `q` is present, but do something more robust with the new param.

**Comment by toolness** [comment]
Hmm, so one thing to keep in mind about the `q` param is that Google Analytics actually interprets it specially, as a search string.  I guess we could always bust up our API log analytics or customize GA, but a nice aspect of the fact that we use the standard `q` for our search string is that it allows GA to tell us about what kinds of search strings we're getting out-of-the-box.

I do like the parentheses approach, that'd be much less likely to accidentally look awkward!

**Comment by jseppi** [comment]
Huh, didn't realize `q` was special for GA. Interesting!

I'm a little leery of modifying the source data, as would be required for the parantheses approach. Would we modify the labor categories during upload/data capture? Or just as output from the API?

Maybe yet another approach is to have our front-end put quotation marks around labor categories that have commas in them, and make a slight adjustment to `views/api.py` to respect the quotation mark-delimited terms. Like how CSVs handle cells with commas in them.

**Comment by toolness** [comment]
Yeah, that said, I *think* GA also looks for other querystring params other than `q`... I bet `query` or `search` is one of them... we'd have to look at the dox.

**Comment by toolness** [comment]
Umm I guess I was thinking just for the `_normalized_labor_category` field introduced in #1378... I definitely feel queasy about modifying the official `labor_category` field...

**Comment by toolness** [comment]
Ah, yeah, good point. Dang.

**Comment by jseppi** [comment]
bonus with the quotation-mark-approach is we can use CSV libraries for it :)

**Comment by jseppi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a user I should be able to search for a labor category with a comma in it (ex: Engineer, Junior)](https://trello.com/c/ncCHRIFd/245-as-a-user-i-should-be-able-to-search-for-a-labor-category-with-a-comma-in-it-ex-engineer-junior)
