### ISSUE TITLE
Fake Schedule table - currency sign overrunning cell contents

### ISSUE THREAD

**Issue by jseppi** [18F/calc#962]
Low priority since this is only happening on Fake Schedule table (`...tables/fake_schedule.html`)

<img width="728" alt="screen shot 2016-10-25 at 3 50 11 pm" src="https://cloud.githubusercontent.com/assets/697848/19703813/d2bebb56-9aca-11e6-9029-463c19b1305c.png">

**Comment by toolness** [comment]
Is there any way to have the fake schedule table use the same CSS as the schedule 70 table?

Since I'm often using fake schedule to test things out, it'd be nice if they shared as much CSS as possible for "dev/prod" parity, as it were, but whatevs.  If it's hard no bigs.

**Comment by jseppi** [comment]
I'm pretty sure they do have the same CSS classes. I think it has something to do with the table's auto layout not working well with the way we've implemented the currency symbol.

**Comment by hbillings** [comment]
Fixed this a while back!
