### ISSUE TITLE
Clicking on `<alerts-widget>` inside styleguide ajaxform example throws JS error

### ISSUE THREAD

**Issue by toolness** [18F/calc#967]
As mentioned in https://github.com/18F/calc/pull/964#issuecomment-256369123:

1. Visit [`/styleguide/ajaxform`](https://calc-dev.apps.cloud.gov/styleguide/ajaxform).
2. Put "5" in as the answer to "What is 2 + 2?" and drop any file with a `.csv` extension in to the file upload widget and submit the form.
3. Click the words "Uh oh" and open the JS console.

The JS console will contain the following:

![2016-10-26_11-24-03](https://cloud.githubusercontent.com/assets/124687/19732447/c88805ee-9b6e-11e6-97d0-40b7489752da.png)

No idea what's going on here and the traceback isn't very useful, particularly since our jQuery is minified. I wonder if we should keep the un-minified jQuery in dev builds to make debugging things like this easier.

Also, the above screenshot shows a `nrWrapper` in `ajaxform:8` but that doesn't display on my local dev environment.

**Comment by jseppi** [comment]
`nrWrapper` is from New Relic

**Comment by toolness** [comment]
Hmm, it looks like it's happening because jQuery inspects the `disabled` property of every element in the ancestor chain of an event target, and when it looks at the `disabled` property of the `<alerts-widget>`, everything explodes.

This can be reproduced by running the following snippet on any page with an `<alerts-widget>`:

```js
document.getElementsByTagName('alerts-widget')[0].disabled
```

I think this might be happening because our `<alerts-widget>` is extending `HTMLInputElement` but isn't actually an input.  It should be extending `HTMLElement` instead!

**Comment by jseppi** [comment]
whoa o_O
