### ISSUE TITLE
508 - Table Sort

### ISSUE THREAD

**Issue by nickbristow** [18F/calc#97]
In the text for the table head, indicate the column is being sorted on that axis and the order of the sort, 

On the other fields add 'Select to sort ascending/descending'

`<th>` table head text `<span class="sr-only">Select to sort....</span></th>`
`<th>` table head text `<span class="sr-only">Sorted ascending, select to sort descending</span></th>`

Something like that.

**Comment by brethauer** [comment]
Assigning to Shawn since it appears to require some js / d3 work
