### ISSUE TITLE
Store un-minified vendor JS in repository

### ISSUE THREAD

**Issue by toolness** [18F/calc#970]
When working on #967 I found that it was difficult to debug because we're using the minified version of jQuery.  And even thought we have a source map for that file, I think that the browser might not be able to make sense of it because of how we're concatenating stuff ourselves (I could be wrong though).

Anyways, since we're concatenating this stuff ourselves, would it be possible to also minify it ourselves during the build process, and default to not minfying during production?

**Comment by jseppi** [comment]
> default to not minfying during production

I'm a little unclear what you mean. Isn't production when we would want it minified?

**Comment by toolness** [comment]
Ooops, sorry, I meant not minifying during development!

**Comment by jseppi** [comment]
Ha, ok, that makes sense.
Yup, certainly possible. Just gotta track down the non-minified versions of all the `vendor/`'d libs we're using.
