### ISSUE TITLE
Consider using input type=number for min/max experience

### ISSUE THREAD

**Issue by toolness** [18F/calc#971]
I just noticed that we're using `<select>` tags for the min/max experience in the data explorer, rather than `<input type="number">`.  Is there a reason for that, especially since we're supposed to [burn our select tags](https://www.youtube.com/watch?v=CUkMCQR4TpY)?

After looking at the graph of min/max increment queries being made to CALC, it might be useful to use a number input with a default increment value of 5, since that appears to match the most common queries folks are making:

> <img width="927" alt="screen shot 2016-10-25 at 8 53 37 am" src="https://cloud.githubusercontent.com/assets/124687/19742913/11910c4c-9b95-11e6-80bc-d63aae1c7c06.png">

(This is assuming that number inputs can be configured to not _enforce_ their increment sizes, since we do still want it to be possible to e.g. set a min experience of 3.)

**Comment by jseppi** [comment]
Hrm, looks like if you put `step="5"` you will not be able to enter non-multiple-of-5 values:

<img width="298" alt="screen shot 2016-10-26 at 3 45 01 pm" src="https://cloud.githubusercontent.com/assets/697848/19744451/329078e4-9b93-11e6-81b9-b6644706b941.png">
