### ISSUE TITLE
Add CALC tutorial video to about page

### ISSUE THREAD

**Issue by toolness** [18F/calc#973]
As [discussed on Slack](https://gsa-tts.slack.com/archives/calc/p1477514277002896), It would be nice to have this video on the about page:

https://www.youtube.com/watch?v=cWYiu-WIi44

@tram also mentioned that we may want to enable captions by default, as quite a few of the CO offices we visited could be noisy and distracting. 💥 

We might also want to enable YouTube tracking on DAP, if it's not enabled by default, so that we can see how often the video is being viewed.

We'll need some copy introducing the video too (unless we just want to plop it at the top of the page, but that could be weird).

**Comment by jseppi** [comment]
@ericronne is going to make a gif and/or video tutorial, so assigned this one to him

**Comment by toolness** [comment]
Oh cool!  I know we discussed this a year ago, but this is making me want to automate the creation of this GIF, so that we get a fresh new version even when we make visual tweaks...

**Comment by ericronne** [comment]
Whoa, cray. Color me intrigued. Editing and finessing 👌 was required, tho. ;)

**Comment by KellyBailey** [comment]
Can we do a new CALC user tutorial video with Alan narrating?
