### ISSUE TITLE
Sauce on Travis timeouts happen relatively frequently

### ISSUE THREAD

**Issue by jseppi** [18F/calc#978]
They are frustrating because they mark PRs as having failed travis builds :(

This old travis-ci thread suggests using `saucelabs.com:4445` instead of `ondemand.saucelabs.com`:

https://github.com/travis-ci/travis-ci/issues/2718#issuecomment-53583278

**Comment by jseppi** [comment]
cc @toolness

**Comment by toolness** [comment]
Blerg, I tried using that in #979 and it [failed](https://travis-ci.org/18F/calc/builds/171396918) with `urllib.error.URLError: <urlopen error timed out>` 😞

**Comment by jseppi** [comment]
durnit!

**Comment by jseppi** [comment]
here's one I haven't seen before:

```sh
/home/travis/build.sh: line 107:  3070 Killed                  ${sc_dir}/bin/sc ${sc_tunnel_id_arg} -f ${sc_readyfile} -l ${sc_logfile} ${SAUCE_NO_SSL_BUMP_DOMAINS} ${SAUCE_DIRECT_DOMAINS} ${SAUCE_TUNNEL_DOMAINS}  (wd: /tmp/sc.qS1o)
```

**Comment by toolness** [comment]
It looks like this has been recently reported as https://github.com/travis-ci/travis-ci/issues/6914. One of the suggestions I like is to be able to tell the sauce labs addon to retry the connection a bunch of times.
