### ISSUE TITLE
Use bugs for status indicators

### ISSUE THREAD

**Issue by hbillings** [18F/calc#980]
For the user's own price lists, bugs like the WDS uses for their "alpha" and "beta" component indicators might be really helpful: https://standards.usa.gov/labels/

**Comment by jseppi** [comment]
Are "bug" and WDS's "label" the same thing?

**Comment by hbillings** [comment]
LOL, I picked a terrible example page. Though we probably could use labels, depending on how we want to design it. I was thinking of these:
<img width="255" alt="screen shot 2016-10-28 at 11 48 54 am" src="https://cloud.githubusercontent.com/assets/509309/19814623/95dfdea4-9d04-11e6-8a83-fb432bbff117.png">

**Comment by ericronne** [comment]
@hbillings what does a "bug" look like?

**Comment by jseppi** [comment]
@ericronne I think that is TBD! What do you think a bug should look like?

**Comment by ericronne** [comment]
Ah, i thought she was referring to a bug that WDS uses.

So we're talking about designing a way for data uploaders to know the status of their uploads. Could be a bug/icon, but an explicit label is generally more clear. We could also use a bug, label, and color together. I'll noodle on this as i re-style the details page.

I'm thinking we should also indicate status on a user's list of uploaded PL's. Agree?

**Comment by jseppi** [comment]
Yea, I agree.

**Comment by hbillings** [comment]
@ericronne I was thinking of these little labelly things that the standards site uses, but doesn't define:
<img width="283" alt="screen shot 2017-01-03 at 1 36 37 pm" src="https://cloud.githubusercontent.com/assets/509309/21622244/c529631c-d1b9-11e6-85de-0ddf73489d06.png">

But please do what makes sense to you!

**Comment by ericronne** [comment]
Yep
![image](https://cloud.githubusercontent.com/assets/9259185/21622532/8df95546-d1c3-11e6-989e-abb05e9915e4.png)

**Comment by ericronne** [comment]
Blew this out a little more, and added an icon for style and increased accessibility.

![image](https://cloud.githubusercontent.com/assets/9259185/21965909/d767d0e4-db2e-11e6-8d18-01b447e18fa6.png)

**Here are the [icon svg files](https://drive.google.com/open?id=0BwWYNZcEDfwabkg0RmF5Zzl4Yzg).**

**Pending**
BG: #FBEEBE
Icon and text: #825C1E

** Rejected**
BG: #FAD0D0
Icon and text: #BA1D1D

**Approved**
BG: #E6EDC2
Icon and text: #61701C

![image](https://cloud.githubusercontent.com/assets/9259185/21966026/2d4d158a-db31-11e6-95e1-7aca39d42771.png)

**Comment by ericronne** [comment]
lmk if those svg files are funky.
i'll be amazed if they aren't!

**Comment by hbillings** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement price list details style changes](https://trello.com/c/QWtdHarC/235-implement-price-list-details-style-changes)
