### ISSUE TITLE
Clarify terminology for price lists

### ISSUE THREAD

**Issue by hbillings** [18F/calc#981]
The terms we're using for price list statuses are a little confusing. Here are some of my thoughts -- what are yours?
### "New"

Does this show up for all users, or just for admins? From some of the screenshots, it seems like this refers to any PLs a user has submitted, but that haven't been approved by a site admin. It's kind of weird to refer to your own PLs as "new," because presumably they aren't new to you. Would **"awaiting approval"** be a better term?
### "Approved"

I think this makes sense. I wonder, though, if we could do better at conveying that this status means data is now available to the public in CALC.
### "Rejected"

I think this should actually be **"declined,"** as "rejected" has [some pretty strong connotations](http://english.stackexchange.com/questions/47350/what-is-the-best-antonym-for-approve-in-the-context-of-approving-a-business-re). **"Disapproved"** might also work.
### "Unapproved"

This is confusing in conjunction with "rejected." **"Revoked"** is one option that connotates approval being withdrawn. **"Disallowed"** is another.
### "Mute"

I asked around some of the data nerd corners I lurk in about alternatives for this one. It's kind of odd in conjunction with printed text. **"Exclude"** was the suggestion I thought fit best with our use case. **"Hide"** and **"archive"** were some other good ideas. ("The ban-hammer" was my personal favorite, though.)

**Comment by jseppi** [comment]
For "New", another option could be "Awaiting review"

"Rejected" -> "Declined" 👍 

"Unapproved" -> "Revoked" 👍 

I agree "Mute(d)" sounds a bit weird. "Exclude" seems to fit our usage.

**Comment by toolness** [comment]
Agree that this could be a nice Writing Lab issue!

I agree with @jseppi but for "Mute(d)" I strongly prefer <img src="https://media.giphy.com/media/1errwBc680uKA/giphy.gif">

**Comment by toolness** [comment]
Another alternative for "unapproved" is simply **retired**.

This implies that the price list was once active/approved, but is no longer, for reasons that are a normal part of the price list lifecycle.  This was the original intention of "unapproved", really: I didn't want to outright delete the database entry because that would make the operation hard to undo.

So I expect the vast majority of price lists marked "unapproved" to be ones that are essentially "out of commission" or "no longer relevant to market research".  On the other hand, I think the other proposed alternatives--**revoked** and **disallowed**--imply some kind of failure state that may not actually be the case, so I'm not sure how appropriate those terms are. I'm guessing that if I were a CO and I noticed that something of mine was suddenly "disallowed" or "revoked", I might have some anxiety that I'd just done something wrong, when in reality my price lists have simply gone to price list heaven.

**Comment by hbillings** [comment]
I really like how "retired" indicates the serviceable life of the data is over, rather than possibly implying that there are errors. (And I'm all for causing less CO anxiety!)

**Comment by hbillings** [comment]
So I was writing up some copy for the mocks, and had a crazy thought: What if instead of "new," "approved" and "unapproved/retired," we just had the concept of a price list being "public" or "private"? "Private" price lists could *also* be marked "new" or not, according to whether or not they've had action taken on them by an admin or not.

We could also still have the notion of "retiring" a price list. But I like "make private" because it sounds less final (for instance, when we tell admins they have to "unapprove" a price list before they can make changes, it sounds weird to tell them they have to "retire" it...only to bring it, uh, out of retirement?)

Might look something like this in the admin:
<img width="268" alt="screen shot 2016-11-11 at 3 09 27 pm" src="https://cloud.githubusercontent.com/assets/509309/20232039/e6a60c40-a822-11e6-85cf-80468da14a90.png">

When it's new, could be denoted like this in the admin view:
<img width="314" alt="screen shot 2016-11-11 at 3 14 59 pm" src="https://cloud.githubusercontent.com/assets/509309/20232051/f43d762c-a822-11e6-94c0-afb841cedac2.png">

...and like this for COs:
<img width="341" alt="screen shot 2016-11-11 at 3 26 18 pm" src="https://cloud.githubusercontent.com/assets/509309/20232098/46668a2e-a823-11e6-8aa3-54738762bb9c.png">

...and when it's available in CALC, both would see this:
<img width="401" alt="screen shot 2016-11-11 at 3 16 13 pm" src="https://cloud.githubusercontent.com/assets/509309/20232053/f906735c-a822-11e6-9c93-a9ad250c96db.png">

**Comment by jseppi** [comment]
I wonder if we'd run into user confusion about to whom a price list is "Private" -- to other COs, to Data Administrators, to the public?

Taking a cue from WordPress, what about "Published" (for public and available in CALC) and "Draft" (for not-available).

**Comment by hbillings** [comment]
@jseppi I like "Published"! I wonder if there should be different indicators to track whether a list has never been published or has been unpublished...

**Comment by jseppi** [comment]
Maybe if it has never been published, then the "New" or "Awaiting Approval" indicator (in addition to "Retired"/"Unpublished") would make that clear. Blerp.

**Comment by hbillings** [comment]
From google doc conversation:

“Submitted” (awaiting approval) “Draft”
A list that has been submitted but has not yet had action taken on it by an admin. (As differentiated from lists that have been published and then unpublished.)

“Modified”
A list that has either had its vendor details changed or had a new list uploaded. Modified lists should likely also be listed as unpublished or draft.
Note: When a modification is submitted, must it be approved by the admin again?

“Published”
A list that is currently active and available on CALC.

“Unpublished”
A list that is not currently publicly available in CALC, but has been previously published.
Note: Not sure what to call published-then-unpublished lists in the user view. Possibly just lump them in with “submitted,” but that makes them sound as if they haven’t been looked at at all. Perhaps they do not need to be differentiated from other unpublished lists.

“Declined”
A list that has been refused inclusion from CALC on some grounds. A future version of this may have the option of providing feedback to COs as to why a list was declined.

“Retired” (permanently unpublished)
There had been some discussion of a “retired” price list. Would it be valuable to have the concept of a list that has reached the end of its useful life and will not be published again?
