### ISSUE TITLE
Inconsistent spacing on Price List Details page

### ISSUE THREAD

**Issue by jseppi** [18F/calc#991]
This could use some design ❤️, @hbillings. Particularly the spacing between the end of the details `<dl>` and the start of the Valid price list rows.

<img width="534" alt="screen shot 2016-11-01 at 4 10 43 pm" src="https://cloud.githubusercontent.com/assets/697848/19907681/d8dcd5e4-a04d-11e6-9a8b-31682cc9b355.png">

URL: `/data-capture/price-lists/<some_primary_key>`

**Comment by hbillings** [comment]
So this is probably super obvious, but I can't figure out how to get to this page, even with the url fragment. What link takes you to this page?

I tried navigating to an approved price list (`/admin/data_capture/approvedpricelist/3/`) and swapping `approvedpricelist` for `price-lists`. I got a 404.

**Comment by jseppi** [comment]
Leave out the `/admin` at the start of your example URL. This is for the user-facing Price List Details page. You could manually navigate by starting at `/account` and clicking one of the price lists there, or by going to `/price-lists`, which should list all of the price lists associated with your user account.

**Comment by hbillings** [comment]
OMG, I needed to merge `develop`. I thought I did that already.  Is this week over yet? >_<

**Comment by hbillings** [comment]
This still could use some design love, but this particular problem is no longer a problem. It is an ex-problem.
